<?php
/**
 * AlmancaPro - B1 mufredati.
 */
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME'])
    && basename((string)$_SERVER['SCRIPT_FILENAME']) === basename(__FILE__)
    && PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

function almancapro_curriculum_b1(): array
{
    return array_merge(
        almancapro_curriculum_b1_part1(),
        almancapro_curriculum_b1_part2(),
        almancapro_curriculum_b1_part3()
    );
}

function almancapro_curriculum_b1_part1(): array
{
    return [
        [
            'slug' => 'b1-m1-sifat-cekimi',
            'level' => 'B1',
            'title' => 'Sıfat Çekimi',
            'description' => 'Sıfatların isimden önce gelirken aldığı ekler. B1\'in en teknik konusu.',
            'lessons' => [
                [
                    'slug' => 'b1-sifat-belirli',
                    'title' => 'Belirli Artikelden Sonra Sıfat',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'der/die/das sonrası sıfat eklerini doğru vermek.',
                    'summary' => 'Bu grup en kolayıdır: neredeyse her yerde -en gelir.',
                    'skills' => ['adj_decl_definite'],
                    'prereq' => ['dativ'=>90,'akkusativ'=>90,'adjective_basics'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada sıfat İSİMDEN ÖNCE gelirse ek alır; fiilden sonra gelirse ek almaz.\n\nDas Auto ist neu. (ek yok)\nDas neue Auto ist teuer. (ek var: neue)\n\nBu ek artikelin türüne, ismin cinsiyetine ve hale bağlıdır."],
                        ['t'=>'table','h'=>'Belirli artikelden sonra','b'=>"Nominativ:\nder neue Chef · die neue Kollegin · das neue Auto · die neuen Autos\n\nAkkusativ:\nden neuen Chef · die neue Kollegin · das neue Auto · die neuen Autos\n\nDativ:\ndem neuen Chef · der neuen Kollegin · dem neuen Auto · den neuen Autos"],
                        ['t'=>'rule','h'=>'Basit kural','b'=>"Belirli artikelden sonra yalnızca İKİ ek vardır: -e ve -en.\n\n-e gelir: Nominativ tekil (3 cinsiyet) ve Akkusativ dişil/nötr\n-en gelir: DİĞER HER YERDE\n\nYani beş kutucuk -e, geri kalan her şey -en."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede sıfat hiç değişmez: \"yeni araba\", \"yeni arabayı\", \"yeni arabaya\". Almancada sıfat üç bilgiye göre çekilir: artikel türü + cinsiyet + hal.\n\nBu, Türkçe konuşan için tamamen yeni bir kavramdır ve ancak bol tekrarla otomatikleşir."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Belirli artikelden sonra \"varsayılan\" ek -en'dir. Sadece beş istisnayı (Nominativ tekil üçü + Akkusativ dişil ve nötr) -e olarak işaretle. Bu bir kısayoldur; tablo yukarıdadır.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Fiilden sonra gelen sıfata da ek vermek: \"Das Auto ist neue\" yanlıştır. Sıfat isimden önce gelmiyorsa ek almaz.",'c'=>1],
                    ],
                    'vocab' => ['neu','alt','gut','groß','klein','wichtig'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'adj_decl_definite','q'=>'Boşluğu doldur: "Der neu___ Chef kommt morgen."','a'=>'e','exp'=>'Nominativ eril tekil → -e: der neue Chef.','vg'=>'adjdef-nom'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'adj_decl_definite','q'=>'Boşluğu doldur: "Ich kenne den neu___ Chef."','a'=>'en','exp'=>'Akkusativ eril → -en: den neuen Chef.','vg'=>'adjdef-akk'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'adj_decl_definite','q'=>'"Ich arbeite mit ___ Kollegin." (die neue Kollegin) Hangisi doğru?','a'=>'der neuen','opts'=>['der neuen','die neue','der neue','den neuen'],'exp'=>'mit + Dativ; dişil Dativ → der neuen.','vg'=>'adjdef-dat'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'adj_decl_definite','q'=>'Hangi cümle doğrudur?','a'=>'Das Auto ist neu.','opts'=>['Das Auto ist neu.','Das Auto ist neue.','Das Auto ist neuen.','Das Auto ist neuer.'],'exp'=>'Sıfat fiilden sonra geliyorsa ek almaz.','vg'=>'adjdef-predicative'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'adj_decl_definite','q'=>'"Yeni arabayı görüyorum" cümlesini yaz. (das Auto, neu)','a'=>'Ich sehe das neue Auto.','exp'=>'Akkusativ nötr → das neue Auto.','vg'=>'adjdef-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-sifat-belirsiz',
                    'title' => 'Belirsiz Artikelden Sonra Sıfat',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'ein/eine/kein/mein sonrası sıfat eklerini vermek.',
                    'summary' => 'Burada sıfat, artikelin veremediği bilgiyi taşımak zorundadır.',
                    'skills' => ['adj_decl_indefinite'],
                    'prereq' => ['adj_decl_definite'=>85],
                    'sections' => [
                        ['t'=>'why','h'=>'Neden farklı?','b'=>"\"ein\" kelimesi eril Nominativ ve nötr Nominativ/Akkusativ'de cinsiyeti GÖSTERMEZ:\n\nein Chef → eril mi nötr mü belli değil\nein Auto → aynı sorun\n\nBu üç kutucukta bilgiyi SIFAT taşır ve belirli artikelin ekini alır:\nein neuer Chef (der gibi -er)\nein neues Auto (das gibi -es)"],
                        ['t'=>'table','h'=>'Belirsiz artikelden sonra','b'=>"Nominativ:\nein neuer Chef · eine neue Kollegin · ein neues Auto · keine neuen Autos\n\nAkkusativ:\neinen neuen Chef · eine neue Kollegin · ein neues Auto · keine neuen Autos\n\nDativ:\neinem neuen Chef · einer neuen Kollegin · einem neuen Auto · keinen neuen Autos"],
                        ['t'=>'rule','h'=>'Kural','b'=>"Aynı çekim şu kelimelerden sonra da geçerlidir:\nein, eine, kein, keine\nmein, dein, sein, ihr, unser, euer, Ihr\n\nÇoğulda \"ein\" yoktur ama kein/mein vb. varsa sıfat -en alır."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Şu soruyu sor: \"Artikel cinsiyeti gösteriyor mu?\" Göstermiyorsa (ein Chef, ein Auto) sıfat der/das ekini alır (-er / -es). Gösteriyorsa (einen, einem, einer) sıfat -en alır.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"ein neue Chef\" demek. Eril Nominativ'de artikel bilgi vermediği için sıfat -er alır: ein neuER Chef.",'c'=>1],
                    ],
                    'vocab' => ['neu','gut','schwierig','möglich'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'adj_decl_indefinite','q'=>'Boşluğu doldur: "Das ist ein neu___ Chef."','a'=>'er','exp'=>'Eril Nominativ, artikel bilgi vermiyor → sıfat -er alır.','vg'=>'adjindef-nom-m'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'adj_decl_indefinite','q'=>'Boşluğu doldur: "Das ist ein neu___ Auto."','a'=>'es','exp'=>'Nötr Nominativ → sıfat -es alır (das gibi).','vg'=>'adjindef-nom-n'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'adj_decl_indefinite','q'=>'"Ich habe ___ Termin." (ein wichtiger Termin, Akkusativ) Hangisi doğru?','a'=>'einen wichtigen','opts'=>['einen wichtigen','ein wichtiger','einen wichtiger','einem wichtigen'],'exp'=>'Akkusativ eril → einen wichtigen Termin.','vg'=>'adjindef-akk'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'adj_decl_indefinite','q'=>'"Ich arbeite mit ___ Kollegen." (ein neuer Kollege) Hangisi doğru?','a'=>'einem neuen','opts'=>['einem neuen','einen neuen','ein neuer','einer neuen'],'exp'=>'mit + Dativ eril → einem neuen Kollegen.','vg'=>'adjindef-dat'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'adj_decl_indefinite','q'=>'"Yeni bir daire arıyorum" cümlesini yaz. (die Wohnung, neu)','a'=>'Ich suche eine neue Wohnung.','exp'=>'Dişil Akkusativ → eine neue Wohnung.','vg'=>'adjindef-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-sifat-artikelsiz',
                    'title' => 'Artikelsiz Sıfat Çekimi',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Artikel yokken sıfatın artikelin işini üstlendiğini kavramak.',
                    'summary' => 'İş ilanlarında, tariflerde ve genel ifadelerde çok sık karşına çıkar.',
                    'skills' => ['adj_decl_zero'],
                    'prereq' => ['adj_decl_indefinite'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Artikel yoksa sıfat, belirli artikelin ekini alır (Genitiv hariç):\n\nNominativ: guter Kaffee · gute Milch · gutes Brot · gute Ideen\nAkkusativ: guten Kaffee · gute Milch · gutes Brot · gute Ideen\nDativ: gutem Kaffee · guter Milch · gutem Brot · guten Ideen"],
                        ['t'=>'usage','h'=>'Nerede karşına çıkar?','b'=>"Genel ifadeler: Ich trinke gerne starken Kaffee.\nÇoğul, artikelsiz: Wir suchen erfahrene Mitarbeiter.\nMalzeme listesi: mit frischem Gemüse\nİş ilanları: Gute Deutschkenntnisse erforderlich.",'c'=>1],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"iyi kahve\" hiçbir durumda değişmez. Almancada artikel yoksa bilgi yükü tamamen sıfata biner ve sıfat üç bilgiyi birden taşır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Artikelsiz kullanımda sıfata -en vermek: \"mit frischen Gemüse\" yanlıştır (tekil kastediliyorsa). Doğrusu \"mit frischem Gemüse\".",'c'=>1],
                    ],
                    'vocab' => ['gut','frisch','erfahren','notwendig'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'adj_decl_zero','q'=>'Boşluğu doldur: "Ich trinke gern stark___ Kaffee." (Akkusativ eril)','a'=>'en','exp'=>'Artikelsiz Akkusativ eril → -en: starken Kaffee.','vg'=>'adjzero-akk'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'adj_decl_zero','q'=>'"Wir suchen ___ Mitarbeiter." (erfahren, çoğul Akkusativ) Hangisi doğru?','a'=>'erfahrene','opts'=>['erfahrene','erfahrenen','erfahrener','erfahrenes'],'exp'=>'Artikelsiz çoğul Akkusativ → -e: erfahrene Mitarbeiter.','vg'=>'adjzero-plural'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'adj_decl_zero','q'=>'"mit ___ Gemüse" (frisch, Dativ nötr) Hangisi doğru?','a'=>'frischem','opts'=>['frischem','frischen','frisches','frischer'],'exp'=>'Artikelsiz Dativ nötr → -em.','vg'=>'adjzero-dat'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'adj_decl_zero','q'=>'"İyi Almanca bilgisi gereklidir" cümlesini yaz. (gute Deutschkenntnisse, erforderlich)','a'=>'Gute Deutschkenntnisse sind erforderlich.','exp'=>'Çoğul Nominativ artikelsiz → -e; çoğul özne "sind" alır.','vg'=>'adjzero-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'adj_decl_zero','q'=>'Artikelsiz sıfat çekiminde sıfat hangi ekleri alır?','a'=>'Belirli artikelin eklerini','opts'=>['Belirli artikelin eklerini','Her zaman -en','Hiç ek almaz','Belirsiz artikelin eklerini'],'exp'=>'Artikel yoksa bilgiyi sıfat taşır; der/die/das eklerini alır.','vg'=>'adjzero-rule'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'b1-m2-ilgi-cumlesi',
            'level' => 'B1',
            'title' => 'İlgi Cümleleri',
            'description' => 'der, die, das ile kurulan ilgi cümleleri. Cümleleri birleştirmenin yolu.',
            'lessons' => [
                [
                    'slug' => 'b1-relativ-nominativ',
                    'title' => 'İlgi Cümlesi: Nominativ',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'İlgi zamiriyle iki cümleyi birleştirmek.',
                    'summary' => 'İlgi cümlesi, B1 seviyesinin en görünür işaretidir. Cümlelerin uzunluğunu ve derinliğini artırır.',
                    'skills' => ['relative_clause_basics','relative_nominativ'],
                    'prereq' => ['nebensatz_verb_final'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"İlgi zamiri, bahsettiğin isme göre CİNSİYET ve SAYI alır; cümledeki görevine göre HAL alır. Fiil yan cümlenin SONUNA gider.\n\nDas ist der Kollege. Er hilft mir.\n→ Das ist der Kollege, der mir hilft.\n\nDas ist die Firma. Sie sucht Mitarbeiter.\n→ Das ist die Firma, die Mitarbeiter sucht."],
                        ['t'=>'table','h'=>'Nominativ ilgi zamirleri','b'=>"eril: der\ndişil: die\nnötr: das\nçoğul: die\n\nBunlar belirli artikellerle aynıdır."],
                        ['t'=>'explanation','h'=>'İki soru sor','b'=>"1. Hangi isimden bahsediyorum? → cinsiyet ve sayıyı verir\n2. Bu isim yan cümlede ne görevde? → hali verir\n\nDas ist der Chef, der die Firma leitet.\nİsim: der Chef (eril) → der/den/dem\nGörev: özne (kim yönetiyor?) → Nominativ → der"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede ilgi cümlesi ORTAÇ (sıfat-fiil) ile kurulur ve isimden ÖNCE gelir:\n\"Bana yardım eden iş arkadaşı\"\n\nAlmancada isimden SONRA gelir ve ayrı bir cümledir:\n\"der Kollege, der mir hilft\"\n\nBu yön farkı Türkçe konuşanlar için ilk başta çok zorlayıcıdır. Almanca cümleyi soldan sağa okumaya alışman gerekir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Virgülü unutmak veya fiili sonda bırakmamak: \"der Kollege der hilft mir\" yanlıştır. Doğrusu \"der Kollege, der mir hilft\".",'c'=>1],
                    ],
                    'vocab' => ['Kollege','Firma','Mitarbeiter','Vorgesetzte'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'relative_nominativ','q'=>'Boşluğu doldur: "Das ist der Kollege, ___ mir hilft."','a'=>'der','exp'=>'der Kollege (eril) + özne görevi (Nominativ) → der.','vg'=>'rel-nom-m'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'relative_nominativ','q'=>'Boşluğu doldur: "Das ist die Firma, ___ Mitarbeiter sucht."','a'=>'die','exp'=>'die Firma (dişil) + Nominativ → die.','vg'=>'rel-nom-f'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'relative_clause_basics','q'=>'Cümleleri birleştir: "Das ist das Formular." + "Es ist wichtig."','a'=>'Das ist das Formular, das wichtig ist.','exp'=>'das Formular (nötr) + Nominativ → das; fiil sonda.','vg'=>'rel-combine'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'relative_clause_basics','q'=>'Hatayı düzelt: "Das ist der Chef, der leitet die Firma."','a'=>'Das ist der Chef, der die Firma leitet.','exp'=>'İlgi cümlesinde fiil sona gider.','vg'=>'rel-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'relative_nominativ','q'=>'"Bana yardım eden iş arkadaşı" ifadesinin Almanca yapısı nasıldır?','a'=>'der Kollege, der mir hilft','opts'=>['der Kollege, der mir hilft','der mir hilft Kollege','der helfende mir Kollege','Kollege der hilft mir'],'exp'=>'Almancada ilgi cümlesi isimden SONRA gelir.','vg'=>'rel-structure'],
                    ],
                ],
                [
                    'slug' => 'b1-relativ-akk-dat',
                    'title' => 'İlgi Cümlesi: Akkusativ ve Dativ',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'İlgi zamirini yan cümledeki göreve göre çekmek.',
                    'summary' => 'Burada hal bilgisi devreye giriyor. A2\'de öğrendiğin Akkusativ/Dativ ayrımı meyvesini veriyor.',
                    'skills' => ['relative_akkusativ','relative_dativ'],
                    'prereq' => ['relative_nominativ'=>85,'akk_dat_distinction'=>90],
                    'sections' => [
                        ['t'=>'table','h'=>'İlgi zamiri tablosu','b'=>"           eril    dişil   nötr    çoğul\nNominativ: der     die     das     die\nAkkusativ: den     die     das     die\nDativ:     dem     der     dem     denen\n\nTek sürpriz: çoğul Dativ \"denen\"dir (den değil)."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Hal, yan cümledeki göreve göre belirlenir:','de'=>'Das ist der Kollege, den ich gestern getroffen habe. (Akkusativ: onu gördüm)\nDas ist der Kollege, dem ich geholfen habe. (Dativ: ona yardım ettim)','tr'=>'Dün karşılaştığım iş arkadaşı. / Yardım ettiğim iş arkadaşı.'],
                        ['t'=>'rule','h'=>'Edatlı ilgi cümlesi','b'=>"Yan cümlede edat varsa, edat ilgi zamirinin ÖNÜNE geçer:\n\nDas ist die Firma, bei der ich arbeite.\nDas ist das Projekt, an dem wir arbeiten.\nDas ist der Kollege, mit dem ich spreche.\n\nEdat kendi halini dayatır: bei + Dativ → bei der."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"çalıştığım firma\" derken hal bilgisi ortacın içinde kaybolur. Almancada bu bilgi açıkça görünür: \"die Firma, bei der ich arbeite\". Almanca daha açık, Türkçe daha kısadır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Hali ana cümledeki isme göre seçmek. İlgi zamirinin hali YAN CÜMLEDEKİ göreve göre belirlenir, ana cümledeki isme göre değil.",'c'=>1],
                    ],
                    'vocab' => ['treffen','Projekt','Firma','Kollege'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'relative_akkusativ','q'=>'Boşluğu doldur: "Das ist der Kollege, ___ ich gestern getroffen habe."','a'=>'den','exp'=>'Yan cümlede nesne (kimi gördüm) → Akkusativ eril → den.','vg'=>'rel-akk'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'relative_dativ','q'=>'Boşluğu doldur: "Das ist der Kollege, ___ ich geholfen habe."','a'=>'dem','exp'=>'helfen Dativ ister → dem.','vg'=>'rel-dat'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'relative_dativ','q'=>'"Das ist die Firma, ___ ich arbeite." (bei ile) Hangisi doğru?','a'=>'bei der','opts'=>['bei der','bei die','bei dem','die bei'],'exp'=>'bei + Dativ; dişil Dativ → der. Edat zamirin önüne geçer.','vg'=>'rel-prep'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'relative_dativ','q'=>'Çoğul Dativ ilgi zamiri hangisidir?','a'=>'denen','opts'=>['denen','den','der','die'],'exp'=>'Çoğul Dativ ilgi zamiri "denen"dir; artikelden farklıdır.','vg'=>'rel-denen'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'relative_akkusativ','q'=>'Cümleleri birleştir: "Das ist das Projekt." + "Wir haben es letztes Jahr angefangen."','a'=>'Das ist das Projekt, das wir letztes Jahr angefangen haben.','exp'=>'Nötr Akkusativ → das; Partizip + yardımcı fiil sonda.','vg'=>'rel-combine2'],
                    ],
                ],
                [
                    'slug' => 'b1-genitiv',
                    'title' => 'Genitiv Temeli',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Sahiplik bildirmenin resmi biçimini tanımak ve okuyabilmek.',
                    'summary' => 'Genitiv resmi yazışmada ve sözleşmelerde sık geçer; konuşmada yerini "von + Dativ" alır.',
                    'skills' => ['genitiv'],
                    'prereq' => ['dativ'=>90],
                    'sections' => [
                        ['t'=>'table','h'=>'Genitiv biçimleri','b'=>"der → des + isme -s/-es\ndie → der\ndas → des + isme -s/-es\ndie (çoğul) → der\n\nder Chef → des Chefs\ndie Firma → der Firma\ndas Auto → des Autos\ndie Mitarbeiter → der Mitarbeiter"],
                        ['t'=>'rule','h'=>'Konuşmada von + Dativ','b'=>"Günlük konuşmada Genitiv yerine \"von + Dativ\" kullanılır:\n\nresmi: das Auto des Chefs\nkonuşma: das Auto von dem Chef / vom Chef\n\nİkisi de doğrudur; resmi metinlerde Genitiv tercih edilir."],
                        ['t'=>'rule','h'=>'Genitiv isteyen edatlar','b'=>"während — sırasında\nwegen — yüzünden\ntrotz — rağmen\naufgrund — nedeniyle\ninnerhalb — içinde (süre/alan)\n\nwährend der Arbeitszeit — çalışma saati içinde\nwegen des Wetters — hava yüzünden\n\nKonuşmada bunlar sıkça Dativ ile de kullanılır (wegen dem Wetter), ancak resmi yazıda Genitiv doğrudur."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede sahiplik iki ekle kurulur: \"amir-İN araba-SI\". Almancada isim değişmez, artikel değişir ve eril/nötr isimlere -s eklenir. Türkçede sahip önce gelir, Almancada sahip SONRA gelir:\n\nTürkçe: amirin arabası\nAlmanca: das Auto des Chefs (araba amirin)"],
                    ],
                    'vocab' => ['während','Vertrag','Firma','Mitarbeiter','Frist'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'genitiv','q'=>'"amirin arabası" Genitiv ile nasıl yazılır?','a'=>'das Auto des Chefs','opts'=>['das Auto des Chefs','das Auto der Chef','das Chefs Auto','des Chef Auto'],'exp'=>'Eril Genitiv: des + isim + -s. Sahip sonra gelir.','vg'=>'gen-form'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'genitiv','q'=>'"während" edatı hangi hali ister?','a'=>'Genitiv','opts'=>['Genitiv','Dativ','Akkusativ','Nominativ'],'exp'=>'während + Genitiv: während der Arbeitszeit.','vg'=>'gen-prep'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'genitiv','q'=>'Konuşma dilinde Genitiv yerine ne kullanılır?','a'=>'von + Dativ','opts'=>['von + Dativ','für + Akkusativ','mit + Dativ','zu + Dativ'],'exp'=>'das Auto vom Chef = das Auto des Chefs.','vg'=>'gen-spoken'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'genitiv','q'=>'Boşluğu doldur: "Die Frist ___ Vertrags läuft ab." (der Vertrag)','a'=>'des','exp'=>'Eril Genitiv → des Vertrags.','vg'=>'gen-fill'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'genitiv','q'=>'"Firmanın adı" ifadesini Genitiv ile yaz. (die Firma, der Name)','a'=>'der Name der Firma','exp'=>'Dişil Genitiv → der Firma.','vg'=>'gen-produce'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'b1-m3-passiv',
            'level' => 'B1',
            'title' => 'Edilgen Yapı (Passiv)',
            'description' => 'İşi kimin yaptığı değil, ne yapıldığı önemli olduğunda kullanılan yapı.',
            'lessons' => [
                [
                    'slug' => 'b1-passiv-praesens',
                    'title' => 'Präsens Passiv',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'werden + Partizip II ile edilgen cümle kurmak.',
                    'summary' => 'İş talimatları, kurallar ve süreç anlatımları neredeyse hep edilgendir.',
                    'skills' => ['passive_present','werden_uses'],
                    'prereq' => ['partizip_ii_irregular'=>85,'perfekt'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Yapı','b'=>"Passiv = werden (çekimli) + Partizip II (sonda)\n\nAktiv: Der Techniker prüft die Maschine.\nPassiv: Die Maschine wird geprüft.\n\nwerden çekimi:\nich werde · du wirst · er wird · wir werden · ihr werdet · sie werden"],
                        ['t'=>'why','h'=>'Neden kullanılır?','b'=>"İşi kimin yaptığı önemsiz veya bilinmiyorsa edilgen kullanılır. Bu yüzden:\n\n- İş talimatlarında: Die Maschine wird jeden Tag geprüft.\n- Kurallarda: Hier wird nicht geraucht.\n- Süreç anlatımında: Das Formular wird ausgefüllt und eingereicht.\n\nİşi yapan söylenecekse \"von + Dativ\" eklenir:\nDie Maschine wird von dem Techniker geprüft."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede edilgen yapı fiilin içine giren -il/-in ekiyle yapılır: \"kontrol ed-il-iyor\". Almancada iki ayrı parça gerekir: werden + Partizip II.\n\nMantık aynıdır, yapı farklıdır. Türkçe konuşan için kavram tanıdıktır, bu bir avantajdır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Passiv için \"sein\" kullanmak: \"Die Maschine ist geprüft\" bir DURUM anlatır (kontrol edilmiş durumda). \"Die Maschine wird geprüft\" ise bir SÜREÇ anlatır (kontrol ediliyor). İkisi farklıdır.",'c'=>1],
                    ],
                    'vocab' => ['werden (Passiv)','geprüft','hergestellt','Anweisung','Sicherheit'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'passive_present','q'=>'"Makine her gün kontrol ediliyor" nasıl denir?','a'=>'Die Maschine wird jeden Tag geprüft.','opts'=>['Die Maschine wird jeden Tag geprüft.','Die Maschine ist jeden Tag geprüft.','Die Maschine hat jeden Tag geprüft.','Die Maschine prüft jeden Tag.'],'exp'=>'Passiv = werden + Partizip II.','vg'=>'pass-form'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'passive_present','q'=>'Bu cümleyi edilgen yap: "Der Techniker prüft die Maschine."','a'=>'Die Maschine wird geprüft.','alt'=>['Die Maschine wird von dem Techniker geprüft.','Die Maschine wird vom Techniker geprüft.'],'exp'=>'Nesne özne olur; werden + Partizip II.','vg'=>'pass-transform'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'passive_present','q'=>'Edilgen cümlede işi yapan nasıl belirtilir?','a'=>'von + Dativ','opts'=>['von + Dativ','für + Akkusativ','mit + Dativ','durch + Nominativ'],'exp'=>'von dem Techniker = teknisyen tarafından.','vg'=>'pass-agent'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'passive_present','q'=>'"Die Maschine ist geprüft." ile "Die Maschine wird geprüft." arasındaki fark nedir?','a'=>'İlki durum, ikincisi süreç anlatır','opts'=>['İlki durum, ikincisi süreç anlatır','İkisi de aynıdır','İlki gelecek, ikincisi şimdiki zaman','İlki yanlıştır'],'exp'=>'Zustandspassiv (sein) durum, Vorgangspassiv (werden) süreç bildirir.','vg'=>'pass-vs-state'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'passive_present','q'=>'"Ürün Almanya\'da üretiliyor" cümlesini edilgen yaz. (das Produkt, herstellen)','a'=>'Das Produkt wird in Deutschland hergestellt.','exp'=>'werden + hergestellt (ayrılabilir fiil: her-ge-stellt).','vg'=>'pass-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-passiv-gecmis',
                    'title' => 'Geçmiş Zamanda Passiv ve lassen',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Geçmiş edilgen biçimleri tanımak ve lassen fiilini kullanmak.',
                    'summary' => 'Resmi yazışmada ve rapor dilinde en sık karşılaşacağın yapılar.',
                    'skills' => ['passive_past','lassen'],
                    'prereq' => ['passive_present'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Geçmiş edilgen','b'=>"Präteritum Passiv: wurde + Partizip II\n  Die Maschine wurde gestern geprüft.\n\nPerfekt Passiv: ist + Partizip II + worden\n  Die Maschine ist gestern geprüft worden.\n\nDikkat: Perfekt Passiv'de \"geworden\" değil \"worden\" kullanılır."],
                        ['t'=>'rule','h'=>'Modal + Passiv','b'=>"Modal fiille birlikte: modal + Partizip II + werden\n\nDas Formular muss ausgefüllt werden. — Formun doldurulması gerekiyor.\nDie Anweisung kann nicht geändert werden. — Talimat değiştirilemez."],
                        ['t'=>'explanation','h'=>'lassen fiili','b'=>"lassen + Infinitiv = birine bir işi YAPTIRMAK\n\nIch lasse das Auto reparieren. — Arabayı tamir ettiriyorum.\nEr lässt die Unterlagen kopieren. — Belgeleri kopyalatıyor.\n\nAyrıca \"izin vermek\" anlamı da vardır:\nLassen Sie mich bitte ausreden. — Lütfen sözümü bitirmeme izin verin."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Perfekt Passiv'de \"geworden\" kullanmak: \"ist geprüft geworden\" yanlıştır. Doğrusu \"ist geprüft worden\"dır.",'c'=>1],
                    ],
                    'vocab' => ['lassen','werden (Passiv)','Anweisung','genehmigen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'passive_past','q'=>'"Makine dün kontrol edildi" (Präteritum Passiv) nasıl denir?','a'=>'Die Maschine wurde gestern geprüft.','opts'=>['Die Maschine wurde gestern geprüft.','Die Maschine war gestern geprüft.','Die Maschine hat gestern geprüft.','Die Maschine ist gestern prüfen.'],'exp'=>'wurde + Partizip II.','vg'=>'passpast-form'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'passive_past','q'=>'Perfekt Passiv\'de hangi biçim kullanılır?','a'=>'ist ... worden','opts'=>['ist ... worden','ist ... geworden','hat ... worden','war ... geworden'],'exp'=>'Perfekt Passiv: ist + Partizip II + worden.','vg'=>'passpast-worden'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'passive_past','q'=>'"Formun doldurulması gerekiyor" nasıl denir?','a'=>'Das Formular muss ausgefüllt werden.','opts'=>['Das Formular muss ausgefüllt werden.','Das Formular muss ausfüllen.','Das Formular wird ausgefüllt müssen.','Das Formular muss ausgefüllt sein.'],'exp'=>'Modal + Partizip II + werden.','vg'=>'passpast-modal'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'lassen','q'=>'"Arabayı tamir ettiriyorum" cümlesini yaz. (reparieren)','a'=>'Ich lasse das Auto reparieren.','exp'=>'lassen + Infinitiv = yaptırmak.','vg'=>'lassen-produce'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'lassen','q'=>'"Ich lasse die Unterlagen kopieren." ne anlama gelir?','a'=>'Belgeleri kopyalatıyorum','opts'=>['Belgeleri kopyalatıyorum','Belgeleri kopyalıyorum','Belgeleri bırakıyorum','Belgeleri kopyalamıyorum'],'exp'=>'lassen + Infinitiv: işi başkasına yaptırmak.','vg'=>'lassen-meaning'],
                    ],
                ],
            ],
        ],
    ];
}

function almancapro_curriculum_b1_part2(): array
{
    return [
        [
            'slug' => 'b1-m4-konjunktiv',
            'level' => 'B1',
            'title' => 'Konjunktiv II: Kibarlık ve Varsayım',
            'description' => 'würde, hätte, wäre, könnte. Almanya\'da profesyonel iletişimin dili.',
            'lessons' => [
                [
                    'slug' => 'b1-konjunktiv-wuerde',
                    'title' => 'würde + Infinitiv',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Kibar istek ve varsayım cümleleri kurmak.',
                    'summary' => 'Bu yapı, Almancada kibar görünmenin en pratik yoludur.',
                    'skills' => ['konjunktiv_ii_wuerde'],
                    'prereq' => ['modal_koennen'=>90,'perfekt'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Yapı','b'=>"würde (çekimli) + Infinitiv (sonda)\n\nich würde · du würdest · er würde · wir würden · ihr würdet · sie würden\n\nIch würde gern früher anfangen.\nWürden Sie mir bitte helfen?"],
                        ['t'=>'why','h'=>'Neden kullanılır?','b'=>"1. Kibar istek/rica:\n   Ich würde gern einen Termin vereinbaren.\n\n2. Gerçek dışı durum:\n   Ich würde mehr lernen, wenn ich Zeit hätte.\n\n3. Kibar öneri:\n   Ich würde vorschlagen, dass wir morgen anfangen.\n\nAlman iş ortamında doğrudan istek yerine würde kullanmak profesyonellik göstergesidir."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede kibarlık \"-ebilir miyim\", \"isterdim\" gibi eklerle kurulur ve fiile gömülüdür. Almancada ayrı bir yardımcı fiil (würde) eklenir ve asıl fiil mastar olarak sona gider.\n\nTürkçe: Daha erken başlamak isterdim.\nAlmanca: Ich würde gern früher anfangen."],
                        ['t'=>'usage','h'=>'İş yerinde','b'=>"Doğrudan: Ich will einen anderen Schichtplan. (kaba durabilir)\nKibar: Ich würde gern über den Schichtplan sprechen. (profesyonel)\n\nBu fark, Almanya'da iş ilişkilerinde önemlidir.",'c'=>1],
                    ],
                    'vocab' => ['würde','vorschlagen','Vorschlag','Termin verschieben'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'konjunktiv_ii_wuerde','q'=>'"Daha erken başlamak isterdim" nasıl denir?','a'=>'Ich würde gern früher anfangen.','opts'=>['Ich würde gern früher anfangen.','Ich will früher anfangen.','Ich würde gern früher anfange.','Ich werde gern früher anfangen.'],'exp'=>'würde + Infinitiv sonda.','vg'=>'wuerde-form'],
                        ['type'=>'conjugation','mode'=>'recall','skill'=>'konjunktiv_ii_wuerde','q'=>'Boşluğu doldur: "___ Sie mir bitte helfen?"','a'=>'Würden','exp'=>'Sie ile würden; soru olduğu için başa geçti.','vg'=>'wuerde-conj'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'konjunktiv_ii_wuerde','q'=>'Hatayı düzelt: "Ich würde gern mehr lerne."','a'=>'Ich würde gern mehr lernen.','exp'=>'würde\'den sonra ikinci fiil mastar kalır.','vg'=>'wuerde-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'konjunktiv_ii_wuerde','q'=>'Amirine vardiya planını konuşmak istediğini söylüyorsun. En profesyonel biçim hangisi?','a'=>'Ich würde gern über den Schichtplan sprechen.','opts'=>['Ich würde gern über den Schichtplan sprechen.','Ich will über den Schichtplan sprechen.','Sie müssen den Schichtplan ändern.','Ich spreche über den Schichtplan.'],'exp'=>'Konjunktiv II profesyonel ve kibar tondur.','vg'=>'wuerde-workplace'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'konjunktiv_ii_wuerde','q'=>'"Bir randevu almak isterdim" cümlesini yaz.','a'=>'Ich würde gern einen Termin vereinbaren.','alt'=>['Ich würde gerne einen Termin vereinbaren.'],'exp'=>'würde + gern + mastar sonda.','vg'=>'wuerde-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-konjunktiv-haette-waere',
                    'title' => 'hätte, wäre ve modal Konjunktiv',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'würde yerine doğrudan Konjunktiv kullanılan fiilleri bilmek.',
                    'summary' => 'Bazı fiillerde würde kullanılmaz; kendi Konjunktiv biçimleri vardır.',
                    'skills' => ['konjunktiv_ii_haette_waere','konjunktiv_ii_modal','unreal_conditions'],
                    'prereq' => ['konjunktiv_ii_wuerde'=>85],
                    'sections' => [
                        ['t'=>'table','h'=>'Doğrudan Konjunktiv biçimleri','b'=>"sein → wäre (ich wäre, du wärst, er wäre, wir wären)\nhaben → hätte (ich hätte, du hättest, er hätte, wir hätten)\nkönnen → könnte\nmüssen → müsste\nsollen → sollte\ndürfen → dürfte\nwollen → wollte\n\nBu fiillerde würde KULLANILMAZ."],
                        ['t'=>'rule','h'=>'Gerçek dışı koşullar','b'=>"wenn + Konjunktiv II, ana cümlede würde veya Konjunktiv II:\n\nWenn ich mehr Zeit hätte, würde ich mehr lernen.\nWenn ich du wäre, würde ich mit dem Chef sprechen.\nWenn ich Deutsch könnte, hätte ich bessere Chancen.\n\nAnlam: gerçekte böyle değil, varsayım yapıyorum."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede bu yapı \"-se/-sa\" ve \"-erdi\" ekleriyle kurulur: \"Vaktim olsaydı daha çok çalışırdım.\" Mantık aynıdır.\n\nFark: Almancada koşul cümlesinde fiil SONA gider ve ana cümlede würde/Konjunktiv gerekir. Yani iki yerde birden değişiklik yaparsın."],
                        ['t'=>'usage','h'=>'En kibar rica biçimleri','b'=>"Könnten Sie mir bitte helfen? — En yaygın kibar rica\nWäre es möglich, den Termin zu verschieben? — Randevuyu ertelemek mümkün olur muydu?\nHätten Sie kurz Zeit? — Kısa bir vaktiniz var mıydı?\nIch hätte eine Frage. — Bir sorum olacaktı.\n\nBu dört cümle iş hayatında sürekli kullanılır.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich würde haben\" veya \"Ich würde sein\" demek. Bu fiillerde doğrudan hätte / wäre kullanılır.",'c'=>1],
                    ],
                    'vocab' => ['hätte','wäre','könnte','sollte','müsste'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'konjunktiv_ii_haette_waere','q'=>'"Bu çok nazik olurdu" nasıl denir?','a'=>'Das wäre sehr nett.','opts'=>['Das wäre sehr nett.','Das würde sein sehr nett.','Das hätte sehr nett.','Das wird sehr nett.'],'exp'=>'sein → wäre; würde kullanılmaz.','vg'=>'haette-waere'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'konjunktiv_ii_haette_waere','q'=>'Boşluğu doldur: "Wenn ich mehr Zeit ___, würde ich mehr lernen."','a'=>'hätte','exp'=>'haben → hätte.','vg'=>'haette-conditional'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'konjunktiv_ii_modal','q'=>'En kibar rica hangisidir?','a'=>'Könnten Sie mir bitte helfen?','opts'=>['Könnten Sie mir bitte helfen?','Können Sie mir helfen?','Helfen Sie mir.','Sie müssen mir helfen.'],'exp'=>'könnte (Konjunktiv II) en kibar biçimdir.','vg'=>'konj-polite'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'konjunktiv_ii_haette_waere','q'=>'Hatayı düzelt: "Ich würde eine Frage haben."','a'=>'Ich hätte eine Frage.','exp'=>'haben fiilinde würde kullanılmaz: hätte.','vg'=>'konj-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'unreal_conditions','q'=>'"Senin yerinde olsam amirle konuşurdum" cümlesini yaz.','a'=>'Wenn ich du wäre, würde ich mit dem Chef sprechen.','exp'=>'wenn + wäre (fiil sonda), ana cümlede würde + mastar.','vg'=>'konj-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'unreal_conditions','q'=>'"Wenn ich Deutsch könnte, hätte ich bessere Chancen." ne anlatır?','a'=>'Gerçekte Almanca bilmiyorum','opts'=>['Gerçekte Almanca bilmiyorum','Almanca biliyorum','Almanca öğreneceğim','Almanca bilmem gerekiyor'],'exp'=>'Konjunktiv II gerçek dışı bir varsayım bildirir.','vg'=>'konj-meaning'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'b1-m5-amac-zaman',
            'level' => 'B1',
            'title' => 'Amaç ve Zaman Cümleleri',
            'description' => 'um...zu, damit, bevor, nachdem, während. Cümleleri anlamlı biçimde bağlama.',
            'lessons' => [
                [
                    'slug' => 'b1-um-zu-damit',
                    'title' => 'um ... zu ve damit',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Amaç bildirmek ve doğru yapıyı seçmek.',
                    'summary' => 'Neden bir şey yaptığını açıklamanın iki yolu. Seçim özneye bağlıdır.',
                    'skills' => ['um_zu','damit'],
                    'prereq' => ['zu_infinitiv'=>85,'nebensatz_verb_final'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"İki cümlenin ÖZNESİ AYNI ise: um ... zu + Infinitiv\n  Ich lerne Deutsch, um in Deutschland zu arbeiten.\n  (ben öğreniyorum, ben çalışacağım → aynı özne)\n\nÖZNELER FARKLI ise: damit + yan cümle (fiil sonda)\n  Ich spreche langsam, damit alle mich verstehen.\n  (ben konuşuyorum, onlar anlıyor → farklı özne)\n\nAynı özne varsa damit de kullanılabilir ama um...zu daha doğaldır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"-mek için\" tek yapıdır ve özne değişse de değişmez:\n\"Çalışmak için Almanca öğreniyorum.\"\n\"Herkes anlasın diye yavaş konuşuyorum.\"\n\nTürkçede ikinci cümlede \"diye\" kullanırız — yani aslında bizde de bir ayrım var. Almanca bu ayrımı dilbilgisiyle zorunlu kılar."],
                        ['t'=>'example','h'=>'Örnek','b'=>'İki yapı yan yana:','de'=>'Ich mache Überstunden, um mehr Geld zu verdienen.\nIch erkläre es noch einmal, damit es alle verstehen.','tr'=>'Daha çok para kazanmak için fazla mesai yapıyorum.\nHerkes anlasın diye bir kez daha açıklıyorum.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Farklı özne varken um...zu kullanmak: \"Ich spreche langsam, um alle mich zu verstehen\" yanlıştır. Özne farklıysa damit kullanılır.",'c'=>1],
                    ],
                    'vocab' => ['um ... zu','damit','verdienen','erklären'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'um_zu','q'=>'"Almanya\'da çalışmak için Almanca öğreniyorum" nasıl denir?','a'=>'Ich lerne Deutsch, um in Deutschland zu arbeiten.','opts'=>['Ich lerne Deutsch, um in Deutschland zu arbeiten.','Ich lerne Deutsch, um in Deutschland arbeiten.','Ich lerne Deutsch, damit in Deutschland zu arbeiten.','Ich lerne Deutsch für in Deutschland arbeiten.'],'exp'=>'Aynı özne → um ... zu + Infinitiv sonda.','vg'=>'umzu-form'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'damit','q'=>'"Herkes anlasın diye yavaş konuşuyorum" nasıl denir?','a'=>'Ich spreche langsam, damit alle mich verstehen.','opts'=>['Ich spreche langsam, damit alle mich verstehen.','Ich spreche langsam, um alle mich zu verstehen.','Ich spreche langsam, damit verstehen alle mich.','Ich spreche langsam für alle verstehen.'],'exp'=>'Özneler farklı → damit; fiil sonda.','vg'=>'damit-form'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'um_zu','q'=>'um ... zu ne zaman kullanılır?','a'=>'İki cümlenin öznesi aynıysa','opts'=>['İki cümlenin öznesi aynıysa','İki cümlenin öznesi farklıysa','Her zaman','Sadece geçmiş zamanda'],'exp'=>'Özne aynıysa um...zu, farklıysa damit.','vg'=>'umzu-rule'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'um_zu','q'=>'Hatayı düzelt: "Ich mache Überstunden, um mehr Geld verdienen."','a'=>'Ich mache Überstunden, um mehr Geld zu verdienen.','exp'=>'um ... zu yapısında "zu" zorunludur.','vg'=>'umzu-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'damit','q'=>'"Anlaman için bir kez daha açıklıyorum" cümlesini damit ile yaz.','a'=>'Ich erkläre es noch einmal, damit du es verstehst.','exp'=>'Özneler farklı → damit; fiil sonda.','vg'=>'damit-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-zaman-baglaclari',
                    'title' => 'bevor, nachdem, während, seitdem, bis, sobald',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Olayları zaman içinde doğru sıralamak.',
                    'summary' => 'İş süreçlerini ve geçmişi anlatırken bu bağlaçlar gerekir.',
                    'skills' => ['temporal_bevor_nachdem','temporal_waehrend_seit','temporal_bis_sobald'],
                    'prereq' => ['nebensatz_verb_final'=>90,'perfekt'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Bağlaçlar ve anlamları','b'=>"bevor — -den önce\nnachdem — -den sonra\nwährend — -iken, sırasında\nseitdem — -den beri\nbis — -e kadar\nsobald — -er ermez\n\nHepsi yan cümle kurar: fiil sona gider."],
                        ['t'=>'rule','h'=>'nachdem ve zaman uyumu','b'=>"nachdem cümlesinde fiil, ana cümleden BİR ADIM ÖNCEKİ zamanda olur:\n\nAna cümle Präsens → nachdem cümlesi Perfekt\n  Nachdem ich gegessen habe, gehe ich zur Arbeit.\n\nAna cümle Präteritum → nachdem cümlesi Plusquamperfekt\n  Nachdem ich gegessen hatte, ging ich zur Arbeit.\n\nBu, olayların sırasını netleştirir."],
                        ['t'=>'example','h'=>'Örnek','b'=>'İş süreci anlatımı:','de'=>'Bevor Sie die Maschine benutzen, lesen Sie bitte die Anweisung.\nNachdem die Schicht zu Ende ist, wird die Maschine gereinigt.\nWährend ich arbeite, höre ich Radio.','tr'=>'Makineyi kullanmadan önce lütfen talimatı okuyun.\nVardiya bittikten sonra makine temizlenir.\nÇalışırken radyo dinliyorum.'],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede bu anlamlar ekle kurulur: \"-meden önce\", \"-dikten sonra\", \"-iken\". Almancada ayrı bağlaç kelimeleri kullanılır ve fiil sona gider.\n\nİyi haber: Türkçede de fiil sonda olduğu için yapı sana tanıdık gelir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"nachdem ile \"danach\" karıştırmak. nachdem yan cümle kurar (fiil sonda), danach ise zarftır (fiil hemen arkasından gelir): \"Danach gehe ich zur Arbeit.\"",'c'=>1],
                    ],
                    'vocab' => ['bevor','nachdem','während','seitdem','bis','sobald'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'temporal_bevor_nachdem','q'=>'"Makineyi kullanmadan önce talimatı okuyun" nasıl denir?','a'=>'Bevor Sie die Maschine benutzen, lesen Sie die Anweisung.','opts'=>['Bevor Sie die Maschine benutzen, lesen Sie die Anweisung.','Bevor Sie benutzen die Maschine, lesen Sie die Anweisung.','Vor Sie die Maschine benutzen, lesen Sie die Anweisung.','Bevor die Maschine Sie benutzen, lesen die Anweisung.'],'exp'=>'bevor yan cümle kurar; fiil sonda.','vg'=>'temp-bevor'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'temporal_bevor_nachdem','q'=>'"Nachdem ich gegessen ___, gehe ich zur Arbeit." Boşluğa hangisi gelir?','a'=>'habe','opts'=>['habe','bin','hatte','werde'],'exp'=>'Ana cümle Präsens ise nachdem cümlesi Perfekt olur.','vg'=>'temp-nachdem'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'temporal_waehrend_seit','q'=>'Boşluğu doldur: "___ ich hier arbeite, spreche ich besser Deutsch." (-den beri)','a'=>'Seitdem','exp'=>'seitdem = -den beri; yan cümle kurar.','vg'=>'temp-seitdem'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'temporal_bis_sobald','q'=>'Hatayı düzelt: "Sobald ich komme an, rufe ich an."','a'=>'Sobald ich ankomme, rufe ich an.','exp'=>'Yan cümlede ayrılabilir fiil birleşir ve sona gider.','vg'=>'temp-sobald'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'temporal_waehrend_seit','q'=>'"Çalışırken radyo dinliyorum" cümlesini während ile yaz.','a'=>'Während ich arbeite, höre ich Radio.','exp'=>'während yan cümle kurar; ana cümlede fiil hemen virgülden sonra.','vg'=>'temp-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-ohne-statt-zu',
                    'title' => 'ohne ... zu ve statt ... zu',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'Olumsuz eşlik ve alternatif bildirmek.',
                    'summary' => 'İki küçük yapı, anlatımını hemen B1 seviyesine taşır.',
                    'skills' => ['ohne_statt_zu'],
                    'prereq' => ['um_zu'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"ohne ... zu + Infinitiv = -meden\n  Er ging, ohne etwas zu sagen. — Hiçbir şey söylemeden gitti.\n\nstatt ... zu + Infinitiv = -mek yerine\n  Statt zu warten, rief er an. — Beklemek yerine telefon etti.\n\nHer iki yapıda da özne AYNI olmalıdır. Özneler farklıysa \"ohne dass\" / \"statt dass\" kullanılır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"-meden\" ve \"-mek yerine\" tek parçadır. Almancada iki parçalıdır ve \"zu\" araya girer. Ayrıca yapı cümlenin sonuna yerleşir."],
                        ['t'=>'usage','h'=>'İş yerinde','b'=>"Ohne den Chef zu fragen, kann ich das nicht entscheiden. — Amire sormadan buna karar veremem.\nStatt eine E-Mail zu schreiben, rufe ich lieber an. — E-posta yazmak yerine aramayı tercih ederim.",'c'=>1],
                    ],
                    'vocab' => ['ohne ... zu','statt ... zu','entscheiden','Entscheidung'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'ohne_statt_zu','q'=>'"Hiçbir şey söylemeden gitti" nasıl denir?','a'=>'Er ging, ohne etwas zu sagen.','opts'=>['Er ging, ohne etwas zu sagen.','Er ging, ohne etwas sagen.','Er ging ohne zu etwas sagen.','Er ging, ohne dass etwas sagen.'],'exp'=>'ohne ... zu + Infinitiv sonda.','vg'=>'ohnezu-form'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'ohne_statt_zu','q'=>'"Beklemek yerine telefon etti" nasıl denir?','a'=>'Statt zu warten, rief er an.','opts'=>['Statt zu warten, rief er an.','Statt warten, rief er an.','Statt zu warten, er rief an.','Statt er wartete, rief an.'],'exp'=>'statt ... zu + Infinitiv; ana cümlede fiil hemen virgülden sonra.','vg'=>'stattzu-form'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'ohne_statt_zu','q'=>'Hatayı düzelt: "Ohne den Chef fragen, kann ich nicht entscheiden."','a'=>'Ohne den Chef zu fragen, kann ich nicht entscheiden.','exp'=>'"zu" zorunludur.','vg'=>'ohnezu-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'ohne_statt_zu','q'=>'"E-posta yazmak yerine arıyorum" cümlesini yaz.','a'=>'Statt eine E-Mail zu schreiben, rufe ich an.','exp'=>'statt ... zu; ana cümlede V2.','vg'=>'stattzu-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'ohne_statt_zu','q'=>'ohne ... zu yapısında özneler farklıysa ne kullanılır?','a'=>'ohne dass','opts'=>['ohne dass','ohne zu','ohne damit','ohne weil'],'exp'=>'Özne farklıysa "ohne dass" + yan cümle kullanılır.','vg'=>'ohnezu-rule'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'b1-m6-cumle-yapisi',
            'level' => 'B1',
            'title' => 'İleri Cümle Yapısı',
            'description' => 'TeKaMoLo, fiil + edat kalıpları, da-/wo- bileşikleri, n-Deklination ve dolaylı sorular.',
            'lessons' => [
                [
                    'slug' => 'b1-tekamolo',
                    'title' => 'TeKaMoLo: Cümle İçi Sıralama',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Cümle ortasındaki öğeleri doğru sırayla dizmek.',
                    'summary' => 'Cümlen dilbilgisel olarak doğru olsa bile sıralama yanlışsa doğal duyulmaz.',
                    'skills' => ['tekamolo'],
                    'prereq' => ['verb_second'=>90,'dativ_prepositions'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Cümle ortasındaki öğelerin standart sırası:\n\nTE (Temporal) — ne zaman?\nKA (Kausal) — neden?\nMO (Modal) — nasıl?\nLO (Lokal) — nerede/nereye?\n\nIch fahre morgen wegen der Besprechung mit dem Zug nach Berlin.\n        (TE)      (KA)                (MO)        (LO)"],
                        ['t'=>'rule','h'=>'Nesne sıralaması','b'=>"Dativ nesne genellikle Akkusativ nesneden ÖNCE gelir (ikisi de isimse):\n  Ich gebe dem Chef das Formular.\n\nZamir varsa zamir öne geçer:\n  Ich gebe ihm das Formular.\n  Ich gebe es dem Chef.\n  Ich gebe es ihm."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede sıralama esnektir ve vurguya göre değişir: \"Yarın trenle Berlin'e gidiyorum\" ya da \"Berlin'e yarın trenle gidiyorum\" — ikisi de doğaldır.\n\nAlmancada da esneklik vardır ama VARSAYILAN sıra TeKaMoLo'dur. Bu sıradan sapmak vurgu yaratır; farkında olmadan sapmak ise cümleyi tuhaf gösterir."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"TeKaMoLo kelimesini bir bütün olarak ezberle: Te-Ka-Mo-Lo. Cümle kurarken içinden bu sırayı say. Bu bir ezber yöntemidir, katı bir kural değildir; vurgu için sıra değişebilir.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Yer bildirimini zamandan önce koymak: \"Ich fahre nach Berlin morgen\" doğal değildir. Doğrusu \"Ich fahre morgen nach Berlin\".",'c'=>1],
                    ],
                    'vocab' => ['während','wegen','Besprechung','Zug'],
                    'exercises' => [
                        ['type'=>'word_order','mode'=>'production','skill'=>'tekamolo','q'=>'Kelimeleri TeKaMoLo sırasına göre diz: "nach Berlin / ich / morgen / fahre / mit dem Zug"','a'=>'Ich fahre morgen mit dem Zug nach Berlin.','exp'=>'Zaman (morgen) → biçim (mit dem Zug) → yer (nach Berlin).','vg'=>'tekamolo-order'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'tekamolo','q'=>'TeKaMoLo sırasında "Mo" neyi ifade eder?','a'=>'Nasıl (biçim)','opts'=>['Nasıl (biçim)','Ne zaman','Neden','Nerede'],'exp'=>'Modal = nasıl, hangi araçla.','vg'=>'tekamolo-meaning'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'tekamolo','q'=>'Hatayı düzelt: "Ich fahre nach Köln morgen mit dem Auto."','a'=>'Ich fahre morgen mit dem Auto nach Köln.','exp'=>'Zaman önce, yer sonra gelir.','vg'=>'tekamolo-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'tekamolo','q'=>'"Ich gebe ___ ___." İkisi de zamirse doğru sıra hangisidir?','a'=>'es ihm','opts'=>['es ihm','ihm es','ihn ihm','ihm ihn'],'exp'=>'İki zamirde Akkusativ önce gelir.','vg'=>'tekamolo-pronoun'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'tekamolo','q'=>'Kelimeleri sıraya diz: "das Formular / dem Chef / ich / gebe"','a'=>'Ich gebe dem Chef das Formular.','exp'=>'İkisi de isimse Dativ önce gelir.','vg'=>'tekamolo-objects'],
                    ],
                ],
                [
                    'slug' => 'b1-fiil-edat',
                    'title' => 'Fiil + Edat Kalıpları',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Fiillerin sabit edatlarını ve bu edatların istediği hali ezberlemek.',
                    'summary' => 'Bu kalıplar tahmin edilemez; liste halinde ezberlenir. B1\'in en çok hata yapılan alanı.',
                    'skills' => ['verb_preposition'],
                    'prereq' => ['akk_dat_distinction'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'En sık kalıplar','b'=>"warten auf + Akkusativ — beklemek\ndenken an + Akkusativ — düşünmek\nsich freuen auf + Akkusativ — dört gözle beklemek\nsich freuen über + Akkusativ — sevinmek (olmuş bir şeye)\nsich interessieren für + Akkusativ — ilgilenmek\nsich kümmern um + Akkusativ — ilgilenmek, bakmak\nsprechen über + Akkusativ — hakkında konuşmak\nsich beschweren über + Akkusativ — şikayet etmek\nsich bedanken für + Akkusativ — teşekkür etmek\nachten auf + Akkusativ — dikkat etmek\n\nteilnehmen an + Dativ — katılmak\nabhängen von + Dativ — bağlı olmak\narbeiten an + Dativ — üzerinde çalışmak\nsprechen mit + Dativ — biriyle konuşmak\nsich treffen mit + Dativ — buluşmak"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede fiiller de hal ister (\"bir şey-İ beklemek\", \"bir şey-E dikkat etmek\") ama Almanca kalıplar Türkçe karşılıklarıyla ÖRTÜŞMEZ:\n\nTürkçe: otobüs-Ü beklemek\nAlmanca: warten AUF den Bus (auf + Akkusativ)\n\nBu yüzden fiili doğrudan çevirmek hataya yol açar. Kalıbı bir bütün olarak ezberlemek gerekir."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Fiili asla yalnız yazma. Defterine \"warten\" değil \"warten auf + Akk\" yaz ve yanına bir örnek cümle koy. Kalıbı cümleyle birlikte ezberlemek, kuru listeden çok daha kalıcıdır.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Türkçe mantığıyla edat seçmek: \"Ich warte den Bus\" veya \"Ich warte für den Bus\" yanlıştır. Doğrusu \"Ich warte auf den Bus\".",'c'=>1],
                    ],
                    'vocab' => ['warten','denken','sich interessieren','sich kümmern','teilnehmen','abhängen','achten','sich beschweren'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'verb_preposition','q'=>'Boşluğu doldur: "Ich warte ___ den Bus."','a'=>'auf','exp'=>'warten auf + Akkusativ.','vg'=>'vpre-warten'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'verb_preposition','q'=>'"Toplantıya katılıyorum" nasıl denir?','a'=>'Ich nehme an der Besprechung teil.','opts'=>['Ich nehme an der Besprechung teil.','Ich nehme an die Besprechung teil.','Ich nehme in der Besprechung teil.','Ich nehme zu der Besprechung teil.'],'exp'=>'teilnehmen an + Dativ.','vg'=>'vpre-teilnehmen'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'verb_preposition','q'=>'Boşluğu doldur: "Das hängt ___ der Situation ab."','a'=>'von','exp'=>'abhängen von + Dativ.','vg'=>'vpre-abhaengen'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'verb_preposition','q'=>'"Gürültüden şikayet etmek istiyorum" nasıl denir? (der Lärm)','a'=>'Ich möchte mich über den Lärm beschweren.','opts'=>['Ich möchte mich über den Lärm beschweren.','Ich möchte mich von dem Lärm beschweren.','Ich möchte mich für den Lärm beschweren.','Ich möchte über den Lärm beschweren.'],'exp'=>'sich beschweren über + Akkusativ; dönüşlü zamir zorunludur.','vg'=>'vpre-beschweren'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'verb_preposition','q'=>'Hatayı düzelt: "Ich interessiere mich in Technik."','a'=>'Ich interessiere mich für Technik.','exp'=>'sich interessieren für + Akkusativ.','vg'=>'vpre-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'verb_preposition','q'=>'"Güvenliğe dikkat edin" cümlesini yaz. (die Sicherheit, resmi emir)','a'=>'Achten Sie auf die Sicherheit.','exp'=>'achten auf + Akkusativ.','vg'=>'vpre-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-da-wo-bilesikleri',
                    'title' => 'da-/wo- Bileşikleri',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Edat + zamir yerine bileşik biçimleri kullanmak.',
                    'summary' => 'Bu yapılar olmadan doğal Almanca konuşmak mümkün değildir.',
                    'skills' => ['pronominal_adverbs','indirect_questions'],
                    'prereq' => ['verb_preposition'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Edatın nesnesi bir NESNE veya DURUM ise (kişi değilse), edat + zamir yerine bileşik kullanılır:\n\nda + edat: darauf, darüber, davon, damit, dafür, daran\nwo + edat: worauf, worüber, wovon, womit, wofür, woran\n\nEdat ünlüyle başlıyorsa araya -r- girer: da-r-auf, wo-r-über."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Kişi mi nesne mi?','de'=>'Ich warte auf den Bus. → Ich warte darauf.\nIch warte auf meinen Chef. → Ich warte auf ihn.','tr'=>'Nesne için darauf, kişi için "auf ihn" kullanılır. Bu ayrım zorunludur.'],
                        ['t'=>'rule','h'=>'Soru biçimi','b'=>"Nesne soruluyorsa wo- bileşiği:\n  Worauf wartest du? — Neyi bekliyorsun?\n  Worüber sprecht ihr? — Ne hakkında konuşuyorsunuz?\n\nKişi soruluyorsa edat + soru zamiri:\n  Auf wen wartest du? — Kimi bekliyorsun?\n  Mit wem sprichst du? — Kiminle konuşuyorsun?"],
                        ['t'=>'explanation','h'=>'Dolaylı sorular','b'=>"Bir soruyu cümle içine gömerken soru kelimesi bağlaç olur ve fiil sona gider:\n\nWo ist das Büro? → Können Sie mir sagen, wo das Büro ist?\nWann beginnt die Schicht? → Ich weiß nicht, wann die Schicht beginnt.\n\nSoru kelimesi yoksa \"ob\" (acaba, -ip -mediği) kullanılır:\nKommt er morgen? → Ich weiß nicht, ob er morgen kommt."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"onu bekliyorum\" derken nesne ile kişi arasında dilbilgisel fark yoktur. Almancada bu ayrım zorunludur ve yanlış kullanmak hemen fark edilir."],
                    ],
                    'vocab' => ['darauf','darüber','davon','damit','womit','worauf','worüber'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'pronominal_adverbs','q'=>'"Ich warte auf den Bus." cümlesinde "den Bus" yerine ne gelir?','a'=>'darauf','opts'=>['darauf','auf ihn','darüber','davon'],'exp'=>'Nesne olduğu için darauf; kişi olsaydı "auf ihn" olurdu.','vg'=>'dawo-object'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'pronominal_adverbs','q'=>'"Ich warte auf meinen Chef." cümlesinde "meinen Chef" yerine ne gelir?','a'=>'auf ihn','opts'=>['auf ihn','darauf','worauf','davon'],'exp'=>'Kişi olduğu için edat + zamir kullanılır.','vg'=>'dawo-person'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'pronominal_adverbs','q'=>'"Neyi bekliyorsun?" nasıl sorulur?','a'=>'Worauf wartest du?','opts'=>['Worauf wartest du?','Auf was wartest du?','Was wartest du?','Wofür wartest du?'],'exp'=>'warten auf + nesne sorusu → worauf.','vg'=>'dawo-question'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'indirect_questions','q'=>'Bu soruyu dolaylı hale getir: "Wo ist das Büro?" (Können Sie mir sagen, ...)','a'=>'Können Sie mir sagen, wo das Büro ist?','exp'=>'Dolaylı soruda fiil sona gider.','vg'=>'indirect-q'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'indirect_questions','q'=>'Boşluğu doldur: "Ich weiß nicht, ___ er morgen kommt." (gelip gelmeyeceğini)','a'=>'ob','exp'=>'Soru kelimesi yoksa "ob" kullanılır.','vg'=>'indirect-ob'],
                    ],
                ],
                [
                    'slug' => 'b1-n-deklination',
                    'title' => 'n-Deklination',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'Nominativ dışında -n/-en alan eril isimleri tanımak.',
                    'summary' => 'Küçük bir grup ama çok sık kullanılan isimler. Hata yapılırsa hemen dikkat çeker.',
                    'skills' => ['n_deklination'],
                    'prereq' => ['dativ'=>90,'akkusativ'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Bazı ERİL isimler Nominativ dışındaki bütün hallerde -n veya -en alır:\n\nNominativ: der Kollege\nAkkusativ: den Kollegen\nDativ: dem Kollegen\nGenitiv: des Kollegen\n\nÇoğulda da -n/-en: die Kollegen"],
                        ['t'=>'table','h'=>'Bu gruba giren isimler','b'=>"-e ile biten eril kişi isimleri:\nder Kollege, der Kunde, der Junge, der Experte, der Neffe\n\nYabancı kökenli, sonu vurgulu:\nder Student, der Praktikant, der Polizist, der Journalist, der Präsident\n\nBazı tekil isimler:\nder Mensch, der Nachbar, der Herr, der Name (der Name özel: des Namens)"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede isimler hale göre ek alır ama bu bütün isimler için geçerlidir. Almancada normalde isim DEĞİŞMEZ, sadece artikel değişir. n-Deklination bu kuralın istisnasıdır ve bu yüzden şaşırtıcıdır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich sehe den Kollege\" demek. Doğrusu \"Ich sehe den Kollegen\"dir. Bu hata Almanca konuşan birinin kulağına hemen çarpar.",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Bu grubun çoğu KİŞİ ismidir ve -e ile biter. \"Kişi + -e ile biten eril isim\" gördüğünde -n eklemeyi düşün. Bu bir kısayoldur; tam liste yukarıdadır.",'c'=>1],
                    ],
                    'vocab' => ['Mensch','Kunde','Praktikant','Experte','Kollege','Nachbar'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'n_deklination','q'=>'"Ich sehe den ___." (der Kollege) Boşluğa hangisi gelir?','a'=>'Kollegen','opts'=>['Kollegen','Kollege','Kolleges','Kollegem'],'exp'=>'n-Deklination: Akkusativ\'de -n eklenir.','vg'=>'ndekl-akk'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'n_deklination','q'=>'"Wir helfen dem ___." (der Kunde) Boşluğa hangisi gelir?','a'=>'Kunden','opts'=>['Kunden','Kunde','Kundes','Kundem'],'exp'=>'Dativ\'de de -n eklenir.','vg'=>'ndekl-dat'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'n_deklination','q'=>'Hangi isim n-Deklination grubundadır?','a'=>'der Student','opts'=>['der Student','der Tisch','das Auto','die Frau'],'exp'=>'Yabancı kökenli, sonu vurgulu eril isimler bu gruptadır: den Studenten.','vg'=>'ndekl-recognize'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'n_deklination','q'=>'Hatayı düzelt: "Ich kenne diesen Mensch nicht."','a'=>'Ich kenne diesen Menschen nicht.','exp'=>'der Mensch n-Deklination grubundadır.','vg'=>'ndekl-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'n_deklination','q'=>'"Bir uzmana sorun" cümlesini yaz. (der Experte, resmi emir)','a'=>'Fragen Sie einen Experten.','exp'=>'fragen + Akkusativ; Experte → Experten.','vg'=>'ndekl-produce'],
                    ],
                ],
            ],
        ],
    ];
}

function almancapro_curriculum_b1_part3(): array
{
    return [
        [
            'slug' => 'b1-m7-is-dunyasi',
            'level' => 'B1',
            'title' => 'İş Dünyası B1',
            'description' => 'Toplantı dili, resmi yazışma, sorun anlatma, iş güvenliği ve sözleşme kelimeleri.',
            'lessons' => [
                [
                    'slug' => 'b1-toplanti',
                    'title' => 'Toplantı Dili',
                    'type' => 'workplace',
                    'minutes' => 16,
                    'objective' => 'Toplantıda söz almak, görüş bildirmek ve anlamadığını söylemek.',
                    'summary' => 'Toplantıda susan kişi, bilgisiz sanılır. Bu kalıplar konuşmanı sağlar.',
                    'skills' => ['meetings_b1','opinions_b1'],
                    'prereq' => ['konjunktiv_ii_wuerde'=>85,'subordinate_dass'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Söz alma','b'=>"Darf ich kurz etwas sagen? — Kısaca bir şey söyleyebilir miyim?\nIch hätte dazu eine Frage. — Bu konuda bir sorum olacak.\nDarf ich kurz nachfragen? — Kısaca sorabilir miyim?\nEntschuldigung, ich möchte etwas ergänzen. — Bir şey eklemek istiyorum."],
                        ['t'=>'rule','h'=>'Görüş bildirme','b'=>"Meiner Meinung nach ... — Bence ...\nIch bin der Meinung, dass ... — ... görüşündeyim.\nIch denke, dass ... — ... diye düşünüyorum.\nAus meiner Sicht ... — Benim açımdan ...\n\nKatılma:\nDa stimme ich Ihnen zu. — Bu konuda size katılıyorum.\nDas sehe ich genauso. — Ben de aynı şekilde görüyorum.\n\nKatılmama (kibar):\nIch sehe das etwas anders. — Ben biraz farklı görüyorum.\nDa bin ich nicht ganz Ihrer Meinung. — Bu konuda tam olarak aynı fikirde değilim."],
                        ['t'=>'usage','h'=>'Anlamadığında','b'=>"Könnten Sie das bitte noch einmal erklären? — Bunu tekrar açıklayabilir misiniz?\nHabe ich das richtig verstanden, dass ...? — ... doğru anladım mı?\nWas bedeutet das konkret für uns? — Bu bizim için somut olarak ne demek?\n\nÜçüncü cümle özellikle değerlidir: hem anlamadığını belli etmeden netlik ister hem profesyonel durur.",'c'=>1],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Alman toplantı kültüründe karşı çıkmak kişisel algılanmaz; fikir tartışması normaldir. Ancak karşı çıkarken kibar kalıp kullanmak beklenir. \"Nein, das ist falsch\" yerine \"Ich sehe das etwas anders\" demek profesyonel farkı yaratır."],
                    ],
                    'vocab' => ['Besprechung','Vorschlag','Entscheidung','Ergebnis','meiner Meinung nach','Ich stimme zu','Ich sehe das anders','Problem','Lösung'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'meetings_b1','q'=>'Toplantıda söz almak istiyorsun. En profesyonel biçim hangisi?','a'=>'Darf ich kurz etwas sagen?','opts'=>['Darf ich kurz etwas sagen?','Ich will sprechen.','Hallo, ich!','Sie müssen mich hören.'],'exp'=>'Modal soru + kibar ton.','vg'=>'meet-turn'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'opinions_b1','q'=>'Bir fikre kibarca karşı çıkmak istiyorsun. Hangisi en uygun?','a'=>'Ich sehe das etwas anders.','opts'=>['Ich sehe das etwas anders.','Das ist falsch.','Nein!','Sie haben keine Ahnung.'],'exp'=>'Almanca iş dilinde karşı çıkış kibar kalıpla yapılır.','vg'=>'meet-disagree'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'opinions_b1','q'=>'"Bence bu çok pahalı" cümlesini yaz.','a'=>'Meiner Meinung nach ist das zu teuer.','alt'=>['Ich bin der Meinung, dass das zu teuer ist.'],'exp'=>'"Meiner Meinung nach" birinci pozisyonda → fiil ikinci sırada.','vg'=>'meet-opinion'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'meetings_b1','q'=>'Bir kararın sonuçlarını netleştirmek istiyorsun. Hangi soru en işlevseldir?','a'=>'Was bedeutet das konkret für uns?','opts'=>['Was bedeutet das konkret für uns?','Ich verstehe nicht.','Warum?','Ist das wichtig?'],'exp'=>'Somut sonuç sormak hem netlik sağlar hem profesyonel durur.','vg'=>'meet-clarify'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'opinions_b1','q'=>'Hatayı düzelt: "Ich bin der Meinung, dass wir brauchen mehr Zeit."','a'=>'Ich bin der Meinung, dass wir mehr Zeit brauchen.','exp'=>'dass yan cümlesinde fiil sona gider.','vg'=>'meet-correct'],
                    ],
                ],
                [
                    'slug' => 'b1-resmi-yazisma',
                    'title' => 'Resmi Yazışma ve Şikayet',
                    'type' => 'workplace',
                    'minutes' => 16,
                    'objective' => 'Resmi bir dilekçe veya şikayet mektubu yazmak.',
                    'summary' => 'Kurumlarla yazışma Almanya\'da yazılı yapılır ve belli bir kalıbı vardır.',
                    'skills' => ['formal_writing_b1','complaints_b1'],
                    'prereq' => ['workplace_email'=>85,'passive_present'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Resmi mektup yapısı','b'=>"1. Betreff (konu)\n2. Sehr geehrte Damen und Herren,\n3. Giriş: neden yazıyorsun\n   Ich schreibe Ihnen bezüglich ...\n   Hiermit möchte ich Sie darüber informieren, dass ...\n4. Ana kısım: olayı tarafsız anlat\n5. Talep: ne istiyorsun\n   Ich bitte Sie, ... zu prüfen.\n   Ich möchte Sie bitten, ...\n6. Kapanış:\n   Für Rückfragen stehe ich Ihnen gerne zur Verfügung.\n   Mit freundlichen Grüßen"],
                        ['t'=>'rule','h'=>'Şikayet kalıpları','b'=>"Leider muss ich Ihnen mitteilen, dass ... — Maalesef size bildirmem gerekiyor ki ...\nEs gibt ein Problem mit ... — ... ile ilgili bir sorun var.\nDas Gerät funktioniert seit dem 3. Mai nicht mehr. — Cihaz 3 Mayıs'tan beri çalışmıyor.\nIch bitte Sie um eine schnelle Lösung. — Hızlı bir çözüm rica ediyorum.\nIch erwarte Ihre Antwort bis zum ... — Cevabınızı ...'e kadar bekliyorum."],
                        ['t'=>'explanation','h'=>'Ton kuralı','b'=>"Alman resmi yazışmasında ton SAKİN ve OLGUSAL olur. Duygusal ifadeler, ünlem işaretleri ve suçlayıcı dil profesyonel bulunmaz.\n\nEtkisiz: Das ist eine Frechheit!\nEtkili: Leider entspricht das nicht der Vereinbarung. Ich bitte Sie um eine Klärung.\n\nOlgusal ve kibar bir mektup, öfkeli bir mektuptan daha hızlı sonuç alır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçe resmi yazışmada uzun nezaket cümleleri yaygındır. Almanca resmi yazışma daha kısa, daha doğrudan ve daha yapısaldır: konu, olay, talep, kapanış. Fazla süsleme beklenmez."],
                    ],
                    'vocab' => ['Bescheid','Frist','bestätigen','beantragen','Problem','Lösung','Verantwortung','ausführlich'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'formal_writing_b1','q'=>'Alıcının adını bilmiyorsun. Doğru selamlama hangisi?','a'=>'Sehr geehrte Damen und Herren,','opts'=>['Sehr geehrte Damen und Herren,','Hallo,','Liebe Firma,','Sehr geehrter Herr,'],'exp'=>'İsim bilinmiyorsa standart biçim budur.','vg'=>'formal-salutation'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'complaints_b1','q'=>'Şikayet mektubunda en etkili ton hangisidir?','a'=>'Sakin, olgusal ve net bir talep içeren','opts'=>['Sakin, olgusal ve net bir talep içeren','Öfkeli ve ünlemli','Çok uzun ve süslü','Belirsiz ve dolaylı'],'exp'=>'Alman resmi yazışmasında olgusal ton daha hızlı sonuç alır.','vg'=>'formal-tone'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'complaints_b1','q'=>'"Hızlı bir çözüm rica ediyorum" cümlesini yaz.','a'=>'Ich bitte Sie um eine schnelle Lösung.','exp'=>'bitten um + Akkusativ.','vg'=>'formal-request'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'formal_writing_b1','q'=>'"Sorularınız için memnuniyetle hazırım" nasıl denir?','a'=>'Für Rückfragen stehe ich Ihnen gerne zur Verfügung.','opts'=>['Für Rückfragen stehe ich Ihnen gerne zur Verfügung.','Ich bin für Fragen da.','Fragen Sie mich.','Ich habe Zeit für Fragen.'],'exp'=>'Standart resmi kapanış kalıbıdır.','vg'=>'formal-closing'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'formal_writing_b1','q'=>'Hatayı düzelt: "Hiermit möchte ich Sie informieren, dass das Gerät funktioniert nicht."','a'=>'Hiermit möchte ich Sie informieren, dass das Gerät nicht funktioniert.','exp'=>'dass yan cümlesinde fiil sona gider; nicht fiilden önce gelir.','vg'=>'formal-correct'],
                    ],
                ],
                [
                    'slug' => 'b1-is-guvenligi',
                    'title' => 'İş Güvenliği ve Sözleşme Kelimeleri',
                    'type' => 'workplace',
                    'minutes' => 16,
                    'objective' => 'Güvenlik talimatlarını anlamak ve sözleşme kelimelerini tanımak.',
                    'summary' => 'Bu ders dil öğretir. Hukuki durumun için sözleşmene ve yetkili bir danışmana bak.',
                    'skills' => ['workplace_safety_b1','contract_vocabulary_b1'],
                    'prereq' => ['passive_present'=>85,'imperative_basic'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Güvenlik talimatları','b'=>"Talimatlar genellikle edilgen veya emir kipiyle yazılır:\n\nSchutzhelm tragen! — Kask takın!\nHier darf nicht geraucht werden. — Burada sigara içilemez.\nDie Maschine muss vor der Reinigung ausgeschaltet werden. — Makine temizlikten önce kapatılmalıdır.\nBei Gefahr sofort den Notausschalter betätigen. — Tehlike durumunda acil durdurmaya basın.\n\nAnahtar kelimeler:\ndie Sicherheit — güvenlik\ndie Gefahr — tehlike\nder Unfall — kaza\nder Schutzhelm — kask\ndie Schutzbrille — koruyucu gözlük\ndie Sicherheitsschuhe — iş ayakkabısı\nder Notausgang — acil çıkış\nverboten — yasak\nvorgeschrieben — zorunlu"],
                        ['t'=>'rule','h'=>'Sözleşme kelimeleri','b'=>"der Arbeitsvertrag — iş sözleşmesi\ndie Probezeit — deneme süresi\ndie Kündigungsfrist — fesih ihbar süresi\ndie Arbeitszeit — çalışma süresi\ndie Überstunden — fazla mesai\nder Urlaubsanspruch — izin hakkı\ndas Gehalt / der Lohn — maaş / ücret\nbrutto / netto — brüt / net\ndie Lohnabrechnung — bordro\nder Tarifvertrag — toplu iş sözleşmesi"],
                        ['t'=>'explanation','h'=>'Önemli uyarı','b'=>"Bu bir DİL dersidir. Bir sözleşme maddesini anlamadıysan tahmin etme:\n\nWas bedeutet dieser Punkt genau? — Bu madde tam olarak ne demek?\nKönnen Sie mir das bitte erklären? — Bunu açıklayabilir misiniz?\nIch möchte den Vertrag zuerst in Ruhe lesen. — Sözleşmeyi önce sakin sakin okumak istiyorum.\n\nSon cümle özellikle değerlidir: bir sözleşmeyi hemen imzalamak zorunda değilsin. Hukuki sorularını yetkili bir danışmana, sendikaya veya uzman bir avukata sor. AlmancaPro hukuki tavsiye vermez."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Sie müssen keinen Helm tragen\" ile \"Sie dürfen keinen Helm tragen\" ifadelerini karıştırmak. İlki \"kask takmanız gerekmiyor\", ikincisi \"kask takmanız yasak\" demektir. İş güvenliğinde bu fark hayati olabilir.",'c'=>1],
                    ],
                    'vocab' => ['Sicherheit','Anweisung','Arbeitsvertrag','Probezeit','Kündigungsfrist','Überstunden','Lohnabrechnung','brutto','netto','Betriebsrat','Arbeitsunfähigkeitsbescheinigung'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'workplace_safety_b1','q'=>'"Hier darf nicht geraucht werden." ne anlama gelir?','a'=>'Burada sigara içmek yasaktır','opts'=>['Burada sigara içmek yasaktır','Burada sigara içmek gerekmiyor','Burada sigara içilebilir','Burada sigara içmek zor'],'exp'=>'nicht dürfen = yasak; edilgen yapı talimat bildirir.','vg'=>'safety-verbot'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'workplace_safety_b1','q'=>'"Sie müssen keinen Helm tragen." ne anlama gelir?','a'=>'Kask takmanız gerekmiyor','opts'=>['Kask takmanız gerekmiyor','Kask takmanız yasak','Kask takmalısınız','Kask yok'],'exp'=>'müssen + nicht/kein = gereklilik yok, yasak değil.','vg'=>'safety-muessen'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'contract_vocabulary_b1','q'=>'"Probezeit" ne demektir?','a'=>'Deneme süresi','opts'=>['Deneme süresi','Fesih süresi','İzin süresi','Mola süresi'],'exp'=>'die Probezeit = iş sözleşmesindeki deneme süresi.','vg'=>'contract-vocab'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'contract_vocabulary_b1','q'=>'"Sözleşmeyi önce sakin sakin okumak istiyorum" cümlesini yaz.','a'=>'Ich möchte den Vertrag zuerst in Ruhe lesen.','exp'=>'möchten + mastar sonda; der Vertrag → den Vertrag.','vg'=>'contract-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'contract_vocabulary_b1','q'=>'Sözleşmede anlamadığın bir madde var. En doğru davranış nedir?','a'=>'Açıklama istemek ve gerekirse yetkili bir danışmana sormak','opts'=>['Açıklama istemek ve gerekirse yetkili bir danışmana sormak','Hemen imzalamak','Boş bırakmak','Tahmin etmek'],'exp'=>'Anlamadan imzalamak risklidir. AlmancaPro dil öğretir, hukuki tavsiye vermez.','vg'=>'contract-safety'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'b1-m8-beceriler',
            'level' => 'B1',
            'title' => 'B1 Becerileri ve Değerlendirme',
            'description' => 'Okuma, yazma, konuşma becerileri ve kapsamlı B1 değerlendirmesi.',
            'lessons' => [
                [
                    'slug' => 'b1-okuma',
                    'title' => 'B1 Okuma Anlama',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Gerçek metinleri (ilan, e-posta, talimat) anlamak ve bilgi çıkarmak.',
                    'summary' => 'B1 okuma, her kelimeyi anlamak değil, gerekli bilgiyi bulmaktır.',
                    'skills' => ['b1_reading'],
                    'prereq' => ['relative_clause_basics'=>85,'passive_present'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Okuma stratejisi','b'=>"B1 seviyesinde her kelimeyi anlamak GEREKMEZ. Üç adım:\n\n1. Önce başlığı ve yapıyı tara: metin ne hakkında?\n2. Aradığın bilgiyi ara (tarih, tutar, isim, talep)\n3. Bilinmeyen kelimeyi bağlamdan tahmin et; her kelimeyi sözlükten aramak okumayı öldürür\n\nBileşik kelimeleri parçala:\nArbeitsunfähigkeitsbescheinigung = Arbeit + Unfähigkeit + Bescheinigung\n= iş + yapamama + belge = iş göremezlik belgesi"],
                        ['t'=>'example','h'=>'Örnek metin','b'=>'Bir iş yeri duyurusu:','de'=>"Sehr geehrte Mitarbeiterinnen und Mitarbeiter,\n\nab dem 1. Juni wird der Schichtplan geändert. Die Frühschicht beginnt dann um 6:00 Uhr statt um 6:30 Uhr. Die Spätschicht endet unverändert um 22:00 Uhr.\n\nWer Fragen hat, kann sich bis zum 25. Mai an die Personalabteilung wenden.\n\nMit freundlichen Grüßen\nDie Geschäftsleitung",'tr'=>'1 Haziran\'dan itibaren vardiya planı değişiyor. Sabah vardiyası 6:30 yerine 6:00\'da başlıyor. Akşam vardiyası 22:00\'da bitmeye devam ediyor. Soruları olanlar 25 Mayıs\'a kadar insan kaynaklarına başvurabilir.'],
                        ['t'=>'rule','h'=>'Metinde aranacak bilgi türleri','b'=>"Tarih: ab dem 1. Juni, bis zum 25. Mai\nSaat: um 6:00 Uhr statt um 6:30 Uhr\nDeğişiklik: wird geändert (edilgen)\nDeğişmeyen: unverändert\nKime başvurulacak: an die Personalabteilung wenden"],
                        ['t'=>'usage','h'=>'İpucu kelimeler','b'=>"ab — -den itibaren\nbis zum — -e kadar\nstatt — yerine\nunverändert — değişmeden\nzusätzlich — ek olarak\nbitte beachten Sie — lütfen dikkat edin\nerforderlich — gerekli\nspätestens — en geç",'c'=>1],
                    ],
                    'vocab' => ['Frist','Bescheid','deutlich','ausführlich','Zusammenhang','Auswirkung'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_reading','q'=>'Duyuruya göre sabah vardiyası 1 Haziran\'dan sonra saat kaçta başlıyor?','a'=>'6:00','opts'=>['6:00','6:30','22:00','25:00'],'ctx'=>'Ab dem 1. Juni wird der Schichtplan geändert. Die Frühschicht beginnt dann um 6:00 Uhr statt um 6:30 Uhr.','exp'=>'"statt um 6:30" = 6:30 yerine. Yeni saat 6:00\'dır.','vg'=>'read-detail'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_reading','q'=>'"bis zum 25. Mai" ne anlama gelir?','a'=>'25 Mayıs\'a kadar','opts'=>['25 Mayıs\'a kadar','25 Mayıs\'tan itibaren','25 Mayıs\'ta','25 Mayıs\'tan sonra'],'exp'=>'bis zum = -e kadar (son tarih).','vg'=>'read-time'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_reading','q'=>'"Arbeitsunfähigkeitsbescheinigung" kelimesini parçalarsan ne çıkar?','a'=>'İş + yapamama + belge','opts'=>['İş + yapamama + belge','İş + izin + belge','İş + kaza + rapor','İş + sözleşme + belge'],'exp'=>'Arbeit + Unfähigkeit + Bescheinigung. Bileşik kelimeleri parçalamak B1 okumanın anahtarıdır.','vg'=>'read-compound'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'b1_reading','q'=>'"unverändert" ne demektir?','a'=>'Değişmeden','opts'=>['Değişmeden','Değişerek','Belirsiz','Zorunlu'],'exp'=>'un- olumsuzluk öneki + verändert (değiştirilmiş) = değişmeden.','vg'=>'read-vocab'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_reading','q'=>'B1 okumada en doğru strateji hangisidir?','a'=>'Aradığın bilgiyi tarayarak bulmak','opts'=>['Aradığın bilgiyi tarayarak bulmak','Her kelimeyi sözlükten aramak','Metni ezberlemek','Sadece başlığı okumak'],'exp'=>'B1 okuma, bilgiyi bulma becerisidir; her kelimeyi anlamak gerekmez.','vg'=>'read-strategy'],
                    ],
                ],
                [
                    'slug' => 'b1-yazma',
                    'title' => 'B1 Yazma',
                    'type' => 'grammar',
                    'minutes' => 18,
                    'objective' => 'Yapılandırılmış, bağlaçlarla örülmüş bir metin üretmek.',
                    'summary' => 'B1 yazmada beklenen: net yapı, doğru bağlaçlar ve tutarlı zaman kullanımı.',
                    'skills' => ['b1_writing'],
                    'prereq' => ['formal_writing_b1'=>85,'temporal_bevor_nachdem'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Metin yapısı','b'=>"Her B1 metni üç bölümlüdür:\n\n1. GİRİŞ: neden yazıyorsun (1-2 cümle)\n2. GELİŞME: olay, gerekçe, ayrıntı (3-5 cümle)\n3. SONUÇ: talep veya kapanış (1-2 cümle)\n\nBu yapı hem e-postada hem dilekçede hem kompozisyonda geçerlidir."],
                        ['t'=>'rule','h'=>'Bağlayıcı kelimeler','b'=>"Sıralama: zuerst, dann, danach, außerdem, schließlich\nSebep: weil, denn, deshalb, aus diesem Grund\nZıtlık: aber, jedoch, trotzdem, obwohl\nÖrnek: zum Beispiel, besonders\nSonuç: also, deshalb, daher\nÖzet: insgesamt, zusammenfassend\n\nB1 metninde bu kelimelerden en az 3-4 tanesi bulunmalıdır. Bağlaçsız cümle dizisi A2 seviyesinde durur."],
                        ['t'=>'example','h'=>'Örnek metin','b'=>'İzin talebi (üç bölümlü yapı):','de'=>"Sehr geehrte Frau Meier,\n\nich schreibe Ihnen, weil ich vom 12. bis zum 16. Mai Urlaub nehmen möchte.\n\nDer Grund ist, dass meine Familie aus der Türkei zu Besuch kommt. Ich habe in dieser Woche keine wichtigen Termine. Außerdem hat Herr Demir zugesagt, meine Aufgaben zu übernehmen. Falls es trotzdem Probleme gibt, könnte ich den Urlaub auch auf Juni verschieben.\n\nIch würde mich über eine kurze Rückmeldung freuen.\n\nMit freundlichen Grüßen\nEmre Yılmaz",'tr'=>'Giriş: neden yazıyor. Gelişme: gerekçe, önlem, alternatif. Sonuç: kibar talep. Bağlaçlar: weil, dass, außerdem, falls, trotzdem.'],
                        ['t'=>'rule','h'=>'Kontrol listesi','b'=>"Yazdıktan sonra şunları kontrol et:\n\n□ Fiil ana cümlede ikinci sırada mı?\n□ Yan cümlede fiil sonda mı?\n□ Bütün isimler büyük harfle mi?\n□ Artikeller doğru mu (der/die/das, den/dem)?\n□ Perfekt\'te haben/sein doğru mu?\n□ En az üç bağlaç kullandın mı?\n□ Selamlamadan sonra virgül ve küçük harf var mı?"],
                    ],
                    'vocab' => ['außerdem','schließlich','zusammenfassend','jedoch','Rückmeldung','verschieben'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'b1_writing','q'=>'B1 metninde neden bağlayıcı kelimeler önemlidir?','a'=>'Metni tutarlı ve seviyeye uygun hale getirir','opts'=>['Metni tutarlı ve seviyeye uygun hale getirir','Metni uzatır','Zorunlu değildir','Sadece resmi yazıda gerekir'],'exp'=>'Bağlaçsız cümle dizisi A2 seviyesinde kalır.','vg'=>'write-connectors'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'b1_writing','q'=>'Hatayı düzelt: "Ich schreibe Ihnen, weil ich möchte Urlaub nehmen."','a'=>'Ich schreibe Ihnen, weil ich Urlaub nehmen möchte.','exp'=>'weil yan cümlesinde çekimli fiil (möchte) sona gider.','vg'=>'write-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'b1_writing','q'=>'"Kısa bir geri dönüş için sevinirim" cümlesini yaz.','a'=>'Ich würde mich über eine kurze Rückmeldung freuen.','exp'=>'sich freuen über + Akkusativ; würde ile kibar biçim.','vg'=>'write-closing'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_writing','q'=>'B1 metninin standart yapısı nedir?','a'=>'Giriş, gelişme, sonuç','opts'=>['Giriş, gelişme, sonuç','Sadece talep','Uzun bir paragraf','Madde madde liste'],'exp'=>'Üç bölümlü yapı hem e-posta hem kompozisyon için geçerlidir.','vg'=>'write-structure'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'b1_writing','q'=>'"Ayrıca meslektaşım görevlerimi devralmayı kabul etti" cümlesini yaz. (außerdem, zusagen, übernehmen)','a'=>'Außerdem hat mein Kollege zugesagt, meine Aufgaben zu übernehmen.','exp'=>'Außerdem birinci pozisyonda → fiil ikinci sırada; zu + Infinitiv sonda.','vg'=>'write-produce'],
                    ],
                ],
                [
                    'slug' => 'b1-konusma-degerlendirme',
                    'title' => 'B1 Konuşma ve Kapsamlı Değerlendirme',
                    'type' => 'grammar',
                    'minutes' => 20,
                    'objective' => 'Bir konuda görüş bildirmek, gerekçelendirmek ve B1 hedeflerini bir arada test etmek.',
                    'summary' => 'B1 yolunun son dersi. Buradaki mastery, uygulama içi B1 değerlendirmesinin temelini oluşturur.',
                    'skills' => ['b1_speaking','opinions_b1','b1_listening'],
                    'prereq' => ['meetings_b1'=>85,'b1_writing'=>85,'konjunktiv_ii_haette_waere'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Görüş bildirme yapısı','b'=>"B1 konuşmada beklenen üç adım:\n\n1. GÖRÜŞ: Meiner Meinung nach ...\n2. GEREKÇE: ... weil / denn ...\n3. ÖRNEK veya SONUÇ: Zum Beispiel ... / Deshalb ...\n\nMeiner Meinung nach ist Pünktlichkeit sehr wichtig, weil die ganze Schicht davon abhängt. Zum Beispiel kann eine Maschine nicht starten, wenn jemand fehlt."],
                        ['t'=>'rule','h'=>'Konuşurken zaman kazanma','b'=>"Doğal konuşma boşluk doldurucular içerir. Sessiz kalmak yerine:\n\nMoment, lassen Sie mich kurz überlegen. — Bir saniye, kısaca düşüneyim.\nDas ist eine gute Frage. — İyi bir soru.\nAlso, ich würde sagen ... — Şöyle diyeyim ...\nWie soll ich das sagen ... — Nasıl desem ...\n\nBu kalıplar hem düşünmene zaman verir hem de akıcı görünmeni sağlar.",'c'=>1],
                        ['t'=>'explanation','h'=>'Uygulama içi B1 değerlendirmesi','b'=>"Bu dersi ve önceki B1 derslerini tamamladığında AlmancaPro içi kapsamlı bir değerlendirme yapılır. Değerlendirilen alanlar:\n\n- Kelime hazinesi\n- Dilbilgisi\n- Okuma anlama\n- Yazma\n- İşlevsel Almanca\n- İş Almancası\n- Cümle üretimi\n\nÖnemli uyarı: Bu, AlmancaPro uygulama içi seviye değerlendirmesidir; Goethe, telc veya ÖSD tarafından verilen resmi B1 sertifikası DEĞİLDİR. Resmi sertifika için ilgili kurumun sınavına girmen gerekir."],
                        ['t'=>'usage','h'=>'Yanlış anlaşılmayı çözme','b'=>"Konuşma sırasında anlaşılmadığını fark edersen:\n\nIch meine Folgendes: ... — Şunu demek istiyorum: ...\nAnders gesagt ... — Başka bir deyişle ...\nIch formuliere das noch einmal. — Bunu bir kez daha ifade edeyim.\n\nAynı cümleyi tekrarlamak yerine BAŞKA kelimelerle anlatmak B1 seviyesinin işaretidir.",'c'=>1],
                    ],
                    'vocab' => ['meiner Meinung nach','Ich bin der Meinung, dass','Ich sehe das anders','einerseits ... andererseits','Es kommt darauf an','deutlich','Erfahrung'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_speaking','q'=>'B1 seviyesinde görüş bildirirken beklenen yapı nedir?','a'=>'Görüş + gerekçe + örnek','opts'=>['Görüş + gerekçe + örnek','Sadece görüş','Sadece örnek','Sadece soru sormak'],'exp'=>'Gerekçelendirilmemiş görüş A2 seviyesinde kalır.','vg'=>'speak-structure'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'opinions_b1','q'=>'"Bence dakiklik çok önemli, çünkü bütün vardiya buna bağlı" cümlesini yaz.','a'=>'Meiner Meinung nach ist Pünktlichkeit sehr wichtig, weil die ganze Schicht davon abhängt.','exp'=>'V2 + weil yan cümlesi (fiil sonda) + abhängen von → davon.','vg'=>'speak-opinion'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'b1_speaking','q'=>'Karşındaki seni anlamadı. B1 seviyesinde en doğru tepki nedir?','a'=>'Aynı fikri başka kelimelerle anlatmak','opts'=>['Aynı fikri başka kelimelerle anlatmak','Aynı cümleyi daha yüksek sesle tekrarlamak','Konuyu değiştirmek','Susmak'],'exp'=>'Yeniden ifade etme (Umformulierung) B1 becerisidir.','vg'=>'speak-repair'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'b1_speaking','q'=>'AlmancaPro içi B1 değerlendirmesi ne anlama gelir?','a'=>'Uygulama içi seviye değerlendirmesidir, resmi sertifika değildir','opts'=>['Uygulama içi seviye değerlendirmesidir, resmi sertifika değildir','Goethe sertifikası yerine geçer','telc sınavıdır','Resmi olarak tanınır'],'exp'=>'Resmi B1 sertifikası yalnızca Goethe, telc veya ÖSD gibi kurumlarca verilir.','vg'=>'speak-assessment'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'opinions_b1','q'=>'"Bir yandan pahalı, öte yandan güvenli" cümlesini yaz.','a'=>'Einerseits ist es teuer, andererseits ist es sicher.','exp'=>'einerseits ... andererseits; her iki cümlede de V2 kuralı geçerlidir.','vg'=>'speak-balance'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'b1_speaking','q'=>'Hatayı düzelt: "Es kommt darauf an, wie viel Zeit haben wir."','a'=>'Es kommt darauf an, wie viel Zeit wir haben.','exp'=>'Dolaylı soruda fiil sona gider.','vg'=>'speak-correct'],
                    ],
                ],
            ],
        ],
    ];
}
