<?php
/**
 * AlmancaPro - A2 mufredati.
 */
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME'])
    && basename((string)$_SERVER['SCRIPT_FILENAME']) === basename(__FILE__)
    && PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

function almancapro_curriculum_a2(): array
{
    return array_merge(
        almancapro_curriculum_a2_part1(),
        almancapro_curriculum_a2_part2(),
        almancapro_curriculum_a2_part3()
    );
}

function almancapro_curriculum_a2_part1(): array
{
    return [
        [
            'slug' => 'a2-m1-dativ',
            'level' => 'A2',
            'title' => 'Dativ Hali',
            'description' => 'Yönelme hali, Dativ zamirleri ve Akkusativ ile ayrımı. A2\'nin en kritik konusu.',
            'lessons' => [
                [
                    'slug' => 'a2-dativ',
                    'title' => 'Dativ: Yönelme Hali',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Dativ artikel biçimlerini ezberlemek ve Dativ isteyen fiilleri tanımak.',
                    'summary' => 'Akkusativ\'de yalnızca "der" değişiyordu. Dativ\'de HEPSİ değişir. Burası dikkat ister.',
                    'skills' => ['dativ'],
                    'prereq' => ['akkusativ'=>90,'definite_articles'=>90],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Dativ, DOLAYLI nesnenin halidir. Türkçedeki \"-e / -a\" yönelme ekine karşılık gelir.\n\nIch gebe dem Chef das Formular. — Amire formu veriyorum.\n     (kime? Dativ)  (neyi? Akkusativ)"],
                        ['t'=>'table','h'=>'Dativ biçimleri','b'=>"der → dem\ndie → der\ndas → dem\ndie (çoğul) → den + isme -n\n\nein → einem\neine → einer\nein → einem\n\nÇoğulda isme de -n eklenir: die Kinder → den Kindern"],
                        ['t'=>'how_recognize','h'=>'Nasıl anlarsın?','b'=>"Cümleye \"Wem?\" (kime?) sorusunu sor. Cevap Dativ'dir.\n\nIch helfe dem Kollegen. → Wem helfe ich? Dem Kollegen. ✓ Dativ"],
                        ['t'=>'rule','h'=>'Dativ isteyen fiiller','b'=>"Bazı fiiller Akkusativ değil, doğrudan Dativ ister. Bunlar ezberlenmelidir:\n\nhelfen (yardım etmek)\ndanken (teşekkür etmek)\nantworten (cevap vermek)\ngefallen (hoşuna gitmek)\ngehören (ait olmak)\npassen (uymak)\nfolgen (takip etmek)\nglauben (inanmak, kişiye)\n\nIch helfe dem Kollegen. (den Kollegen değil!)"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"amire\" derken ismin sonuna -e getiririz. Almancada isim değişmez, ARTIKEL değişir: der Chef → dem Chef.\n\nİyi haber: Türkçede de bu ayrım vardır (\"amiri gördüm\" / \"amire verdim\"), bu yüzden mantık sana yabancı değil. Zor olan tek şey artikel tablosunu ezberlemek."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Dativ tablosunu şu sırayla ezberle: dem – der – dem – den(+n). Eril ve nötr AYNIDIR (dem); dişil \"der\" olur (Nominativ'deki eril \"der\" ile karışmasın). Bu bir kural değil, ezberi kolaylaştıran bir dizilimdir.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"helfen fiilini Akkusativ ile kullanmak: \"Ich helfe den Kollegen\" yanlıştır (tekil kastediliyorsa). Doğrusu \"Ich helfe dem Kollegen\".",'c'=>1],
                    ],
                    'vocab' => ['helfen','geben','mit','zu','von','bei','Kollege','Chef'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'dativ','q'=>'"Ich helfe ___ Kollegen." Boşluğa hangisi gelir?','a'=>'dem','opts'=>['dem','den','der','das'],'exp'=>'helfen Dativ ister; der Kollege → dem Kollegen.','vg'=>'dat-verb'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'dativ','q'=>'"Ich gebe ___ Frau das Formular." Boşluğa hangisi gelir?','a'=>'der','opts'=>['der','die','dem','den'],'exp'=>'Dişil Dativ: die → der.','vg'=>'dat-fem'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'dativ','q'=>'Çoğul Dativ\'de ne olur?','a'=>'den + isme -n eklenir','opts'=>['den + isme -n eklenir','die değişmez','der olur','dem olur'],'exp'=>'die Kinder → den Kindern.','vg'=>'dat-plural'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'dativ','q'=>'Dativ hangi soruyla bulunur?','a'=>'Wem?','opts'=>['Wem?','Wen?','Wer?','Wessen?'],'exp'=>'Wem = kime.','vg'=>'dat-question'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'dativ','q'=>'Hatayı düzelt: "Ich danke den Chef."','a'=>'Ich danke dem Chef.','exp'=>'danken Dativ ister.','vg'=>'dat-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'dativ','q'=>'"Amire yardım ediyorum" cümlesini Almanca yaz.','a'=>'Ich helfe dem Chef.','exp'=>'helfen + Dativ.','vg'=>'dat-produce'],
                    ],
                ],
                [
                    'slug' => 'a2-dativ-zamirler',
                    'title' => 'Dativ Zamirleri',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'mir, dir, ihm gibi Dativ zamirlerini doğru kullanmak.',
                    'summary' => 'Günlük konuşmanın çok büyük kısmı bu zamirlerle kurulur.',
                    'skills' => ['dativ_pronouns'],
                    'prereq' => ['dativ'=>85],
                    'sections' => [
                        ['t'=>'table','h'=>'Zamir tablosu','b'=>"Nominativ → Akkusativ → Dativ\n\nich → mich → mir\ndu → dich → dir\ner → ihn → ihm\nsie → sie → ihr\nes → es → ihm\nwir → uns → uns\nihr → euch → euch\nsie → sie → ihnen\nSie → Sie → Ihnen"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Sık kullanılan kalıplar:','de'=>'Kannst du mir helfen?\nWie geht es Ihnen?\nDas gefällt mir.\nIch gebe ihm das Buch.','tr'=>'Bana yardım edebilir misin?\nNasılsınız?\nBu hoşuma gidiyor.\nOna kitabı veriyorum.'],
                        ['t'=>'rule','h'=>'İki nesne varsa sıra','b'=>"Cümlede hem Dativ hem Akkusativ nesne varsa:\n\nİkisi de İSİMSE: Dativ önce\n  Ich gebe dem Chef das Formular.\n\nBiri ZAMİRSE: zamir önce\n  Ich gebe ihm das Formular.\n  Ich gebe es dem Chef.\n\nİkisi de ZAMİRSE: Akkusativ önce\n  Ich gebe es ihm."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"bana\", \"beni\" ayrımı zaten var: ben-i (Akkusativ), ban-a (Dativ). Almancada da aynı ayrım var: mich / mir. Mantık tanıdık, sadece kelimeler yeni."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Kannst du mich helfen?\" demek. helfen Dativ ister: \"Kannst du mir helfen?\"",'c'=>1],
                    ],
                    'vocab' => ['mir','dir','ihm','uns','helfen','gefallen'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'dativ_pronouns','q'=>'Boşluğu doldur: "Kannst du ___ helfen?" (bana)','a'=>'mir','exp'=>'helfen Dativ ister: mir.','vg'=>'datpron-mir'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'dativ_pronouns','q'=>'Boşluğu doldur: "Wie geht es ___?" (resmi: size)','a'=>'Ihnen','exp'=>'Resmi Dativ zamiri Ihnen, büyük harfle yazılır.','vg'=>'datpron-ihnen'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'dativ_pronouns','q'=>'"er" zamirinin Dativ biçimi nedir?','a'=>'ihm','opts'=>['ihm','ihn','ihr','ihnen'],'exp'=>'er → ihn (Akkusativ) → ihm (Dativ).','vg'=>'datpron-table'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'dativ_pronouns','q'=>'"Ich gebe ___ ___." (ona / onu) Doğru sıralama hangisi?','a'=>'es ihm','opts'=>['es ihm','ihm es','ihn ihm','ihm ihn'],'exp'=>'İki zamir varsa Akkusativ önce gelir: es ihm.','vg'=>'datpron-order'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'dativ_pronouns','q'=>'Hatayı düzelt: "Kannst du mich helfen?"','a'=>'Kannst du mir helfen?','exp'=>'helfen Dativ ister: mir.','vg'=>'datpron-correct'],
                    ],
                ],
                [
                    'slug' => 'a2-akk-dat-ayrimi',
                    'title' => 'Akkusativ mi Dativ mi?',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Bir cümlede hangi öğenin hangi hale gireceğine karar vermek.',
                    'summary' => 'Bu ders A2\'nin kilit taşıdır. Doğru karar veremezsen sonraki her konu sorunlu olur.',
                    'skills' => ['akk_dat_distinction'],
                    'prereq' => ['dativ'=>85,'akkusativ'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Karar verme yöntemi','b'=>"1. Fiili bul.\n2. \"Wen/Was?\" (kimi/neyi) sor → cevap AKKUSATIV\n3. \"Wem?\" (kime) sor → cevap DATIV\n\nIch gebe dem Chef das Formular.\nWem gebe ich? → dem Chef (Dativ)\nWas gebe ich? → das Formular (Akkusativ)"],
                        ['t'=>'explanation','h'=>'Üç fiil grubu','b'=>"1) Yalnızca Akkusativ: kaufen, sehen, nehmen, haben, brauchen, essen, lesen, besuchen\n   Ich kaufe den Kaffee.\n\n2) Yalnızca Dativ: helfen, danken, gefallen, gehören, passen, antworten, folgen\n   Ich helfe dem Kollegen.\n\n3) Dativ + Akkusativ: geben, zeigen, schicken, bringen, erklären, empfehlen, schenken\n   Ich zeige dem Kunden das Produkt."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"yardım etmek\" fiili yönelme hali alır: \"amir-E yardım ettim\". Almancada da helfen Dativ alır. Bu benzerlik işine yarar.\n\nAma bazı fiiller ters çalışır:\nanrufen (aramak) → Akkusativ: Ich rufe DEN Chef an. (Türkçede \"amir-İ aradım\", uyumlu)\nfragen (sormak) → Akkusativ: Ich frage DEN Chef. (Türkçede \"amir-E sordum\", UYUMSUZ)\n\nBu yüzden fiili hal bilgisiyle birlikte ezberlemek gerekir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Türkçe mantığıyla fragen fiiline Dativ vermek: \"Ich frage dem Chef\" yanlıştır. Doğrusu \"Ich frage den Chef\".",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Yeni bir fiil öğrenirken hal bilgisini de yaz: \"helfen + Dativ\", \"fragen + Akkusativ\". Fiili tek başına öğrenirsen bu ayrım sürekli hata kaynağı olur.",'c'=>1],
                    ],
                    'vocab' => ['geben','zeigen','helfen','fragen','anrufen','erklären'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'akk_dat_distinction','q'=>'"Ich frage ___ Chef." Boşluğa hangisi gelir?','a'=>'den','opts'=>['den','dem','der','des'],'exp'=>'fragen Akkusativ ister, Türkçedeki "-e sormak" mantığından farklıdır.','vg'=>'akkdat-fragen'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'akk_dat_distinction','q'=>'"Ich danke ___ Kollegin." Boşluğa hangisi gelir?','a'=>'der','opts'=>['der','die','den','dem'],'exp'=>'danken Dativ ister; die Kollegin → der Kollegin.','vg'=>'akkdat-danken'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'akk_dat_distinction','q'=>'"Ich zeige dem Kunden das Produkt." cümlesinde "das Produkt" hangi haldedir?','a'=>'Akkusativ','opts'=>['Akkusativ','Dativ','Nominativ','Genitiv'],'exp'=>'Was zeige ich? → das Produkt (Akkusativ). Wem? → dem Kunden (Dativ).','vg'=>'akkdat-analyze'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'akk_dat_distinction','q'=>'Hatayı düzelt: "Ich rufe dem Arzt an."','a'=>'Ich rufe den Arzt an.','exp'=>'anrufen Akkusativ ister.','vg'=>'akkdat-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'akk_dat_distinction','q'=>'"Müşteriye ürünü gösteriyorum" cümlesini yaz. (der Kunde, das Produkt)','a'=>'Ich zeige dem Kunden das Produkt.','exp'=>'zeigen: Dativ (kime) + Akkusativ (neyi). Kunde n-Deklination olduğu için Kunden olur.','vg'=>'akkdat-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'akk_dat_distinction','q'=>'Hangi fiil Dativ ister?','a'=>'gefallen','opts'=>['gefallen','kaufen','sehen','brauchen'],'exp'=>'gefallen Dativ alır: Das gefällt mir.','vg'=>'akkdat-verbgroup'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'a2-m2-edatlar',
            'level' => 'A2',
            'title' => 'Edatlar ve Hal İlişkisi',
            'description' => 'Dativ edatları, Akkusativ edatları ve Wechselpräpositionen.',
            'lessons' => [
                [
                    'slug' => 'a2-dativ-edatlar',
                    'title' => 'Dativ Edatları',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Her zaman Dativ isteyen edatları ezberlemek ve kullanmak.',
                    'summary' => 'Bu edatlar günlük dilde çok sık geçer. Hepsi istisnasız Dativ alır.',
                    'skills' => ['dativ_prepositions'],
                    'prereq' => ['dativ'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Her zaman Dativ isteyen edatlar','b'=>"mit — ile\nnach — sonra; -e (şehir/ülke)\naus — -den (içinden), -li\nzu — -e (kişi/kurum)\nvon — -den, -in\nbei — yanında, -de\nseit — -den beri\ngegenüber — karşısında\n\nBunlar istisnasız Dativ alır. Ezberlemek zorundasın."],
                        ['t'=>'rule','h'=>'Kaynaşmalar','b'=>"zu + dem = zum\nzu + der = zur\nbei + dem = beim\nvon + dem = vom\n\nIch gehe zum Arzt. (zu dem Arzt)\nIch gehe zur Bank. (zu der Bank)"],
                        ['t'=>'explanation','h'=>'zu / nach / in farkı','b'=>"Bu üçü Türkçede hep \"-e\" olur ama Almancada ayrılır:\n\nzu → kişi veya kurum: zum Arzt, zur Bank, zu meinem Freund\nnach → şehir/ülke (artikelsiz) ve yönler: nach Berlin, nach Hause, nach links\nin → bina veya alan İÇİNE (Akkusativ ile): in die Stadt, in den Supermarkt\n\nÖzel kalıp: nach Hause (eve doğru) / zu Hause (evde)"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede tek bir \"-e/-a\" eki bütün bu anlamları karşılar. Almancada hedefin TÜRÜNE göre farklı edat seçilir. Bu, Türkçe konuşanlar için A2'nin en yorucu ayrımıdır ve ancak bol örnekle oturur."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich gehe nach dem Arzt\" demek. Kişi/kurum için zu kullanılır: \"Ich gehe zum Arzt.\"",'c'=>1],
                    ],
                    'vocab' => ['mit','nach','aus','zu','von','bei','seit'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'dativ_prepositions','q'=>'"Ich fahre mit ___ Bus." Boşluğa hangisi gelir?','a'=>'dem','opts'=>['dem','den','der','das'],'exp'=>'mit + Dativ; der Bus → dem Bus.','vg'=>'datprep-mit'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'dativ_prepositions','q'=>'"Doktora gidiyorum" nasıl denir?','a'=>'Ich gehe zum Arzt.','opts'=>['Ich gehe zum Arzt.','Ich gehe nach dem Arzt.','Ich gehe in den Arzt.','Ich gehe bei dem Arzt.'],'exp'=>'Kişi/kurum için zu: zu + dem = zum.','vg'=>'datprep-zu'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'dativ_prepositions','q'=>'"Berlin\'e gidiyorum" nasıl denir?','a'=>'Ich fahre nach Berlin.','opts'=>['Ich fahre nach Berlin.','Ich fahre zu Berlin.','Ich fahre in Berlin.','Ich fahre bei Berlin.'],'exp'=>'Artikelsiz şehir/ülke için nach.','vg'=>'datprep-nach'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'dativ_prepositions','q'=>'Boşluğu doldur: "Ich arbeite ___ einer Firma in Köln."','a'=>'bei','exp'=>'İşyeri için bei + Dativ kullanılır.','vg'=>'datprep-bei'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'dativ_prepositions','q'=>'"Bir yıldır burada oturuyorum" cümlesini yaz.','a'=>'Ich wohne seit einem Jahr hier.','alt'=>['Seit einem Jahr wohne ich hier.'],'exp'=>'seit + Dativ; das Jahr → einem Jahr. Almancada şimdiki zaman kullanılır.','vg'=>'datprep-seit'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'dativ_prepositions','q'=>'"Eve gidiyorum" nasıl denir?','a'=>'Ich gehe nach Hause.','opts'=>['Ich gehe nach Hause.','Ich gehe zu Hause.','Ich gehe in Hause.','Ich gehe bei Hause.'],'exp'=>'nach Hause = eve doğru; zu Hause = evde.','vg'=>'datprep-hause'],
                    ],
                ],
                [
                    'slug' => 'a2-akkusativ-edatlar',
                    'title' => 'Akkusativ Edatları',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'Her zaman Akkusativ isteyen edatları kullanmak.',
                    'summary' => 'Dativ edatlarından sonra bunlar kolay gelecek; sayıları daha az.',
                    'skills' => ['akkusativ_prepositions'],
                    'prereq' => ['dativ_prepositions'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Her zaman Akkusativ isteyen edatlar','b'=>"für — için\nohne — -siz\ngegen — karşı; civarında\num — etrafında; -de (saat)\ndurch — içinden, aracılığıyla\nbis — -e kadar\n\nHatırlama dizisi: FUDGOB (für, um, durch, gegen, ohne, bis)."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Günlük kullanım:','de'=>'Das ist für dich.\nIch trinke Kaffee ohne Zucker.\nDie Arbeit beginnt um acht Uhr.\nWir gehen durch den Park.','tr'=>'Bu senin için.\nKahveyi şekersiz içiyorum.\nİş sekizde başlıyor.\nParkın içinden geçiyoruz.'],
                        ['t'=>'rule','h'=>'ohne sonrası artikel düşer','b'=>"ohne edatından sonra genellikle artikel kullanılmaz:\nohne Zucker, ohne Auto, ohne Termin\n\nArtikel kullanılırsa Akkusativ olur: ohne einen Termin."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"für\" edatını Dativ ile kullanmak: \"für dem Chef\" yanlıştır. Doğrusu \"für den Chef\".",'c'=>1],
                    ],
                    'vocab' => ['für','ohne','gegen','um','durch'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'akkusativ_prepositions','q'=>'"Das ist für ___ Chef." Boşluğa hangisi gelir?','a'=>'den','opts'=>['den','dem','der','des'],'exp'=>'für + Akkusativ; der Chef → den Chef.','vg'=>'akkprep-fuer'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'akkusativ_prepositions','q'=>'Hangi edat her zaman Akkusativ ister?','a'=>'ohne','opts'=>['ohne','mit','bei','seit'],'exp'=>'ohne Akkusativ, diğer üçü Dativ ister.','vg'=>'akkprep-which'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'akkusativ_prepositions','q'=>'"Kahveyi şekersiz içiyorum" cümlesini yaz. (der Zucker)','a'=>'Ich trinke Kaffee ohne Zucker.','exp'=>'ohne sonrası artikel genelde düşer.','vg'=>'akkprep-ohne'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'akkusativ_prepositions','q'=>'Boşluğu doldur: "Die Besprechung beginnt ___ zehn Uhr."','a'=>'um','exp'=>'Saatle um kullanılır.','vg'=>'akkprep-um'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'akkusativ_prepositions','q'=>'"Baş ağrısına karşı bir ilaç" nasıl denir?','a'=>'ein Medikament gegen Kopfschmerzen','opts'=>['ein Medikament gegen Kopfschmerzen','ein Medikament für Kopfschmerzen','ein Medikament mit Kopfschmerzen','ein Medikament von Kopfschmerzen'],'exp'=>'gegen + Akkusativ, "karşı" anlamında.','vg'=>'akkprep-gegen'],
                    ],
                ],
                [
                    'slug' => 'a2-wechselpraepositionen',
                    'title' => 'Wechselpräpositionen: Wo? / Wohin?',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Dokuz değişken edatta hareket olup olmadığına göre hal seçmek.',
                    'summary' => 'Almancanın en zarif kurallarından biri: hal, anlamı belirler.',
                    'skills' => ['wechselpraepositionen','wo_wohin'],
                    'prereq' => ['dativ'=>90,'akkusativ'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Dokuz edat hem Dativ hem Akkusativ alabilir:\nin, an, auf, über, unter, vor, hinter, neben, zwischen\n\nWo? (nerede, HAREKET YOK) → DATIV\nWohin? (nereye, HAREKET VAR) → AKKUSATIV\n\nIch bin in der Küche. (Wo? → Dativ)\nIch gehe in die Küche. (Wohin? → Akkusativ)"],
                        ['t'=>'why','h'=>'Neden böyle bir kural var?','b'=>"Almanca, hareketi ve konumu dilbilgisiyle ayırır. Türkçede bu ayrım ekle yapılır:\n\nmutfak-TA (konum) → in der Küche\nmutfağ-A (hareket) → in die Küche\n\nYani Türkçede de aynı ayrım vardır! Sadece Almancada ek yerine artikel değişir. Bu, Türkçe konuşanın avantajlı olduğu bir konudur."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Aynı edat, iki anlam:','de'=>'Das Buch liegt auf dem Tisch. (Wo? Dativ)\nIch lege das Buch auf den Tisch. (Wohin? Akkusativ)','tr'=>'Kitap masanın üstünde duruyor.\nKitabı masanın üstüne koyuyorum.'],
                        ['t'=>'rule','h'=>'Fiil ipucu','b'=>"Bazı fiil çiftleri kuralı otomatik belirler:\n\nDURUM (Dativ): sein, liegen, stehen, sitzen, hängen, bleiben\nHAREKET (Akkusativ): gehen, fahren, legen, stellen, setzen, hängen (koymak)\n\nliegen (duruyor) → Dativ\nlegen (koymak) → Akkusativ"],
                        ['t'=>'rule','h'=>'Kaynaşmalar','b'=>"in + dem = im\nin + das = ins\nan + dem = am\nan + das = ans\n\nIch bin im Büro. (in dem)\nIch gehe ins Büro. (in das)"],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Hareket varken Dativ kullanmak: \"Ich gehe in der Stadt\" (şehirde yürüyorum) ile \"Ich gehe in die Stadt\" (şehre gidiyorum) tamamen farklı anlamlardır.",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Cümleyi Türkçeye çevir: \"-de/-da\" mı yoksa \"-e/-a\" mı diyorsun? \"-de\" ise Dativ, \"-e\" ise Akkusativ. Bu kısayol Türkçe konuşanlar için çok güvenilir çalışır.",'c'=>1],
                    ],
                    'vocab' => ['in','an','auf','unter','über','vor','hinter','neben','zwischen'],
                    'exercises' => [
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'wechselpraepositionen','q'=>'"Ich bin in ___ Küche." (mutfaktayım) Boşluğa hangisi gelir?','a'=>'der','opts'=>['der','die','den','dem'],'exp'=>'Wo? → Dativ; die Küche → der Küche.','vg'=>'wechsel-wo'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'wechselpraepositionen','q'=>'"Ich gehe in ___ Küche." (mutfağa gidiyorum) Boşluğa hangisi gelir?','a'=>'die','opts'=>['die','der','dem','den'],'exp'=>'Wohin? → Akkusativ; die Küche değişmez ama hal Akkusativ\'dir.','vg'=>'wechsel-wohin'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'wechselpraepositionen','q'=>'"Das Buch liegt auf ___ Tisch." Boşluğa hangisi gelir?','a'=>'dem','opts'=>['dem','den','der','das'],'exp'=>'liegen durum fiilidir → Dativ.','vg'=>'wechsel-liegen'],
                        ['type'=>'case_choice','mode'=>'recall','skill'=>'wechselpraepositionen','q'=>'"Ich lege das Buch auf ___ Tisch." Boşluğa hangisi gelir?','a'=>'den','opts'=>['den','dem','der','das'],'exp'=>'legen hareket fiilidir → Akkusativ.','vg'=>'wechsel-legen'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'wo_wohin','q'=>'"Ich fahre ___ Stadt." (şehre gidiyorum) Hangisi doğru?','a'=>'in die','opts'=>['in die','in der','zu die','nach die'],'exp'=>'Hareket var → Akkusativ: in die Stadt.','vg'=>'wechsel-apply'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'wo_wohin','q'=>'"Ofisteyim" cümlesini Almanca yaz. (das Büro)','a'=>'Ich bin im Büro.','alt'=>['Ich bin in dem Büro.'],'exp'=>'Wo? → Dativ; in + dem = im.','vg'=>'wechsel-produce'],
                    ],
                ],
            ],
        ],
    ];
}

function almancapro_curriculum_a2_part2(): array
{
    return [
        [
            'slug' => 'a2-m3-perfekt',
            'level' => 'A2',
            'title' => 'Geçmiş Zaman: Perfekt',
            'description' => 'Konuşma dilinin geçmiş zamanı. Partizip II, haben/sein seçimi ve Präteritum temeli.',
            'lessons' => [
                [
                    'slug' => 'a2-perfekt-temel',
                    'title' => 'Perfekt: Yapı',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Perfekt cümlesi kurmak ve yardımcı fiil + Partizip II yapısını yerleştirmek.',
                    'summary' => 'Almanlar günlük konuşmada geçmişi neredeyse her zaman Perfekt ile anlatır.',
                    'skills' => ['perfekt','partizip_ii_regular'],
                    'prereq' => ['haben_present'=>90,'verb_second'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Yapı','b'=>"Perfekt = haben/sein (çekimli, 2. pozisyonda) + Partizip II (cümlenin SONUNDA)\n\nIch habe gearbeitet.\nIch bin nach Berlin gefahren.\nWir haben das Formular ausgefüllt."],
                        ['t'=>'rule','h'=>'Düzenli Partizip II: ge- ... -t','b'=>"machen → gemacht\nlernen → gelernt\nkaufen → gekauft\narbeiten → gearbeitet (kök -t ile bitince araya e girer)\n\nAyrılabilir fiilde ge- ÖN EK İLE KÖK ARASINA girer:\neinkaufen → eingekauft\naufstehen → aufgestanden\n\nAyrılmayan ön ek varsa ge- HİÇ GELMEZ:\nbezahlen → bezahlt\nverstehen → verstanden\nerklären → erklärt\n\n-ieren ile bitenlerde de ge- gelmez:\nstudieren → studiert\nbuchstabieren → buchstabiert"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede geçmiş zaman tek ekle yapılır: \"çalış-tım\". Almancada iki parça gerekir ve bu parçalar cümlenin iki ucuna dağılır:\n\nIch HABE gestern acht Stunden GEARBEITET.\n\nBu \"cümle parantezi\" yapısına alışmak zaman alır. Türkçe konuşan için avantaj: Türkçede de fiil sonda olduğu için cümlenin sonunu dinleme alışkanlığın var."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Kelime kelime:','de'=>'Ich habe gestern das Formular ausgefüllt.','tr'=>'habe = yardımcı fiil (2. sırada) · ausgefüllt = Partizip II (sonda) · Anlam: Dün formu doldurdum.','hl'=>'ausgefüllt'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Partizip II\'yi ortaya koymak: \"Ich habe gearbeitet gestern\" yanlıştır. Partizip II her zaman cümlenin SONUNDADIR.",'c'=>1],
                    ],
                    'vocab' => ['machen','lernen','kaufen','arbeiten','bezahlen','einkaufen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_regular','q'=>'"machen" fiilinin Partizip II biçimi nedir?','a'=>'gemacht','opts'=>['gemacht','gemachen','machte','gemachte'],'exp'=>'Düzenli: ge- + kök + -t.','vg'=>'perf-regular'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_regular','q'=>'"bezahlen" fiilinin Partizip II biçimi nedir?','a'=>'bezahlt','opts'=>['bezahlt','gebezahlt','bezahlgt','bezahlen'],'exp'=>'be- ayrılmayan ön ektir, ge- gelmez.','vg'=>'perf-noge'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_regular','q'=>'"einkaufen" fiilinin Partizip II biçimi nedir?','a'=>'eingekauft','opts'=>['eingekauft','geeinkauft','einkauft','gekauftein'],'exp'=>'Ayrılabilir fiilde ge- ön ek ile kök arasına girer.','vg'=>'perf-separable'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'perfekt','q'=>'Kelimeleri sıraya diz: "gearbeitet / ich / gestern / habe"','a'=>'Ich habe gestern gearbeitet.','exp'=>'Yardımcı fiil 2. sırada, Partizip II sonda.','vg'=>'perf-order'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'perfekt','q'=>'Hatayı düzelt: "Ich habe gelernt Deutsch."','a'=>'Ich habe Deutsch gelernt.','exp'=>'Partizip II cümlenin sonundadır.','vg'=>'perf-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'perfekt','q'=>'"Dün formu doldurdum" cümlesini yaz. (ausfüllen)','a'=>'Ich habe gestern das Formular ausgefüllt.','exp'=>'ausfüllen → ausgefüllt; Partizip sonda.','vg'=>'perf-produce'],
                    ],
                ],
                [
                    'slug' => 'a2-haben-sein-secimi',
                    'title' => 'haben mi sein mi?',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Perfekt için doğru yardımcı fiili seçmek.',
                    'summary' => 'Yanlış yardımcı fiil, Almanca konuşan birinin kulağını hemen tırmalar.',
                    'skills' => ['perfekt_auxiliary'],
                    'prereq' => ['perfekt'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"sein kullanılır:\n1. YER DEĞİŞTİRME fiilleri: gehen, fahren, kommen, fliegen, laufen, reisen, umziehen\n2. DURUM DEĞİŞİMİ fiilleri: aufstehen, einschlafen, aufwachen, sterben, werden\n3. Üç istisna: sein, bleiben, passieren\n\nhaben kullanılır:\n- Diğer bütün fiiller\n- Akkusativ nesne alan bütün fiiller"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Aynı fiil, farklı yardımcı:','de'=>'Ich bin nach Köln gefahren. (yer değiştirme → sein)\nIch habe das Auto gefahren. (nesne var → haben)','tr'=>'Köln\'e gittim. / Arabayı kullandım.'],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede geçmiş zaman için yardımcı fiil yoktur; tek bir ek her fiil için çalışır. Almancada fiilin ANLAMINA göre iki farklı yardımcı fiil arasında seçim yaparsın. Türkçede karşılığı olmayan bu ayrım ezber gerektirir."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Şu soruyu sor: \"Bu fiil beni bir yerden bir yere mi taşıyor, ya da halimi mi değiştiriyor?\" Cevap evetse sein. Bu bir kısayoldur; istisnalar (bleiben, sein, passieren) ayrıca ezberlenir.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich habe nach Berlin gefahren\" demek. Yer değiştirme olduğu için sein gerekir: \"Ich bin nach Berlin gefahren.\"",'c'=>1],
                    ],
                    'vocab' => ['gehen','fahren','kommen','bleiben','aufstehen','werden'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'perfekt_auxiliary','q'=>'"Ich ___ nach Berlin gefahren." Boşluğa hangisi gelir?','a'=>'bin','opts'=>['bin','habe','war','wurde'],'exp'=>'fahren yer değiştirme fiilidir → sein.','vg'=>'aux-sein'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'perfekt_auxiliary','q'=>'"Ich ___ das Formular ausgefüllt." Boşluğa hangisi gelir?','a'=>'habe','opts'=>['habe','bin','war','wurde'],'exp'=>'Akkusativ nesne var → haben.','vg'=>'aux-haben'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'perfekt_auxiliary','q'=>'"bleiben" fiili Perfekt\'te hangi yardımcı fiili alır?','a'=>'sein','opts'=>['sein','haben','werden','ikisi de'],'exp'=>'bleiben hareket içermese de sein alan üç istisnadan biridir.','vg'=>'aux-exception'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'perfekt_auxiliary','q'=>'Hatayı düzelt: "Ich habe um sechs Uhr aufgestanden."','a'=>'Ich bin um sechs Uhr aufgestanden.','exp'=>'aufstehen durum değişimi fiilidir → sein.','vg'=>'aux-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'perfekt_auxiliary','q'=>'"Dün evde kaldım" cümlesini Perfekt ile yaz.','a'=>'Ich bin gestern zu Hause geblieben.','exp'=>'bleiben → sein + geblieben.','vg'=>'aux-produce'],
                    ],
                ],
                [
                    'slug' => 'a2-partizip-duzensiz',
                    'title' => 'Düzensiz Partizip II',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'En sık kullanılan düzensiz fiillerin üç biçimini ezberlemek.',
                    'summary' => 'Düzensiz fiiller azdır ama en sık kullanılanlardır. Ezberleri kaçınılmazdır.',
                    'skills' => ['partizip_ii_irregular'],
                    'prereq' => ['perfekt'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural: ge- ... -en','b'=>"Düzensiz fiillerde Partizip II \"ge- ... -en\" ile biter ve genellikle kök ünlüsü değişir.\n\nsprechen → gesprochen\nschreiben → geschrieben\nnehmen → genommen\ntrinken → getrunken\nessen → gegessen"],
                        ['t'=>'table','h'=>'En sık düzensiz fiiller','b'=>"sein – war – ist gewesen\nhaben – hatte – hat gehabt\ngehen – ging – ist gegangen\nfahren – fuhr – ist gefahren\nkommen – kam – ist gekommen\nsprechen – sprach – hat gesprochen\nschreiben – schrieb – hat geschrieben\nlesen – las – hat gelesen\nsehen – sah – hat gesehen\nnehmen – nahm – hat genommen\ngeben – gab – hat gegeben\nessen – aß – hat gegessen\ntrinken – trank – hat getrunken\nfinden – fand – hat gefunden\nhelfen – half – hat geholfen\nbleiben – blieb – ist geblieben\nverstehen – verstand – hat verstanden"],
                        ['t'=>'usage','h'=>'Nasıl çalışmalısın?','b'=>"Bir düzensiz fiili DÖRT parça halinde öğren:\nmastar – 3. tekil – Präteritum – Partizip II (yardımcı fiille)\n\nfahren – fährt – fuhr – ist gefahren\n\nDördü ayrı ayrı ezberlenirse hiçbiri kalıcı olmaz. Bir bütün olarak, ritimle tekrar et.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Düzensiz fiile düzenli ek vermek: \"gesprecht\" diye bir şey yoktur. Doğrusu \"gesprochen\"dur.",'c'=>1],
                    ],
                    'vocab' => ['sprechen','schreiben','lesen','sehen','nehmen','geben','essen','trinken','helfen','verstehen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_irregular','q'=>'"sprechen" fiilinin Partizip II biçimi nedir?','a'=>'gesprochen','opts'=>['gesprochen','gesprecht','gesprachen','gesprechen'],'exp'=>'sprechen – sprach – gesprochen.','vg'=>'irrp-1'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_irregular','q'=>'"schreiben" fiilinin Partizip II biçimi nedir?','a'=>'geschrieben','opts'=>['geschrieben','geschreibt','geschriebt','schreibte'],'exp'=>'schreiben – schrieb – geschrieben.','vg'=>'irrp-2'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'partizip_ii_irregular','q'=>'"trinken" fiilinin Partizip II biçimini yaz.','a'=>'getrunken','exp'=>'trinken – trank – getrunken.','vg'=>'irrp-3'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'partizip_ii_irregular','q'=>'"verstehen" fiilinin Partizip II biçimi nedir?','a'=>'verstanden','opts'=>['verstanden','geverstanden','verstehen','verstandet'],'exp'=>'ver- ayrılmayan ön ek → ge- gelmez: verstanden.','vg'=>'irrp-4'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'partizip_ii_irregular','q'=>'"Amirle konuştum" cümlesini Perfekt ile yaz.','a'=>'Ich habe mit dem Chef gesprochen.','exp'=>'mit + Dativ; sprechen → gesprochen.','vg'=>'irrp-produce'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'partizip_ii_irregular','q'=>'Hatayı düzelt: "Ich habe einen Brief geschreibt."','a'=>'Ich habe einen Brief geschrieben.','exp'=>'schreiben düzensizdir: geschrieben.','vg'=>'irrp-correct'],
                    ],
                ],
                [
                    'slug' => 'a2-praeteritum-war-hatte',
                    'title' => 'Präteritum: war ve hatte',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'sein ve haben fiillerinin geçmiş zamanını kullanmak.',
                    'summary' => 'Bu iki fiil konuşmada bile Perfekt yerine Präteritum ile kullanılır.',
                    'skills' => ['praeteritum_sein_haben','modal_past'],
                    'prereq' => ['perfekt'=>85],
                    'sections' => [
                        ['t'=>'table','h'=>'war ve hatte','b'=>"sein → war\nich war · du warst · er war · wir waren · ihr wart · sie waren\n\nhaben → hatte\nich hatte · du hattest · er hatte · wir hatten · ihr hattet · sie hatten"],
                        ['t'=>'rule','h'=>'Modal fiillerde de Präteritum tercih edilir','b'=>"können → konnte\nmüssen → musste\nwollen → wollte\ndürfen → durfte\nsollen → sollte\nmögen → mochte\n\nIch konnte gestern nicht kommen.\nIch musste zum Arzt gehen.\n\nModal fiillerin Perfekt biçimi de vardır ama konuşmada Präteritum daha yaygındır."],
                        ['t'=>'why','h'=>'Neden Perfekt kullanılmıyor?','b'=>"\"Ich bin krank gewesen\" dilbilgisel olarak doğrudur ama Almanlar günlük konuşmada \"Ich war krank\" der. sein, haben ve modal fiillerde Präteritum daha kısa ve doğaldır.\n\nDiğer fiillerde ise konuşmada Perfekt tercih edilir. Bu, öğrenilmesi gereken pratik bir alışkanlıktır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"hastaydım\" ve \"hasta olmuştum\" arasında ince bir fark vardır. Almancada war/hatte ile Perfekt arasındaki seçim çoğunlukla anlam değil, ÜSLUP farkıdır."],
                    ],
                    'vocab' => ['sein','haben','können','müssen','krank'],
                    'exercises' => [
                        ['type'=>'conjugation','mode'=>'recall','skill'=>'praeteritum_sein_haben','q'=>'Boşluğu doldur: "Gestern ___ ich krank." (sein, geçmiş)','a'=>'war','exp'=>'ich war.','vg'=>'praet-war'],
                        ['type'=>'conjugation','mode'=>'recall','skill'=>'praeteritum_sein_haben','q'=>'Boşluğu doldur: "Wir ___ keine Zeit." (haben, geçmiş)','a'=>'hatten','exp'=>'wir hatten.','vg'=>'praet-hatte'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'modal_past','q'=>'"können" fiilinin Präteritum biçimi nedir?','a'=>'konnte','opts'=>['konnte','kannte','könnte','gekonnt'],'exp'=>'können → konnte. (könnte ise Konjunktiv II\'dir.)','vg'=>'praet-modal'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'praeteritum_sein_haben','q'=>'"Dün hastaydım" cümlesini Almanca yaz.','a'=>'Gestern war ich krank.','alt'=>['Ich war gestern krank.'],'exp'=>'sein → war. V2 kuralına dikkat.','vg'=>'praet-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'modal_past','q'=>'"Dün gelemedim" nasıl denir?','a'=>'Ich konnte gestern nicht kommen.','opts'=>['Ich konnte gestern nicht kommen.','Ich habe gestern nicht kommen gekonnt.','Ich war gestern nicht kommen.','Ich kann gestern nicht kommen.'],'exp'=>'Modal fiillerde Präteritum tercih edilir.','vg'=>'praet-apply'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'a2-m4-nebensatz',
            'level' => 'A2',
            'title' => 'Yan Cümleler',
            'description' => 'weil, dass, wenn, als, obwohl. Fiilin sona gittiği yapı.',
            'lessons' => [
                [
                    'slug' => 'a2-nebensatz-temel',
                    'title' => 'Yan Cümlede Fiil Sonda',
                    'type' => 'grammar',
                    'minutes' => 16,
                    'objective' => 'Yan cümle kurmak ve fiili doğru konuma yerleştirmek.',
                    'summary' => 'Almancanın ikinci büyük yapı kuralı. Türkçe konuşanlar için aslında tanıdık.',
                    'skills' => ['nebensatz_verb_final','subordinate_weil'],
                    'prereq' => ['verb_second'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Yan cümle bir bağlaçla başlar ve ÇEKİMLİ FİİL yan cümlenin SONUNA gider.\n\nIch lerne Deutsch, weil ich in Deutschland arbeite.\n                    (bağlaç)              (fiil sonda)\n\nİki cümle arasına VİRGÜL konur. Almancada bu virgül zorunludur."],
                        ['t'=>'explanation','h'=>'Yan cümle başta olursa','b'=>"Yan cümle önce gelirse, TAMAMI birinci pozisyonu doldurur ve ana cümlenin fiili hemen arkasından gelir:\n\nWeil ich in Deutschland arbeite, lerne ich Deutsch.\n                                 (fiil)  (özne)\n\nBuna \"fiil fiile bakar\" durumu denir: ...arbeite, lerne... İki fiil virgülün iki yanında yan yana gelir."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede fiil zaten cümlenin sonundadır. Yani yan cümlede fiilin sona gitmesi sana YABANCI DEĞİL — tam tersine tanıdık geliyor.\n\nAsıl zorluk şu: Almancada ANA cümlede fiil ikinci, YAN cümlede sonda. Yani aynı dilde iki farklı düzen var ve doğru olanı seçmen gerekiyor."],
                        ['t'=>'rule','h'=>'weil ve denn farkı','b'=>"İkisi de \"çünkü\" demektir ama yapıları farklıdır:\n\nweil → YAN cümle, fiil sonda\n  Ich bleibe zu Hause, weil ich krank bin.\n\ndenn → ANA cümle bağlacı, fiil normal 2. pozisyonda\n  Ich bleibe zu Hause, denn ich bin krank.\n\nAnlam aynıdır; hangisini kullanacağın sana kalmış."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"weil\'den sonra fiili ikinci sırada bırakmak: \"weil ich bin krank\" yanlıştır. Doğrusu \"weil ich krank bin\".",'c'=>1],
                        ['t'=>'example','h'=>'Örnek','b'=>'Ayrılabilir fiil yan cümlede birleşir:','de'=>'Ich bin müde, weil ich um fünf Uhr aufstehe.','tr'=>'Yorgunum çünkü saat beşte kalkıyorum. — Yan cümlede "stehe ... auf" ayrılmaz, "aufstehe" olarak birleşir.','hl'=>'aufstehe'],
                    ],
                    'vocab' => ['weil','denn','arbeiten','krank'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'nebensatz_verb_final','q'=>'Hangi cümle doğrudur?','a'=>'Ich lerne Deutsch, weil ich in Deutschland arbeite.','opts'=>['Ich lerne Deutsch, weil ich in Deutschland arbeite.','Ich lerne Deutsch, weil ich arbeite in Deutschland.','Ich lerne Deutsch, weil arbeite ich in Deutschland.','Ich lerne Deutsch weil in Deutschland ich arbeite.'],'exp'=>'weil yan cümle kurar; fiil sona gider ve virgül zorunludur.','vg'=>'neben-choose'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'subordinate_weil','q'=>'İki cümleyi weil ile birleştir: "Ich bleibe zu Hause." + "Ich bin krank."','a'=>'Ich bleibe zu Hause, weil ich krank bin.','exp'=>'weil sonrası fiil sona gider.','vg'=>'neben-combine'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'nebensatz_verb_final','q'=>'Hatayı düzelt: "Ich komme nicht, weil ich habe keine Zeit."','a'=>'Ich komme nicht, weil ich keine Zeit habe.','exp'=>'weil yan cümlesinde fiil sonda olmalı.','vg'=>'neben-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'subordinate_weil','q'=>'"denn" ile "weil" arasındaki fark nedir?','a'=>'denn ana cümle bağlacıdır, fiil 2. sırada kalır','opts'=>['denn ana cümle bağlacıdır, fiil 2. sırada kalır','Anlamları farklıdır','denn yalnızca yazıda kullanılır','weil fiili 2. sırada bırakır'],'exp'=>'Anlam aynı, yapı farklı.','vg'=>'neben-denn'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'nebensatz_verb_final','q'=>'Yan cümleyi başa alarak yeniden yaz: "Ich lerne Deutsch, weil ich in Deutschland arbeite."','a'=>'Weil ich in Deutschland arbeite, lerne ich Deutsch.','exp'=>'Yan cümle 1. pozisyonu doldurur, ana cümlenin fiili hemen arkasından gelir.','vg'=>'neben-front'],
                    ],
                ],
                [
                    'slug' => 'a2-dass',
                    'title' => 'dass ile Yan Cümle',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'Düşünce, bilgi ve görüş aktarmak için dass kullanmak.',
                    'summary' => 'Fikir bildirmenin ve dolaylı anlatımın temel yapısı.',
                    'skills' => ['subordinate_dass'],
                    'prereq' => ['nebensatz_verb_final'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"dass, bir cümleyi diğerinin nesnesi yapar. Fiil yine sona gider.\n\nIch glaube, dass er heute kommt.\nIch weiß, dass die Besprechung um zehn beginnt.\nEs ist wichtig, dass Sie pünktlich sind."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede bu yapı ekle kurulur: \"onun geldiğiNİ sanıyorum\". Almancada ayrı bir bağlaç (dass) kullanılır ve iki ayrı cümle olur.\n\nTürkçe: Bugün geleceğini sanıyorum.\nAlmanca: Ich glaube, dass er heute kommt.\n\nTürkçede tek cümle, Almancada iki cümle."],
                        ['t'=>'rule','h'=>'dass ile başlayan sık kalıplar','b'=>"Ich glaube, dass ... — ... olduğunu sanıyorum\nIch denke, dass ... — ... diye düşünüyorum\nIch weiß, dass ... — ... olduğunu biliyorum\nIch hoffe, dass ... — ... umuyorum\nEs ist wichtig, dass ... — ... önemli\nEs tut mir leid, dass ... — ... için üzgünüm"],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"das\" ile \"dass\" karıştırmak. das = artikel veya işaret zamiri (das Auto, das ist gut). dass = bağlaç. Yazımda tek s / çift s farkı anlamı değiştirir.",'c'=>1],
                    ],
                    'vocab' => ['dass','glauben','wissen','wichtig'],
                    'exercises' => [
                        ['type'=>'word_order','mode'=>'production','skill'=>'subordinate_dass','q'=>'Cümleleri dass ile birleştir: "Ich glaube." + "Er kommt heute."','a'=>'Ich glaube, dass er heute kommt.','exp'=>'dass sonrası fiil sona gider.','vg'=>'dass-combine'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'subordinate_dass','q'=>'"das" ile "dass" arasındaki fark nedir?','a'=>'das artikel/zamir, dass bağlaç','opts'=>['das artikel/zamir, dass bağlaç','İkisi de bağlaç','das yazıda, dass konuşmada','Fark yok'],'exp'=>'das Auto (artikel) / Ich weiß, dass ... (bağlaç).','vg'=>'dass-vs-das'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'subordinate_dass','q'=>'Hatayı düzelt: "Ich weiß, dass die Besprechung beginnt um zehn."','a'=>'Ich weiß, dass die Besprechung um zehn beginnt.','exp'=>'Fiil yan cümlenin sonuna gider.','vg'=>'dass-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'subordinate_dass','q'=>'"Dakik olmanız önemli" cümlesini Almanca yaz.','a'=>'Es ist wichtig, dass Sie pünktlich sind.','exp'=>'Es ist wichtig, dass + yan cümle; fiil sonda.','vg'=>'dass-produce'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'subordinate_dass','q'=>'Boşluğu doldur: "Ich hoffe, ___ Sie mir helfen können."','a'=>'dass','exp'=>'Bağlaç olarak çift s ile dass yazılır.','vg'=>'dass-fill'],
                    ],
                ],
                [
                    'slug' => 'a2-wenn-als',
                    'title' => 'wenn ve als',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Koşul ve zaman bildirirken doğru bağlacı seçmek.',
                    'summary' => 'Türkçede ikisi de "-diğinde" olur; Almancada seçim kurala bağlıdır.',
                    'skills' => ['subordinate_wenn','subordinate_als'],
                    'prereq' => ['nebensatz_verb_final'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"wenn kullanılır:\n- Şimdiki veya gelecek zamanda her durumda\n- Geçmişte TEKRARLANAN olaylarda\n- Koşul (eğer) anlamında\n\nals kullanılır:\n- Geçmişte BİR KEZ olmuş olayda"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Fark net görünsün:','de'=>'Als ich nach Deutschland kam, sprach ich kein Deutsch. (bir kez)\nWenn ich Zeit habe, lerne ich Deutsch. (her seferinde)\nImmer wenn ich müde war, trank ich Kaffee. (geçmişte tekrarlanan)','tr'=>'Almanya\'ya geldiğimde hiç Almanca bilmiyordum.\nVaktim olduğunda Almanca öğreniyorum.\nHer yorgun olduğumda kahve içerdim.'],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"-diğinde\" eki bütün bu durumları karşılar. Almancada geçmişte tek seferlik olay için ayrı bir bağlaç (als) vardır. Türkçe konuşanlar bu ayrımı sürekli atlar."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Şu soruyu sor: \"Bu olay geçmişte SADECE BİR KEZ mi oldu?\" Evet ise als, aksi halde wenn. Bu bir kısayoldur, kuralın kendisi yukarıdadır.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Geçmişteki tek olayda wenn kullanmak: \"Wenn ich nach Deutschland kam...\" yanlıştır (tek seferlikse). Doğrusu \"Als ich nach Deutschland kam...\"",'c'=>1],
                    ],
                    'vocab' => ['wenn','als','Zeit'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'subordinate_als','q'=>'"Almanya\'ya geldiğimde hiç Almanca bilmiyordum." Hangi bağlaç kullanılır?','a'=>'als','opts'=>['als','wenn','dass','weil'],'exp'=>'Geçmişte tek seferlik olay → als.','vg'=>'wennals-choose'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'subordinate_wenn','q'=>'"Vaktim olduğunda Almanca öğreniyorum." Hangi bağlaç kullanılır?','a'=>'wenn','opts'=>['wenn','als','dass','obwohl'],'exp'=>'Tekrarlanan/şimdiki durum → wenn.','vg'=>'wennals-choose'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'subordinate_wenn','q'=>'Cümleleri birleştir: "Ich habe Zeit." + "Ich lerne Deutsch." (wenn ile, yan cümle başta)','a'=>'Wenn ich Zeit habe, lerne ich Deutsch.','exp'=>'Yan cümle başta → ana cümlenin fiili hemen arkasından gelir.','vg'=>'wenn-order'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'subordinate_als','q'=>'Hatayı düzelt: "Wenn ich 2020 nach Köln zog, sprach ich kein Deutsch."','a'=>'Als ich 2020 nach Köln zog, sprach ich kein Deutsch.','exp'=>'Geçmişte tek seferlik olay → als.','vg'=>'als-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'subordinate_wenn','q'=>'"Hastaysan işe gelme" cümlesini wenn ile yaz.','a'=>'Wenn du krank bist, komm nicht zur Arbeit.','alt'=>['Wenn du krank bist, komme nicht zur Arbeit.'],'exp'=>'Koşul → wenn; yan cümlede fiil sonda.','vg'=>'wenn-produce'],
                    ],
                ],
                [
                    'slug' => 'a2-baglaclar-genis',
                    'title' => 'obwohl, deshalb, trotzdem, sondern',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Zıtlık ve sonuç bildiren bağlaçları doğru yapıyla kullanmak.',
                    'summary' => 'Bu bağlaçlar üç farklı yapı grubuna ayrılır; hangisinin ne yaptığını bilmek gerekir.',
                    'skills' => ['subordinate_obwohl','connectors_deshalb','conjunctions_aduso'],
                    'prereq' => ['nebensatz_verb_final'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Üç grup','b'=>"1) YAN CÜMLE bağlaçları (fiil SONDA): weil, dass, wenn, als, obwohl, damit, bevor\n   Obwohl es regnet, gehe ich zur Arbeit.\n\n2) ANA CÜMLE bağlaçları (sıra DEĞİŞMEZ): und, aber, oder, denn, sondern\n   Es regnet, aber ich gehe zur Arbeit.\n\n3) ZARF bağlaçları (fiil HEMEN ARKASINDAN gelir): deshalb, deswegen, trotzdem, dann, danach\n   Es regnet, trotzdem gehe ich zur Arbeit."],
                        ['t'=>'explanation','h'=>'sondern ne zaman?','b'=>"sondern yalnızca OLUMSUZ bir cümleden sonra, düzeltme yaparken kullanılır:\n\nIch komme nicht aus Berlin, sondern aus Köln.\nDas ist nicht mein Auto, sondern sein Auto.\n\nOlumsuz cümle yoksa \"aber\" kullanılır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"ama\" tek kelimedir ve düzeltme yaparken de kullanılır: \"Berlin'den değil, Köln'den geliyorum.\" Almancada bu iki durum ayrılır: aber (zıtlık) / sondern (düzeltme)."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"deshalb\'den sonra özneyi öne almak: \"Ich bin krank, deshalb ich bleibe zu Hause\" yanlıştır. deshalb birinci pozisyonu doldurur, fiil hemen arkasından gelir: \"deshalb bleibe ich zu Hause\".",'c'=>1],
                    ],
                    'vocab' => ['obwohl','deshalb','trotzdem','sondern','aber','denn'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'connectors_deshalb','q'=>'Hangi cümle doğrudur?','a'=>'Ich bin krank, deshalb bleibe ich zu Hause.','opts'=>['Ich bin krank, deshalb bleibe ich zu Hause.','Ich bin krank, deshalb ich bleibe zu Hause.','Ich bin krank, deshalb ich zu Hause bleibe.','Ich bin krank, deshalb zu Hause ich bleibe.'],'exp'=>'deshalb 1. pozisyondadır, fiil hemen arkasından gelir.','vg'=>'conn-deshalb'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'conjunctions_aduso','q'=>'"Berlin\'den değil, Köln\'den geliyorum." Hangi bağlaç kullanılır?','a'=>'sondern','opts'=>['sondern','aber','denn','obwohl'],'exp'=>'Olumsuz cümleden sonra düzeltme → sondern.','vg'=>'conn-sondern'],
                        ['type'=>'word_order','mode'=>'production','skill'=>'subordinate_obwohl','q'=>'Cümleleri obwohl ile birleştir (yan cümle başta): "Es regnet." + "Ich gehe zur Arbeit."','a'=>'Obwohl es regnet, gehe ich zur Arbeit.','exp'=>'obwohl yan cümle kurar, fiil sonda; ana cümlede fiil hemen virgülden sonra.','vg'=>'conn-obwohl'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'connectors_deshalb','q'=>'Hatayı düzelt: "Es ist spät, trotzdem ich arbeite weiter."','a'=>'Es ist spät, trotzdem arbeite ich weiter.','exp'=>'trotzdem zarf bağlacıdır; fiil hemen arkasından gelir.','vg'=>'conn-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'conjunctions_aduso','q'=>'Hangi bağlaçtan sonra kelime sırası hiç değişmez?','a'=>'aber','opts'=>['aber','weil','deshalb','obwohl'],'exp'=>'und, aber, oder, denn, sondern ana cümle bağlaçlarıdır ve sırayı değiştirmez.','vg'=>'conn-group'],
                    ],
                ],
            ],
        ],
    ];
}

function almancapro_curriculum_a2_part3(): array
{
    return [
        [
            'slug' => 'a2-m5-sifat-refleksiv',
            'level' => 'A2',
            'title' => 'Sıfatlar ve Dönüşlü Fiiller',
            'description' => 'Karşılaştırma, üstünlük ve dönüşlü fiiller.',
            'lessons' => [
                [
                    'slug' => 'a2-komparativ',
                    'title' => 'Karşılaştırma (Komparativ)',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'İki şeyi karşılaştırmak ve düzensiz biçimleri bilmek.',
                    'summary' => 'Fiyat, iş, ev karşılaştırırken sürekli ihtiyaç duyacaksın.',
                    'skills' => ['comparative','adjective_basics'],
                    'prereq' => ['sein_present'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Sıfata -er eklenir, karşılaştırma \"als\" ile yapılır:\n\nklein → kleiner\nDie Wohnung ist kleiner als das Haus.\n\nEşitlik için \"so ... wie\" kullanılır:\nDie Wohnung ist so groß wie das Haus."],
                        ['t'=>'rule','h'=>'Umlaut ve düzensizler','b'=>"Tek heceli birçok sıfat umlaut alır:\ngroß → größer · alt → älter · jung → jünger · lang → länger · kurz → kürzer · warm → wärmer\n\nDüzensizler ezberlenir:\ngut → besser → am besten\nviel → mehr → am meisten\ngern → lieber → am liebsten\nhoch → höher → am höchsten\nnah → näher → am nächsten"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede karşılaştırma \"daha\" kelimesiyle yapılır ve sıfat değişmez: \"daha büyük\". Almancada sıfatın KENDİSİ değişir: größer.\n\nAyrıca Türkçede \"-den\" eki kullanılır (\"evden büyük\"); Almancada \"als\" kelimesi kullanılır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"mehr groß\" gibi İngilizce mantığıyla \"daha\" kelimesi eklemek. Almancada sıfata doğrudan -er eklenir: größer.",'c'=>1],
                    ],
                    'vocab' => ['besser','am besten','größer','mehr','weniger','genauso','teuer','billig'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'comparative','q'=>'"groß" sıfatının karşılaştırma biçimi nedir?','a'=>'größer','opts'=>['größer','großer','mehr groß','am größten'],'exp'=>'Tek heceli sıfat umlaut alır: groß → größer.','vg'=>'komp-form'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'comparative','q'=>'"gut" sıfatının karşılaştırma biçimi nedir?','a'=>'besser','opts'=>['besser','guter','gutter','mehr gut'],'exp'=>'gut → besser → am besten (düzensiz).','vg'=>'komp-irregular'],
                        ['type'=>'fill_blank','mode'=>'production','skill'=>'comparative','q'=>'Boşluğu doldur: "Die Wohnung ist teurer ___ das Zimmer."','a'=>'als','exp'=>'Karşılaştırmada als kullanılır.','vg'=>'komp-als'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'comparative','q'=>'"Bu ev diğerinden daha eski" cümlesini yaz. (das Haus, das andere)','a'=>'Dieses Haus ist älter als das andere.','exp'=>'alt → älter; karşılaştırmada als.','vg'=>'komp-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'superlative','q'=>'"En iyisi bu" nasıl denir?','a'=>'Das ist am besten.','opts'=>['Das ist am besten.','Das ist besser.','Das ist der beste als.','Das ist am guten.'],'exp'=>'Üstünlük: am + sıfat + -sten. gut → am besten.','vg'=>'super-form'],
                    ],
                ],
                [
                    'slug' => 'a2-refleksiv',
                    'title' => 'Dönüşlü Fiiller',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Dönüşlü fiilleri ve dönüşlü zamirleri kullanmak.',
                    'summary' => 'Almanya\'daki resmi işlemlerin çoğu dönüşlü fiillerle anlatılır: sich anmelden, sich bewerben.',
                    'skills' => ['reflexive_verbs','reflexive_pronouns'],
                    'prereq' => ['dativ_pronouns'=>85],
                    'sections' => [
                        ['t'=>'table','h'=>'Dönüşlü zamirler','b'=>"Akkusativ: mich · dich · sich · uns · euch · sich\nDativ: mir · dir · sich · uns · euch · sich\n\nÇoğu dönüşlü fiil Akkusativ zamiri alır."],
                        ['t'=>'rule','h'=>'Sık kullanılan dönüşlü fiiller','b'=>"sich anmelden — kayıt yaptırmak\nsich bewerben — başvurmak\nsich vorstellen — kendini tanıtmak\nsich freuen — sevinmek\nsich interessieren — ilgilenmek\nsich beeilen — acele etmek\nsich setzen — oturmak\nsich fühlen — hissetmek\nsich erinnern — hatırlamak"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Zamir fiile göre çekilir:','de'=>'Ich melde mich beim Bürgeramt an.\nEr bewirbt sich um eine Stelle.\nWir freuen uns auf den Urlaub.','tr'=>'Nüfus dairesine kayıt yaptırıyorum.\nBir pozisyona başvuruyor.\nTatili dört gözle bekliyoruz.'],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede dönüşlülük fiilin içine giren bir ekle yapılır: \"yıka-n-mak\", \"giy-in-mek\". Almancada ayrı bir zamir kullanılır ve bu zamir özneye göre değişir.\n\nAyrıca Almancada bazı fiiller Türkçede dönüşlü olmadıkları halde dönüşlüdür: sich bewerben (başvurmak). Bunları liste halinde öğrenmek gerekir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Zamiri unutmak: \"Ich bewerbe um eine Stelle\" yanlıştır. Doğrusu \"Ich bewerbe mich um eine Stelle\".",'c'=>1],
                    ],
                    'vocab' => ['sich anmelden','sich bewerben','sich vorstellen','sich freuen','sich','Bürgeramt'],
                    'exercises' => [
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'reflexive_pronouns','q'=>'Boşluğu doldur: "Ich melde ___ beim Bürgeramt an."','a'=>'mich','exp'=>'ich → mich (Akkusativ dönüşlü zamir).','vg'=>'refl-pronoun'],
                        ['type'=>'fill_blank','mode'=>'recall','skill'=>'reflexive_pronouns','q'=>'Boşluğu doldur: "Er bewirbt ___ um eine Stelle."','a'=>'sich','exp'=>'er/sie/es → sich.','vg'=>'refl-pronoun'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'reflexive_verbs','q'=>'Hatayı düzelt: "Ich freue auf den Urlaub."','a'=>'Ich freue mich auf den Urlaub.','exp'=>'sich freuen dönüşlü bir fiildir; zamir zorunludur.','vg'=>'refl-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'reflexive_verbs','q'=>'"Kendimi tanıtabilir miyim?" cümlesini yaz.','a'=>'Darf ich mich vorstellen?','exp'=>'sich vorstellen; modal soru yapısı.','vg'=>'refl-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'reflexive_verbs','q'=>'"Nüfus dairesine kayıt yaptırmam gerekiyor" nasıl denir?','a'=>'Ich muss mich beim Bürgeramt anmelden.','opts'=>['Ich muss mich beim Bürgeramt anmelden.','Ich muss beim Bürgeramt anmelden.','Ich muss mich beim Bürgeramt an.','Ich muss mir beim Bürgeramt anmelden.'],'exp'=>'Modal + dönüşlü zamir + mastar sonda.','vg'=>'refl-apply'],
                    ],
                ],
                [
                    'slug' => 'a2-zu-infinitiv',
                    'title' => 'zu + Infinitiv',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'İki fiilli cümlelerde zu kullanımını doğru yapmak.',
                    'summary' => 'Modal fiillerden farklı olarak burada "zu" gerekir. Ne zaman gerekmediğini de bilmelisin.',
                    'skills' => ['zu_infinitiv'],
                    'prereq' => ['modal_koennen'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Bazı fiil ve ifadelerden sonra ikinci fiil \"zu + Infinitiv\" biçiminde ve cümlenin sonunda gelir:\n\nIch habe vergessen, das Formular auszufüllen.\nEs ist wichtig, pünktlich zu sein.\nIch hoffe, dich bald zu sehen.\n\nAyrılabilir fiilde zu ÖN EK İLE KÖK ARASINA girer: aus-zu-füllen."],
                        ['t'=>'rule','h'=>'zu KULLANILMAYAN yerler','b'=>"Modal fiillerden sonra: Ich kann kommen. (zu yok)\nwerden ile gelecek: Ich werde kommen.\nsehen, hören, lassen, gehen: Ich gehe schwimmen. Ich lasse das Auto reparieren."],
                        ['t'=>'rule','h'=>'zu isteyen sık ifadeler','b'=>"vergessen, versuchen, anfangen, aufhören, hoffen, versprechen, vorhaben\nes ist wichtig / möglich / schwer / einfach\nLust haben, Zeit haben, keine Lust haben"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"-mek/-mak\" mastarı doğrudan kullanılır: \"gelmeyi unuttum\". Almancada araya bir \"zu\" girer ve mastar cümlenin sonuna gider."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Modal fiilden sonra zu koymak: \"Ich kann zu kommen\" yanlıştır. Modallerden sonra zu KULLANILMAZ.",'c'=>1],
                    ],
                    'vocab' => ['vergessen','anfangen','wichtig','möglich'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'zu_infinitiv','q'=>'Hangi cümle doğrudur?','a'=>'Es ist wichtig, pünktlich zu sein.','opts'=>['Es ist wichtig, pünktlich zu sein.','Es ist wichtig, pünktlich sein.','Es ist wichtig, zu pünktlich sein.','Es ist wichtig, sein pünktlich zu.'],'exp'=>'zu + Infinitiv, mastar sonda.','vg'=>'zuinf-basic'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'zu_infinitiv','q'=>'"ausfüllen" fiili zu ile nasıl yazılır?','a'=>'auszufüllen','opts'=>['auszufüllen','zu ausfüllen','ausfüllen zu','zu füllen aus'],'exp'=>'Ayrılabilir fiilde zu ön ek ile kök arasına girer.','vg'=>'zuinf-separable'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'zu_infinitiv','q'=>'Hangi cümlede zu KULLANILMAZ?','a'=>'Ich kann morgen kommen.','opts'=>['Ich kann morgen kommen.','Ich hoffe morgen zu kommen.','Ich vergesse zu kommen.','Es ist möglich zu kommen.'],'exp'=>'Modal fiillerden sonra zu kullanılmaz.','vg'=>'zuinf-nozu'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'zu_infinitiv','q'=>'Hatayı düzelt: "Ich habe vergessen, das Formular ausfüllen."','a'=>'Ich habe vergessen, das Formular auszufüllen.','exp'=>'vergessen zu ister; ayrılabilir fiilde zu araya girer.','vg'=>'zuinf-correct'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'zu_infinitiv','q'=>'"Sana yardım etmeyi umuyorum" cümlesini yaz.','a'=>'Ich hoffe, dir zu helfen.','exp'=>'hoffen + zu + Infinitiv; helfen Dativ ister.','vg'=>'zuinf-produce'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'a2-m6-gunluk-almanya',
            'level' => 'A2',
            'title' => 'Almanya\'da Günlük Hayat',
            'description' => 'Ev kiralama, resmi kurumlar, banka ve sağlık sistemi.',
            'lessons' => [
                [
                    'slug' => 'a2-ev-kiralama',
                    'title' => 'Ev Kiralama',
                    'type' => 'daily_life',
                    'minutes' => 14,
                    'objective' => 'Ev ilanı okumak, ev sahibiyle konuşmak ve sözleşme kelimelerini anlamak.',
                    'summary' => 'Almanya\'da ev bulmak zordur; doğru kelimeleri bilmek büyük avantajdır.',
                    'skills' => ['renting_flat'],
                    'prereq' => ['dativ_prepositions'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Temel kelimeler','b'=>"die Kaltmiete — çıplak kira (ısınma/aidat hariç)\ndie Warmmiete — ek giderler dahil kira\ndie Nebenkosten — ek giderler\ndie Kaution — depozito\nder Vermieter — ev sahibi\nder Mieter — kiracı\nder Mietvertrag — kira sözleşmesi\ndie Wohnfläche — kullanım alanı (m²)\nZKB — Zimmer, Küche, Bad"],
                        ['t'=>'explanation','h'=>'İlan okuma','b'=>"Tipik ilan: \"3 ZKB, 75 m², 850 € kalt + 200 € NK, 3 MM Kaution\"\n\n3 ZKB = 3 oda, mutfak, banyo\n75 m² = 75 metrekare\n850 € kalt = çıplak kira\n200 € NK = ek giderler\n3 MM Kaution = 3 aylık kira depozito"],
                        ['t'=>'usage','h'=>'Faydalı cümleler','b'=>"Ich interessiere mich für die Wohnung. — Daireyle ilgileniyorum.\nIst die Wohnung noch frei? — Daire hâlâ boş mu?\nWann kann ich die Wohnung besichtigen? — Daireyi ne zaman görebilirim?\nWie hoch sind die Nebenkosten? — Ek giderler ne kadar?\nIst eine Küche vorhanden? — Mutfak mevcut mu?",'c'=>1],
                        ['t'=>'explanation','h'=>'Dikkat notu','b'=>"Almanya'da birçok daire mutfaksız kiralanır; mutfağı kiracı kendi kurar. İlanda \"EBK\" (Einbauküche) yazıyorsa mutfak vardır.\n\nBu bilgiler zamanla ve şehre göre değişebilir; sözleşme imzalamadan önce ayrıntıları mutlaka ev sahibiyle netleştir."],
                    ],
                    'vocab' => ['Wohnung','Miete','Vermieter','Mietvertrag','Kaution','Nebenkosten','Hausmeister','Heizung','mieten','umziehen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'renting_flat','q'=>'"Kaltmiete" ne demektir?','a'=>'Ek giderler hariç kira','opts'=>['Ek giderler hariç kira','Ek giderler dahil kira','Depozito','Isınmasız daire'],'exp'=>'Kaltmiete = çıplak kira; Warmmiete ek giderleri içerir.','vg'=>'rent-vocab'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'renting_flat','q'=>'"3 ZKB" ne anlama gelir?','a'=>'3 oda, mutfak, banyo','opts'=>['3 oda, mutfak, banyo','3 katlı bina','3 kişilik daire','3 aylık kira'],'exp'=>'ZKB = Zimmer, Küche, Bad.','vg'=>'rent-abbrev'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'renting_flat','q'=>'"Daire hâlâ boş mu?" cümlesini Almanca yaz.','a'=>'Ist die Wohnung noch frei?','exp'=>'Evet/hayır sorusu: fiil başta.','vg'=>'rent-ask'],
                        ['type'=>'article','mode'=>'recall','skill'=>'renting_flat','q'=>'"Kaution" kelimesinin artikeli nedir?','a'=>'die','opts'=>['die','der','das'],'exp'=>'-ion ile biten isimler die alır: die Kaution.','vg'=>'rent-article'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'renting_flat','q'=>'Ev sahibine ek giderleri sormak istiyorsun. Hangisi doğru?','a'=>'Wie hoch sind die Nebenkosten?','opts'=>['Wie hoch sind die Nebenkosten?','Wie viel ist die Nebenkosten?','Was kostet Nebenkosten?','Wo sind die Nebenkosten?'],'exp'=>'Nebenkosten çoğuldur → sind.','vg'=>'rent-apply'],
                    ],
                ],
                [
                    'slug' => 'a2-resmi-kurumlar',
                    'title' => 'Resmi Kurumlar ve Anmeldung',
                    'type' => 'daily_life',
                    'minutes' => 14,
                    'objective' => 'Randevu almak, form doldurmak ve memurla iletişim kurmak.',
                    'summary' => 'Almanya\'da resmi işlemler randevu ve belge üzerine kuruludur.',
                    'skills' => ['authorities_a2'],
                    'prereq' => ['reflexive_verbs'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Temel kelimeler','b'=>"das Bürgeramt / Einwohnermeldeamt — nüfus dairesi\ndie Anmeldung — ikamet kaydı\ndie Abmeldung — kayıt sildirme\ndie Ummeldung — adres değişikliği\ndie Meldebescheinigung — ikamet belgesi\nder Termin — randevu\ndie Unterlagen — belgeler\ndas Formular — form\nausfüllen — doldurmak\neinreichen — teslim etmek"],
                        ['t'=>'usage','h'=>'Faydalı cümleler','b'=>"Ich möchte einen Termin vereinbaren. — Randevu almak istiyorum.\nIch möchte mich anmelden. — Kayıt yaptırmak istiyorum.\nWelche Unterlagen brauche ich? — Hangi belgelere ihtiyacım var?\nKönnen Sie mir beim Formular helfen? — Formda bana yardım edebilir misiniz?\nIch verstehe dieses Wort nicht. — Bu kelimeyi anlamıyorum.",'c'=>1],
                        ['t'=>'explanation','h'=>'Süreç hakkında','b'=>"Almanya'da yeni bir adrese taşındıktan sonra ikamet kaydı (Anmeldung) yapılır. Genellikle randevu gerekir ve randevular yoğun şehirlerde haftalar öncesinden dolabilir.\n\nGerekli belgeler ve süreler şehre ve zamana göre değişir. Güncel listeyi ilgili belediyenin resmi sayfasından veya doğrudan kurumdan öğren. Bu ders dil öğretir, hukuki danışmanlık vermez."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Formu anlamadan imzalamak. Anlamadığın bir alan varsa \"Was bedeutet das?\" (Bu ne demek?) diye sormak tamamen normaldir ve memurlar açıklamak zorundadır.",'c'=>1],
                    ],
                    'vocab' => ['Bürgeramt','Anmeldung','Ausweis','Formular','Unterlagen','Termin','beantragen','bestätigen','Bescheid'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'authorities_a2','q'=>'"Randevu almak istiyorum" nasıl denir?','a'=>'Ich möchte einen Termin vereinbaren.','opts'=>['Ich möchte einen Termin vereinbaren.','Ich möchte ein Termin machen.','Ich will Termin.','Ich habe einen Termin vereinbaren.'],'exp'=>'der Termin → einen Termin; möchten + mastar sonda.','vg'=>'auth-appointment'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'authorities_a2','q'=>'"Anmeldung" ne demektir?','a'=>'İkamet kaydı','opts'=>['İkamet kaydı','Kayıt sildirme','Randevu','Oturma izni'],'exp'=>'die Anmeldung = kayıt/ikamet kaydı. Abmeldung ise kayıt sildirmedir.','vg'=>'auth-vocab'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'authorities_a2','q'=>'"Hangi belgelere ihtiyacım var?" cümlesini yaz.','a'=>'Welche Unterlagen brauche ich?','exp'=>'welche + çoğul isim; brauchen Akkusativ ister.','vg'=>'auth-ask'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'authorities_a2','q'=>'Formda anlamadığın bir kelime var. Ne yaparsın?','a'=>'Was bedeutet das? diye sorarım','opts'=>['Was bedeutet das? diye sorarım','Boş bırakırım','Rastgele doldururum','İmzalayıp giderim'],'exp'=>'Anlamadan imzalamak risklidir; sormak normaldir.','vg'=>'auth-safety'],
                        ['type'=>'article','mode'=>'recall','skill'=>'authorities_a2','q'=>'"Formular" kelimesinin artikeli nedir?','a'=>'das','opts'=>['das','der','die'],'exp'=>'das Formular – die Formulare.','vg'=>'auth-article'],
                    ],
                ],
                [
                    'slug' => 'a2-banka-saglik',
                    'title' => 'Banka ve Sağlık Sistemi',
                    'type' => 'daily_life',
                    'minutes' => 14,
                    'objective' => 'Hesap açmak, havale yapmak ve sağlık sigortasıyla iletişim kurmak.',
                    'summary' => 'Maaş almak için banka hesabı, çalışmak için sağlık sigortası gerekir.',
                    'skills' => ['bank_a2','health_a2'],
                    'prereq' => ['authorities_a2'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Banka kelimeleri','b'=>"das Konto — hesap\ndas Girokonto — vadesiz hesap\ndie IBAN — IBAN numarası\ndie Überweisung — havale\nder Dauerauftrag — düzenli ödeme talimatı\nabheben — para çekmek\neinzahlen — para yatırmak\nüberweisen — havale etmek\nder Kontoauszug — hesap özeti"],
                        ['t'=>'rule','h'=>'Sağlık kelimeleri','b'=>"die Krankenkasse — sağlık sigortası kurumu\ndie Versichertenkarte — sigorta kartı\nder Hausarzt — aile hekimi\ndie Überweisung — sevk (doktor için)\ndas Rezept — reçete\ndie Praxis — muayenehane\ndie Sprechstunde — muayene saati\n\nDikkat: \"Überweisung\" hem banka havalesi hem doktor sevki anlamına gelir; bağlamdan anlaşılır."],
                        ['t'=>'usage','h'=>'Faydalı cümleler','b'=>"Ich möchte ein Konto eröffnen. — Hesap açmak istiyorum.\nWie ist Ihre IBAN? — IBAN\'ınız nedir?\nBei welcher Krankenkasse sind Sie? — Hangi sağlık sigortasındasınız?\nIch brauche ein Rezept. — Reçeteye ihtiyacım var.\nWann ist Sprechstunde? — Muayene saati ne zaman?",'c'=>1],
                        ['t'=>'explanation','h'=>'Dikkat notu','b'=>"Almanya'da çalışanlar için sağlık sigortası zorunludur ve genellikle maaştan kesilir. Sigorta türleri, katkı payları ve kurallar zamanla değişebilir. Güncel durumu işvereninden veya sigorta kurumundan öğren."],
                    ],
                    'vocab' => ['Bankkonto','Überweisung','Krankenkasse','Versicherung','Medikament','Apotheke','Termin','bestätigen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'bank_a2','q'=>'"Hesap açmak istiyorum" nasıl denir?','a'=>'Ich möchte ein Konto eröffnen.','opts'=>['Ich möchte ein Konto eröffnen.','Ich möchte einen Konto eröffnen.','Ich will Konto machen.','Ich habe ein Konto eröffnen.'],'exp'=>'das Konto → ein Konto; möchten + mastar sonda.','vg'=>'bank-open'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'bank_a2','q'=>'"überweisen" ne demektir?','a'=>'Havale etmek','opts'=>['Havale etmek','Para çekmek','Para yatırmak','Hesap kapatmak'],'exp'=>'überweisen = havale etmek; abheben = çekmek; einzahlen = yatırmak.','vg'=>'bank-verb'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'health_a2','q'=>'"Krankenkasse" ne demektir?','a'=>'Sağlık sigortası kurumu','opts'=>['Sağlık sigortası kurumu','Hastane','Eczane','Muayenehane'],'exp'=>'die Krankenkasse = sağlık sigortası kurumu.','vg'=>'health-vocab'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'health_a2','q'=>'"Reçeteye ihtiyacım var" cümlesini yaz. (das Rezept)','a'=>'Ich brauche ein Rezept.','exp'=>'brauchen + Akkusativ; das Rezept → ein Rezept.','vg'=>'health-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'health_a2','q'=>'"Überweisung" kelimesi doktorda hangi anlama gelir?','a'=>'Uzman doktora sevk','opts'=>['Uzman doktora sevk','Para havalesi','Reçete','Randevu'],'exp'=>'Bankada havale, sağlıkta sevk anlamına gelir. Bağlam belirler.','vg'=>'health-context'],
                    ],
                ],
            ],
        ],

        [
            'slug' => 'a2-m7-is-almancasi',
            'level' => 'A2',
            'title' => 'İş Almancası A2',
            'description' => 'E-posta yazma, telefon görüşmesi ve kibar rica kalıpları.',
            'lessons' => [
                [
                    'slug' => 'a2-is-eposta',
                    'title' => 'İş E-postası Yazma',
                    'type' => 'workplace',
                    'minutes' => 16,
                    'objective' => 'Resmi bir e-postayı doğru yapıyla yazmak.',
                    'summary' => 'Almanya\'da iş iletişiminin büyük kısmı e-posta ile yürür. Yapı standarttır.',
                    'skills' => ['workplace_email','polite_requests'],
                    'prereq' => ['zu_infinitiv'=>85,'sie_du'=>90],
                    'sections' => [
                        ['t'=>'rule','h'=>'E-posta yapısı','b'=>"1. Konu (Betreff): kısa ve net\n   Betreff: Urlaubsantrag für den 12.-16. Mai\n\n2. Selamlama:\n   Sehr geehrte Damen und Herren, (isim bilinmiyorsa)\n   Sehr geehrter Herr Wagner, (erkek)\n   Sehr geehrte Frau Meier, (kadın)\n   Hallo Thomas, (samimi ekipte)\n\n3. Giriş cümlesi\n4. Ana mesaj\n5. Kapanış: Mit freundlichen Grüßen\n6. Ad soyad\n\nDikkat: Selamlamadan sonra VİRGÜL gelir ve bir sonraki satır KÜÇÜK harfle başlar."],
                        ['t'=>'rule','h'=>'Kibar kalıplar','b'=>"ich möchte Sie bitten, ... — sizden rica etmek istiyorum\nKönnten Sie bitte ...? — ... yapabilir misiniz?\nWäre es möglich, ...? — ... mümkün olur muydu?\nVielen Dank im Voraus. — Şimdiden çok teşekkürler.\nIch freue mich auf Ihre Antwort. — Cevabınızı bekliyorum."],
                        ['t'=>'example','h'=>'Örnek e-posta','b'=>'İzin talebi:','de'=>"Betreff: Urlaubsantrag für den 12.-16. Mai\n\nSehr geehrter Herr Wagner,\n\nich möchte vom 12. bis zum 16. Mai Urlaub nehmen. Meine Aufgaben übernimmt in dieser Zeit Herr Demir.\n\nKönnten Sie mir bitte Bescheid geben, ob das möglich ist?\n\nVielen Dank im Voraus.\n\nMit freundlichen Grüßen\nEmre Yılmaz",'tr'=>'Konu: 12-16 Mayıs izin talebi. Resmi hitap, net talep, kibar soru, teşekkür ve standart kapanış.'],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçe iş e-postalarında \"Sayın ...,\" sonrası genellikle büyük harfle devam edilir. Almancada selamlamadan sonra virgül konur ve sonraki satır KÜÇÜK harfle başlar (ilk kelime isim değilse). Bu, Almanca yazışmanın belirgin bir kuralıdır."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Sehr geehrte Herr Wagner\" yazmak. Erkek için \"geehrter\" (r ile), kadın için \"geehrte\" olur: Sehr geehrter Herr Wagner / Sehr geehrte Frau Meier.",'c'=>1],
                    ],
                    'vocab' => ['E-Mail','Besprechung','Urlaub','Frist','bestätigen','Termin verschieben'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'workplace_email','q'=>'Bay Wagner\'a resmi e-posta yazıyorsun. Doğru selamlama hangisi?','a'=>'Sehr geehrter Herr Wagner,','opts'=>['Sehr geehrter Herr Wagner,','Sehr geehrte Herr Wagner,','Sehr geehrten Herr Wagner,','Lieber Herr Wagner!'],'exp'=>'Erkek için "geehrter" kullanılır; sonrasında virgül gelir.','vg'=>'email-salutation'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'workplace_email','q'=>'Resmi e-postada standart kapanış hangisidir?','a'=>'Mit freundlichen Grüßen','opts'=>['Mit freundlichen Grüßen','Tschüss','Bis bald','Liebe Grüße'],'exp'=>'Mit freundlichen Grüßen resmi standarttır.','vg'=>'email-closing'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'polite_requests','q'=>'En kibar rica hangisidir?','a'=>'Könnten Sie mir bitte Bescheid geben?','opts'=>['Könnten Sie mir bitte Bescheid geben?','Geben Sie mir Bescheid.','Sie müssen mir Bescheid geben.','Ich will Bescheid.'],'exp'=>'Konjunktiv II (könnten) en kibar biçimdir.','vg'=>'email-polite'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'workplace_email','q'=>'"Şimdiden çok teşekkürler" ifadesini Almanca yaz.','a'=>'Vielen Dank im Voraus.','exp'=>'Standart e-posta kapanış kalıbıdır.','vg'=>'email-thanks'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'workplace_email','q'=>'Almanca e-postada selamlamadan sonra ne gelir?','a'=>'Virgül ve sonraki satır küçük harfle başlar','opts'=>['Virgül ve sonraki satır küçük harfle başlar','Ünlem ve büyük harf','İki nokta','Nokta ve büyük harf'],'exp'=>'Bu, Almanca yazışmanın standart kuralıdır.','vg'=>'email-format'],
                    ],
                ],
                [
                    'slug' => 'a2-telefon',
                    'title' => 'Telefonda Konuşma',
                    'type' => 'workplace',
                    'minutes' => 14,
                    'objective' => 'Telefonda kendini tanıtmak, anlamadığını söylemek ve mesaj bırakmak.',
                    'summary' => 'Telefon, dil öğrenenler için en zor beceridir çünkü karşındakini göremezsin.',
                    'skills' => ['telephone_a2'],
                    'prereq' => ['workplace_email'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Telefon kalıpları','b'=>"Açılış:\n  [Firma], [Ad] am Apparat. — [Firma], ben [Ad].\n  Guten Tag, hier ist Emre Yılmaz.\n\nBağlantı isteme:\n  Könnte ich bitte Herrn Wagner sprechen?\n  Ich möchte gern mit Frau Meier sprechen.\n\nAnlamadığında:\n  Entschuldigung, die Verbindung ist schlecht. — Bağlantı kötü.\n  Könnten Sie das bitte wiederholen?\n  Könnten Sie bitte langsamer sprechen?\n  Wie schreibt man das? — Bu nasıl yazılıyor?\n\nKapanış:\n  Vielen Dank. Auf Wiederhören."],
                        ['t'=>'usage','h'=>'Mesaj bırakma','b'=>"Kann ich eine Nachricht hinterlassen? — Mesaj bırakabilir miyim?\nKönnen Sie ihm ausrichten, dass ich angerufen habe? — Aradığımı iletebilir misiniz?\nEr soll mich bitte zurückrufen. — Lütfen beni geri arasın.\nMeine Nummer ist ...",'c'=>1],
                        ['t'=>'explanation','h'=>'Telefonda hayatta kalma taktiği','b'=>"Telefonda anlamamak normaldir. Şu üç cümle her durumu kurtarır:\n\n1. Entschuldigung, ich habe Sie nicht verstanden.\n2. Könnten Sie das bitte langsam wiederholen?\n3. Können Sie mir das per E-Mail schicken? — Bunu bana e-postayla gönderebilir misiniz?\n\nÜçüncüsü özellikle değerlidir: yazılı bilgi her zaman daha güvenlidir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Telefonu \"Auf Wiedersehen\" diye kapatmak. Telefonda doğru veda \"Auf Wiederhören\"dir.",'c'=>1],
                    ],
                    'vocab' => ['anrufen','E-Mail','Termin','wiederholen','verstehen','Nachricht'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'telephone_a2','q'=>'Telefonu kapatırken hangisi doğrudur?','a'=>'Auf Wiederhören','opts'=>['Auf Wiederhören','Auf Wiedersehen','Gute Nacht','Bis später sehen'],'exp'=>'Telefonda "hören" (duymak) kullanılır.','vg'=>'phone-close'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'telephone_a2','q'=>'Karşı taraf çok hızlı konuşuyor. En doğru tepki?','a'=>'Könnten Sie bitte langsamer sprechen?','opts'=>['Könnten Sie bitte langsamer sprechen?','Ja, verstanden.','Auf Wiederhören.','Ich rufe später an.'],'exp'=>'Anlamadan onaylamak yerine yavaşlatma istemek doğrudur.','vg'=>'phone-slow'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'telephone_a2','q'=>'"Mesaj bırakabilir miyim?" cümlesini Almanca yaz.','a'=>'Kann ich eine Nachricht hinterlassen?','exp'=>'Modal soru + Akkusativ nesne + mastar sonda.','vg'=>'phone-message'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'telephone_a2','q'=>'Önemli bir bilgiyi telefonda tam anlayamadın. En güvenli çözüm nedir?','a'=>'Können Sie mir das per E-Mail schicken?','opts'=>['Können Sie mir das per E-Mail schicken?','Ja, alles klar.','Ich rufe morgen wieder an.','Auf Wiederhören.'],'exp'=>'Yazılı bilgi istemek yanlış anlamayı önler.','vg'=>'phone-safety'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'telephone_a2','q'=>'"Herrn Wagner ile görüşebilir miyim?" nasıl denir?','a'=>'Könnte ich bitte Herrn Wagner sprechen?','opts'=>['Könnte ich bitte Herrn Wagner sprechen?','Kann ich Herr Wagner?','Ich will Herrn Wagner sprechen.','Wo ist Herr Wagner?'],'exp'=>'Konjunktiv II ile kibar rica. Herr n-Deklination olduğu için Herrn olur.','vg'=>'phone-connect'],
                    ],
                ],
            ],
        ],
    ];
}
