<?php
/**
 * AlmancaPro - A0 mufredati: modul, ders, bolum ve egzersizler.
 */
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME'])
    && basename((string)$_SERVER['SCRIPT_FILENAME']) === basename(__FILE__)
    && PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

function almancapro_curriculum_a0(): array
{
    return [
        /* ============================================================
         * MODUL 1 - Sesler ve alfabe
         * ============================================================ */
        [
            'slug' => 'a0-m1-alfabe-ses',
            'level' => 'A0',
            'title' => 'Alfabe ve Sesler',
            'description' => 'Almanca harfleri tanı, okunuşu doğru öğren. Yanlış öğrenilen ses ileride yanlış yazıma dönüşür.',
            'lessons' => [
                [
                    'slug' => 'a0-alfabe',
                    'title' => 'Alman Alfabesi',
                    'type' => 'pronunciation',
                    'minutes' => 12,
                    'objective' => 'Almanca 26 harfin adını söyleyebilmek ve kendi adını harf harf söyleyebilmek.',
                    'summary' => 'Alfabe, telefonda ad-soyad söylerken ve resmi kurumlarda en çok işine yarayacak temel beceridir.',
                    'skills' => ['alphabet'],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almanca alfabe Türkçe alfabeye çok benzer: aynı Latin harfleri kullanılır. Fakat harflerin ADI farklıdır. Türkçede \"b\" harfini \"be\" diye okuruz; Almancada da \"be\" denir, ama \"c\" harfi \"tse\", \"j\" harfi \"yot\", \"w\" harfi \"ve\" diye okunur.\n\nBir Alman memur sana \"Wie schreibt man das?\" (Bu nasıl yazılıyor?) diye sorduğunda, adını harf harf söylemen gerekir. Bu yüzden alfabe süs değil, gerçek bir hayat becerisidir."],
                        ['t'=>'table','h'=>'Harf adları','b'=>"A [a] · B [be] · C [tse] · D [de] · E [e] · F [ef] · G [ge] · H [ha] · I [i] · J [yot] · K [ka] · L [el] · M [em] · N [en] · O [o] · P [pe] · Q [ku] · R [er] · S [es] · T [te] · U [u] · V [fau] · W [ve] · X [iks] · Y [üpsilon] · Z [tset]"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede harflerin adı okunuşuyla neredeyse aynıdır. Almancada dört harf Türkçe konuşanları en çok yanıltır:\n\nJ = \"yot\" (Türkçe \"c\" gibi değil)\nV = \"fau\" ve kelime içinde çoğunlukla \"f\" okunur\nW = \"ve\" ve kelime içinde \"v\" okunur\nZ = \"tset\" ve kelime içinde \"ts\" okunur"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Ad soyad söylemek:','de'=>'Mein Name ist Yılmaz: Ypsilon – I – L – M – A – Zett.','tr'=>'Adım Yılmaz: Y – I – L – M – A – Z.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"J\" harfini Türkçedeki gibi \"j\" (jandarma) diye okumak. Almancada Ja (evet) kelimesi \"ya\" okunur, \"ja\" değil.",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"W ve V harfini birlikte ezberle: W = \"ve\" sesi, V = \"fe\" sesi. Yani ikisi de Türkçedeki karşılığının tersi gibi çalışır. Bu bir kural değil, yardımcı bir ezber yöntemidir.",'c'=>1],
                    ],
                    'vocab' => ['Buchstabe','Name','Wort','buchstabieren'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'alphabet','q'=>'Almancada "J" harfinin adı nedir?','a'=>'yot','opts'=>['yot','ji','ce','yi'],'exp'=>'J harfi "yot" diye okunur ve kelime içinde "y" sesi verir: ja = ya.','vg'=>'alphabet-letter'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'alphabet','q'=>'"W" harfi kelime içinde hangi sesi verir?','a'=>'v','opts'=>['v','w (İngilizce gibi)','f','u'],'exp'=>'Wasser kelimesi "vasır" diye okunur. W = v sesidir.','vg'=>'alphabet-sound'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'alphabet','q'=>'"Z" harfi kelime içinde hangi sesi verir?','a'=>'ts','opts'=>['ts','z','s','c'],'exp'=>'zehn kelimesi "tseen" okunur. Z = ts sesidir.','vg'=>'alphabet-sound'],
                        ['type'=>'text_input','mode'=>'recall','skill'=>'alphabet','q'=>'"Vater" kelimesindeki V harfi hangi sesi verir? Tek harfle yaz.','a'=>'f','alt'=>['F'],'exp'=>'Almanca kökenli kelimelerde V genellikle "f" okunur: Vater = "fatır".','vg'=>'alphabet-sound'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'alphabet','q'=>'Bir memur adını soruyor. Hangi cümleyle harf harf söylemesini isteyebilirsin?','a'=>'Können Sie das buchstabieren?','opts'=>['Können Sie das buchstabieren?','Wie geht es Ihnen?','Wo wohnen Sie?','Was kostet das?'],'exp'=>'buchstabieren = harf harf söylemek. Resmi ortamda bu cümle çok işe yarar.','vg'=>'alphabet-use'],
                    ],
                ],
                [
                    'slug' => 'a0-umlaut',
                    'title' => 'ä, ö, ü ve ß',
                    'type' => 'pronunciation',
                    'minutes' => 12,
                    'objective' => 'Umlaut harflerini tanımak, doğru okumak ve doğru yazmak.',
                    'summary' => 'ä, ö, ü ve ß Almancanın dört özel karakteridir. Yanlış yazılırsa kelime anlamı değişebilir.',
                    'skills' => ['umlaut_sounds','eszett'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada üç umlaut harfi vardır: ä, ö, ü. Bunlar süs değil, ayrı seslerdir.\n\nä ≈ Türkçedeki \"e\" sesine çok yakındır.\nö = Türkçedeki \"ö\" ile aynıdır.\nü = Türkçedeki \"ü\" ile aynıdır.\n\nİyi haber: Türkçede zaten ö ve ü var. Bu, Türkçe konuşanların Almanca telaffuzda İngilizce konuşanlara göre avantajlı olduğu noktalardan biridir."],
                        ['t'=>'rule','h'=>'Kural','b'=>"ß harfi (Eszett) yalnızca \"ss\" sesini verir ve UZUN bir ünlüden ya da çift ünlüden sonra gelir.\n\nStraße (uzun a) → ß\nFluss (kısa u) → ss\n\nKlavyende ß yoksa \"ss\" yazabilirsin: Strasse. Bu resmi yazışmada da kabul edilir. Ama ä, ö, ü yerine a, o, u yazamazsın; onların yerine ae, oe, ue yazılır."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede ö ve ü var, ä yok. Almanca ä sesi Türkçe \"e\" gibidir; korkma. Türkçede ß gibi bir harf hiç yoktur; bu tamamen yeni bir karakterdir ve sadece küçük harfle yazılır."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Umlaut anlamı değiştirir:','de'=>'Mutter (anne) → Mütter (anneler) · Vater (baba) → Väter (babalar)','tr'=>'Çoğul yaparken umlaut eklenir; harfi atlarsan çoğul kaybolur.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Klavyede umlaut olmadığı için ü yerine u yazmak. \"Tur\" ile \"Tür\" farklı kelimelerdir (die Tür = kapı). Umlaut yazılamıyorsa doğru çözüm ue yazmaktır: Tuer.",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"ß'yi \"uzun sesli ss\" olarak düşün: Straße'de a uzundur, Fluss'ta u kısadır. Bu bir kural değil, kuralı hatırlatan bir kısayoldur.",'c'=>1],
                    ],
                    'vocab' => ['Straße','Tür','Stadt','Mutter','Vater'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'eszett','q'=>'ß harfi hangi durumda kullanılır?','a'=>'Uzun ünlü veya çift ünlüden sonra','opts'=>['Uzun ünlü veya çift ünlüden sonra','Kısa ünlüden sonra','Her zaman kelime sonunda','Sadece özel isimlerde'],'exp'=>'Straße: a uzun → ß. Fluss: u kısa → ss.','vg'=>'eszett-rule'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'umlaut_sounds','q'=>'Klavyende "ü" yoksa doğru yazım hangisidir?','a'=>'ue','opts'=>['ue','u','uu','ui'],'exp'=>'Umlautlar ae, oe, ue olarak yazılır. Sadece harfi atmak kelimeyi bozar.','vg'=>'umlaut-write'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'umlaut_sounds','q'=>'"kapı" kelimesinin Almancasını artikeliyle birlikte yaz.','a'=>'die Tür','alt'=>['die Tuer'],'exp'=>'die Tür – die Türen. Umlaut atlanırsa kelime anlamını kaybeder.','vg'=>'umlaut-write'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'umlaut_sounds','q'=>'Almanca "ä" sesi Türkçedeki hangi sese en yakındır?','a'=>'e','opts'=>['e','a','ı','ö'],'exp'=>'ä sesi Türkçe "e" sesine çok yakındır: Väter ≈ "feter".','vg'=>'umlaut-sound'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'eszett','q'=>'"sokak, cadde" anlamına gelen kelimeyi artikeliyle yaz.','a'=>'die Straße','alt'=>['die Strasse'],'exp'=>'die Straße – die Straßen. Ünlü uzun olduğu için ß kullanılır.','vg'=>'eszett-write'],
                    ],
                ],
                [
                    'slug' => 'a0-ch-sch-sp-st',
                    'title' => 'ch, sch, sp, st',
                    'type' => 'pronunciation',
                    'minutes' => 12,
                    'objective' => 'Almancanın en sık geçen harf birleşimlerini doğru okumak.',
                    'summary' => 'Bu dört birleşim Almanca kelimelerin çok büyük kısmında geçer. Yanlış okursan hiç anlaşılmazsın.',
                    'skills' => ['digraph_ch_sch','digraph_sp_st'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada bazı harfler yan yana gelince tek bir ses olur.\n\nsch = Türkçe \"ş\": Schule (şule) = okul\nsp = kelime başında \"şp\": sprechen (şprehen) = konuşmak\nst = kelime başında \"şt\": Straße (ştrase) = sokak\nch = iki farklı ses verir (aşağıda)"],
                        ['t'=>'rule','h'=>'Kural: ch iki türlüdür','b'=>"1) a, o, u, au'dan sonra: boğazdan gelen sert \"h\" sesi.\n   acht (aht), Buch (buh), auch (auh)\n\n2) i, e, ä, ö, ü, ei, eu ve ünsüzlerden sonra: yumuşak, \"hi\" gibi ince ses.\n   ich (ih), nicht (niht), München (münhın)\n\nAyrıca chs birleşimi \"ks\" okunur: sechs (zeks)."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"ş\" tek harfle yazılır. Almancada üç harf gerekir: sch. Ayrıca Türkçede kelime başındaki \"st\" ve \"sp\" olduğu gibi okunur; Almancada bu birleşimler kelime BAŞINDA \"şt\" ve \"şp\" olur. Kelime ortasında ve sonunda normal okunur: Post (post)."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Aynı kelimede iki kural birden:','de'=>'Ich spreche Deutsch.','tr'=>'Almanca konuşuyorum. — "ih ŞPREHE doyç"'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Straße kelimesini \"strase\" diye okumak. Kelime başında st her zaman \"şt\" olur: \"ŞTRASE\".",'c'=>1],
                    ],
                    'vocab' => ['sprechen','Stadt','Straße','Schwester','sechs'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'digraph_sp_st','q'=>'"Stadt" kelimesi nasıl okunur?','a'=>'ştat','opts'=>['ştat','stat','sıtat','şitat'],'exp'=>'Kelime başındaki st = "şt". Stadt → ŞTAT.','vg'=>'st-start'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'digraph_ch_sch','q'=>'"Schule" kelimesindeki sch hangi sesi verir?','a'=>'ş','opts'=>['ş','sk','s-h','ç'],'exp'=>'sch = tek "ş" sesi. Schule = "şule".','vg'=>'sch-sound'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'digraph_ch_sch','q'=>'"acht" kelimesindeki ch nasıl okunur?','a'=>'Boğazdan gelen sert h','opts'=>['Boğazdan gelen sert h','İnce, hi gibi h','k sesi','ş sesi'],'exp'=>'a, o, u, au harflerinden sonra ch sert okunur: acht = "aht".','vg'=>'ch-hard'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'digraph_ch_sch','q'=>'"ich" kelimesindeki ch nasıl okunur?','a'=>'İnce, hi gibi yumuşak h','opts'=>['İnce, hi gibi yumuşak h','Boğazdan sert h','k sesi','ts sesi'],'exp'=>'i, e, ä, ö, ü seslerinden sonra ch yumuşaktır: ich = "ih".','vg'=>'ch-soft'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'digraph_sp_st','q'=>'Hangi kelimede baştaki sp "şp" okunmaz?','a'=>'Wespe','opts'=>['Wespe','sprechen','Sport','Sprache'],'exp'=>'Kural yalnızca kelime BAŞI içindir. Wespe kelimesinde sp ortadadır, normal okunur.','vg'=>'sp-position'],
                    ],
                ],
                [
                    'slug' => 'a0-diftong',
                    'title' => 'ei, ie, eu, äu',
                    'type' => 'pronunciation',
                    'minutes' => 10,
                    'objective' => 'İki ünlü yan yana geldiğinde hangi sesin çıktığını bilmek.',
                    'summary' => 'ei ve ie karıştırılırsa kelime tamamen değişir. Bu ders yazım hatalarının yarısını önler.',
                    'skills' => ['diphthongs'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"ei = \"ay\" okunur → mein (mayn) = benim\nie = uzun \"ii\" okunur → sieben (ziibın) = yedi\neu = \"oy\" okunur → neun (noyn) = dokuz\näu = \"oy\" okunur → Häuser (hoyzır) = evler\n\nBasit kısayol: İKİNCİ harfi oku, ilkini değil. ei → i sesi gibi \"ay\"; ie → e uzun \"ii\"."],
                        ['t'=>'why','h'=>'Neden önemli?','b'=>"Bu iki birleşim çok yakın yazılır ama tamamen farklı okunur ve farklı kelimeler üretir:\n\ndie (dii) = artikel\nsie (zii) = o/onlar\nsein (zayn) = olmak\n\nYanlış okursan karşındaki seni anlamaz; yanlış yazarsan cümle anlamsız olur."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Aynı cümlede ei ve ie:','de'=>'Sie heißt Marie und sie ist sieben Jahre alt.','tr'=>'Onun adı Marie ve o yedi yaşında. — "zii HAYST marii unt zii ist ZIIBIN yaare alt"'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"ie\" birleşimini \"iye\" diye okumak. ie tek ve uzun bir \"ii\" sesidir: viel = \"fiil\", nicht \"fi-yel\".",'c'=>1],
                    ],
                    'vocab' => ['sieben','neun','vier','Ei'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'diphthongs','q'=>'"mein" kelimesi nasıl okunur?','a'=>'mayn','opts'=>['mayn','miyn','meyin','main (İngilizce gibi)'],'exp'=>'ei = "ay". mein → MAYN.','vg'=>'ei-sound'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'diphthongs','q'=>'"sieben" kelimesi nasıl okunur?','a'=>'ziibın','opts'=>['ziibın','sayben','siyeben','zayben'],'exp'=>'ie = uzun "ii", baştaki s = "z". sieben → ZIIBIN.','vg'=>'ie-sound'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'diphthongs','q'=>'"neun" (dokuz) kelimesindeki eu nasıl okunur?','a'=>'oy','opts'=>['oy','ey','öy','iu'],'exp'=>'eu = "oy". neun → NOYN.','vg'=>'eu-sound'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'diphthongs','q'=>'"yedi" sayısını Almanca yaz.','a'=>'sieben','exp'=>'sieben. ie birleşimini unutma; "siben" yanlıştır.','vg'=>'ie-write'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'diphthongs','q'=>'Hangi kelime "ay" sesiyle okunur?','a'=>'drei','opts'=>['drei','vier','sieben','die'],'exp'=>'drei içinde ei var → "dray". Diğerlerinde ie var → uzun "ii".','vg'=>'ei-vs-ie'],
                    ],
                ],
                [
                    'slug' => 'a0-sessizler',
                    'title' => 'w, v, j, z, r, h ve ünlü uzunluğu',
                    'type' => 'pronunciation',
                    'minutes' => 12,
                    'objective' => 'Türkçe konuşanı en çok yanıltan ünsüzleri doğru çıkarmak ve vurguyu doğru yere koymak.',
                    'summary' => 'Bu ders A0 telaffuz bloğunun son parçasıdır. Bundan sonra kelimeleri doğru okuyabileceksin.',
                    'skills' => ['consonants_wvjzr','vowel_length','word_stress'],
                    'prereq' => ['alphabet'=>85,'diphthongs'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"w → v sesi: Wasser (vasır), wohnen (voonın)\nv → f sesi (Almanca kökenli kelimelerde): Vater (fatır), vier (fiir)\nj → y sesi: ja (ya), Jahr (yaar)\nz → ts sesi: zehn (tseen), Zimmer (tsimır)\ns → ünlüden önce z sesi: sieben (ziibın), Sonne (zonı)\nh → kelime başında nefes sesi (haben); ünlüden sonra sessizdir ve ünlüyü UZATIR: gehen (geeın)\nr → boğaza yakın; kelime sonunda neredeyse \"a\" gibi zayıflar: Vater (fatı-a)"],
                        ['t'=>'explanation','h'=>'Ünlü uzunluğu','b'=>"Almancada ünlüler kısa veya uzun olur ve bu anlamı değiştirir.\n\nUzatan işaretler: çift ünlü (Saal), h (Bahn), tek ünsüz (Tag)\nKısaltan işaret: çift ünsüz (Mutter, kommen, Fluss)\n\nBu yüzden çift ünsüz yazımı önemlidir: \"kommen\" ile \"komen\" aynı okunmaz."],
                        ['t'=>'explanation','h'=>'Vurgu','b'=>"Almanca kelimelerde vurgu genellikle İLK hecededir: ARbeit, LEHrer, WASser.\n\nAyrılabilir fiillerde vurgu ön ektedir: AUFstehen, EINkaufen.\nAyrılmayan ön eklerde vurgu köke gider: verSTEhen, beZAHlen.\n-ieren ile biten fiillerde vurgu sondadır: studIEren, buchstabIEren."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede vurgu genellikle son hecededir (kaLEM, oKUL). Almancada tam tersine çoğunlukla ilk hecededir. Türkçe alışkanlığıyla sonu vurgularsan Almanca kulağa yabancı gelir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Zimmer\" kelimesini \"zimmer\" diye okumak. Z = ts olduğu için doğru okunuş \"TSİMIR\"dir.",'c'=>1],
                    ],
                    'vocab' => ['Woche','Jahr','Zimmer','Wasser','Uhr'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'consonants_wvjzr','q'=>'"Wasser" kelimesi nasıl okunur?','a'=>'vasır','opts'=>['vasır','wasser','fasır','vazır'],'exp'=>'w = v sesi; iki ünsüzden önceki a kısadır.','vg'=>'w-sound'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'consonants_wvjzr','q'=>'"Jahr" kelimesindeki J hangi sesi verir?','a'=>'y','opts'=>['y','j','c','h'],'exp'=>'J = y sesi. Jahr → "YAAR".','vg'=>'j-sound'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'vowel_length','q'=>'Hangi kelimede ünlü UZUN okunur?','a'=>'Bahn','opts'=>['Bahn','Mutter','kommen','Fluss'],'exp'=>'h ünlüyü uzatır: Bahn = "baan". Çift ünsüz ise kısaltır.','vg'=>'vowel-length'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'word_stress','q'=>'"aufstehen" kelimesinde vurgu nerededir?','a'=>'auf hecesinde','opts'=>['auf hecesinde','ste hecesinde','hen hecesinde','Vurgu yoktur'],'exp'=>'Ayrılabilir fiillerde vurgu her zaman ön ektedir: AUFstehen.','vg'=>'stress-separable'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'consonants_wvjzr','q'=>'"sieben" kelimesindeki baştaki s nasıl okunur?','a'=>'z','opts'=>['z','s','ş','ts'],'exp'=>'Ünlüden önce gelen s, "z" okunur: sieben = "ziibın".','vg'=>'s-sound'],
                    ],
                ],
            ],
        ],

        /* ============================================================
         * MODUL 2 - İlk tanışma
         * ============================================================ */
        [
            'slug' => 'a0-m2-tanisma',
            'level' => 'A0',
            'title' => 'İlk Tanışma',
            'description' => 'Selamlaşma, kendini tanıtma, isim ve memleket sorma. Almanya\'daki ilk gününde kullanacağın cümleler.',
            'lessons' => [
                [
                    'slug' => 'a0-selamlasma',
                    'title' => 'Selamlaşma ve Vedalaşma',
                    'type' => 'vocabulary',
                    'minutes' => 12,
                    'objective' => 'Günün saatine ve ortamın resmiyetine göre doğru selamlaşmayı seçmek.',
                    'summary' => 'Almanya\'da yanlış selamlaşma kaba görünür. Bu ders hangi kalıbı ne zaman kullanacağını öğretir.',
                    'skills' => ['greetings'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada selamlaşma iki şeye göre değişir: SAAT ve RESMİYET.\n\nSabah (≈ 11'e kadar): Guten Morgen\nGün içi: Guten Tag\nAkşam: Guten Abend\nHer zaman, yarı samimi: Hallo\n\nVedalaşma:\nResmi: Auf Wiedersehen\nSamimi: Tschüss\nYatmadan önce: Gute Nacht"],
                        ['t'=>'why','h'=>'Neden önemli?','b'=>"Almanya'da iş yerine girerken \"Guten Morgen\" demek beklenen bir davranıştır. Hiçbir şey söylemeden geçmek soğuk ve saygısız algılanır. Bir markete, doktora, komşunun yanına girerken de selam verilir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Gute Nacht\" ile selamlaşmak. Bu kalıp yalnızca gece VEDALAŞIRKEN, yatmadan önce kullanılır. Akşam biriyle karşılaştığında \"Guten Abend\" denir.",'c'=>1],
                        ['t'=>'example','h'=>'Örnek','b'=>'İş yerinde tipik bir sabah:','de'=>'— Guten Morgen, Herr Wagner!\n— Guten Morgen! Wie geht es Ihnen?\n— Danke, gut. Und Ihnen?','tr'=>'— Günaydın, Bay Wagner!\n— Günaydın! Nasılsınız?\n— Teşekkürler, iyiyim. Ya siz?'],
                        ['t'=>'usage','h'=>'Gerçek hayatta kullanım','b'=>"Güney Almanya ve Avusturya'da \"Grüß Gott\" da çok duyulur; anlamı \"Guten Tag\" ile aynıdır. Sana \"Grüß Gott\" denirse aynı şekilde karşılık verebilirsin.",'c'=>1],
                    ],
                    'vocab' => ['Hallo','Guten Morgen','Guten Tag','Guten Abend','Gute Nacht','Tschüss','Auf Wiedersehen','Bis bald','Wie geht es Ihnen?','Mir geht es gut.','danke','bitte'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'greetings','q'=>'Saat 09:00, iş yerine giriyorsun. Ne dersin?','a'=>'Guten Morgen','opts'=>['Guten Morgen','Guten Abend','Gute Nacht','Auf Wiedersehen'],'exp'=>'Sabah saatlerinde Guten Morgen kullanılır.','vg'=>'greeting-time'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'greetings','q'=>'Amirinden resmi biçimde ayrılıyorsun. Ne dersin?','a'=>'Auf Wiedersehen','opts'=>['Auf Wiedersehen','Tschüss','Hallo','Gute Nacht'],'exp'=>'Resmi vedalaşma Auf Wiedersehen\'dir. Tschüss samimi ortamlar içindir.','vg'=>'greeting-formal'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'greetings','q'=>'"Wie geht es Ihnen?" ne demek?','a'=>'Nasılsınız?','opts'=>['Nasılsınız?','Adınız ne?','Nerede oturuyorsunuz?','Kaç yaşındasınız?'],'exp'=>'Resmi biçimidir. Samimi hali: Wie geht es dir?','vg'=>'greeting-question'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'greetings','q'=>'"İyi akşamlar" ifadesini Almanca yaz.','a'=>'Guten Abend','exp'=>'Guten Abend. Büyük harflere dikkat: Abend bir isimdir.','vg'=>'greeting-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'greetings','q'=>'Bir kişi sana teşekkür etti: "Danke!" En doğru karşılık hangisi?','a'=>'Bitte','opts'=>['Bitte','Tschüss','Hallo','Ja'],'exp'=>'bitte hem "lütfen" hem de "rica ederim" anlamına gelir.','vg'=>'greeting-response'],
                    ],
                ],
                [
                    'slug' => 'a0-kendini-tanitma',
                    'title' => 'Kendini Tanıtma',
                    'type' => 'grammar',
                    'minutes' => 14,
                    'objective' => 'Adını, memleketini, oturduğun yeri ve mesleğini söyleyebilmek.',
                    'summary' => 'Dört cümlelik bir tanıtım, Almanya\'daki ilk haftanda defalarca kullanacağın en değerli bloktur.',
                    'skills' => ['self_introduction','asking_name'],
                    'prereq' => ['greetings'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada kendini tanıtırken dört temel cümle vardır:\n\nIch heiße Emre. — Adım Emre.\nIch komme aus der Türkei. — Türkiye'den geliyorum.\nIch wohne in Köln. — Köln'de oturuyorum.\nIch bin Ingenieur. — Mühendisim.\n\nBu dördü bir arada söylendiğinde tam bir tanıtım olur."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"Adım Emre\" derken fiil kullanmayız; \"-dır\" eki bile çoğu zaman düşer. Almancada CÜMLEDE HER ZAMAN FİİL OLMAK ZORUNDADIR.\n\nYanlış: Ich Emre.\nDoğru: Ich heiße Emre. veya Ich bin Emre.\n\nAyrıca Türkçede meslek söylerken \"mühendisim\" deriz; Almancada \"Ich bin Ingenieur\" denir ve meslek isminden ÖNCE artikel KULLANILMAZ."],
                        ['t'=>'rule','h'=>'Kural','b'=>"Meslek söylerken artikel yoktur:\nIch bin Lehrer. (Ich bin ein Lehrer değil.)\n\nÜlke söylerken çoğu ülke artikelsizdir:\nIch komme aus Deutschland.\nAma birkaç ülke artikel alır ve bu değişir:\nIch komme aus der Türkei. (die Türkei → aus der Türkei)\nIch komme aus der Schweiz."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Tam tanıtım:','de'=>'Guten Tag! Ich heiße Ayşe Yılmaz. Ich komme aus der Türkei und wohne jetzt in Köln. Ich bin Krankenschwester.','tr'=>'İyi günler! Adım Ayşe Yılmaz. Türkiye\'den geliyorum ve şimdi Köln\'de oturuyorum. Hemşireyim.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich komme aus die Türkei\" demek. aus edatı Dativ ister, bu yüzden die → der olur: aus der Türkei. Bu konuyu A2'de ayrıntılı işleyeceğiz; şimdilik kalıbı olduğu gibi öğren.",'c'=>1],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Dört cümleyi hep aynı sırayla söyle: AD → ÜLKE → ŞEHİR → MESLEK. Sıralamayı sabitlersen düşünmeden söyleyebilirsin.",'c'=>1],
                    ],
                    'vocab' => ['heißen','kommen','wohnen','sein','Name','Vorname','Nachname','Beruf','Deutschland','Türkei','Freut mich.','Woher kommen Sie?','Wo wohnen Sie?'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'self_introduction','q'=>'"Adım Emre" ifadesinin doğru Almancası hangisi?','a'=>'Ich heiße Emre.','opts'=>['Ich heiße Emre.','Ich Emre.','Mein Emre.','Ich name Emre.'],'exp'=>'Almanca cümlede fiil zorunludur: heißen fiili kullanılır.','vg'=>'intro-name'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'self_introduction','q'=>'"Türkiye\'den geliyorum" nasıl denir?','a'=>'Ich komme aus der Türkei.','opts'=>['Ich komme aus der Türkei.','Ich komme aus die Türkei.','Ich komme von Türkei.','Ich komme aus Türkei.'],'exp'=>'die Türkei artikel alır ve aus edatı Dativ istediği için "aus der Türkei" olur.','vg'=>'intro-country'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'self_introduction','q'=>'Mesleğini söylerken hangisi doğrudur?','a'=>'Ich bin Lehrer.','opts'=>['Ich bin Lehrer.','Ich bin ein Lehrer.','Ich bin der Lehrer.','Ich habe Lehrer.'],'exp'=>'Meslek söylerken artikel kullanılmaz: Ich bin Lehrer.','vg'=>'intro-job'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'self_introduction','q'=>'"Köln\'de oturuyorum" cümlesini Almanca yaz.','a'=>'Ich wohne in Köln.','exp'=>'wohnen = ikamet etmek. Şehir adından önce "in" kullanılır.','vg'=>'intro-city'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'asking_name','q'=>'Tanımadığın birine adını sormak istiyorsun. Hangisi doğru ve kibar?','a'=>'Wie heißen Sie?','opts'=>['Wie heißen Sie?','Wie heißt du?','Was ist du Name?','Wer bist du?'],'exp'=>'Tanımadığın yetişkine "Sie" ile hitap edilir: Wie heißen Sie?','vg'=>'intro-ask'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'self_introduction','q'=>'Kendini tanıt: adın Murat, Türkiye\'densin. İki cümle yaz.','a'=>'Ich heiße Murat. Ich komme aus der Türkei.','alt'=>['Ich heiße Murat und ich komme aus der Türkei.','Ich bin Murat. Ich komme aus der Türkei.'],'exp'=>'İki temel cümle: ad + memleket. Cümle sonuna nokta koymayı unutma.','vg'=>'intro-full'],
                    ],
                ],
                [
                    'slug' => 'a0-ulke-milliyet',
                    'title' => 'Ülkeler, Milliyetler ve Diller',
                    'type' => 'vocabulary',
                    'minutes' => 12,
                    'objective' => 'Ülke, milliyet ve dil adlarını ayırt etmek ve doğru kullanmak.',
                    'summary' => 'Almancada ülke, milliyet ve dil üç ayrı kelimedir. Türkçede çoğu zaman aynıdır; bu ders farkı netleştirir.',
                    'skills' => ['countries_nationalities'],
                    'prereq' => ['self_introduction'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada üç farklı kelime vardır:\n\nÜLKE: die Türkei, Deutschland\nMİLLİYET: der Türke / die Türkin, der Deutsche / die Deutsche\nDİL: Türkisch, Deutsch\n\nÜçü de büyük harfle yazılır çünkü hepsi isimdir."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"Türk\" hem milliyet hem sıfat olabilir, \"Türkçe\" dildir. Almancada milliyetin ERKEK ve KADIN biçimi ayrıdır:\n\nEr ist Türke. (erkek)\nSie ist Türkin. (kadın)\n\nBu ayrımı yapmazsan cümle yanlış olur."],
                        ['t'=>'rule','h'=>'Kural','b'=>"Ülkeye giderken/gelirken:\nartikelsiz ülke → nach / aus\n  Ich fahre nach Deutschland. Ich komme aus Deutschland.\nartikelli ülke → in die / aus der\n  Ich fahre in die Türkei. Ich komme aus der Türkei.\n\nDil için: Ich spreche Deutsch. (artikelsiz)"],
                        ['t'=>'example','h'=>'Örnek','b'=>'Üçü bir arada:','de'=>'Ich komme aus der Türkei. Ich bin Türkin. Ich spreche Türkisch und ein bisschen Deutsch.','tr'=>'Türkiye\'den geliyorum. Türk\'üm. Türkçe ve biraz Almanca konuşuyorum.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Milliyeti dil zannetmek: \"Ich spreche Türke\" yanlıştır. Doğrusu \"Ich spreche Türkisch\".",'c'=>1],
                    ],
                    'vocab' => ['Land','Stadt','Deutschland','Türkei','Österreich','Schweiz','Deutsch','Türkisch','Englisch','Türke','Türkin','Deutsche','Deutscher'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'countries_nationalities','q'=>'Bir kadın milliyetini söylüyor. Hangisi doğru?','a'=>'Ich bin Türkin.','opts'=>['Ich bin Türkin.','Ich bin Türke.','Ich bin Türkisch.','Ich bin die Türkei.'],'exp'=>'Kadın biçimi -in eki alır: Türke → Türkin.','vg'=>'nat-gender'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'countries_nationalities','q'=>'"Almanca konuşuyorum" nasıl denir?','a'=>'Ich spreche Deutsch.','opts'=>['Ich spreche Deutsch.','Ich spreche Deutsche.','Ich spreche Deutschland.','Ich spreche der Deutsch.'],'exp'=>'Dil adı artikelsiz kullanılır: Deutsch.','vg'=>'lang-use'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'countries_nationalities','q'=>'"Türkiye\'ye gidiyorum" nasıl denir?','a'=>'Ich fahre in die Türkei.','opts'=>['Ich fahre in die Türkei.','Ich fahre nach die Türkei.','Ich fahre nach Türkei.','Ich fahre zu Türkei.'],'exp'=>'Artikelli ülkelerde "in die + ülke" kullanılır. Artikelsiz ülkelerde "nach".','vg'=>'country-direction'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'countries_nationalities','q'=>'"Almanya\'da çalışıyorum" cümlesini Almanca yaz.','a'=>'Ich arbeite in Deutschland.','exp'=>'Deutschland özel isimdir, büyük harfle yazılır ve artikel almaz.','vg'=>'country-write'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'countries_nationalities','q'=>'Hangisi bir DİL adıdır?','a'=>'Englisch','opts'=>['Englisch','England','Engländer','Englands'],'exp'=>'Englisch = İngilizce (dil). England = ülke, Engländer = milliyet.','vg'=>'lang-vs-country'],
                    ],
                ],
                [
                    'slug' => 'a0-sie-du',
                    'title' => 'Sie mi du mu?',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'Resmi ve samimi hitabı doğru seçmek ve fiili buna göre çekmek.',
                    'summary' => 'Almanya\'da yanlış hitap iş görüşmesini bile etkileyebilir. Bu ders kültürel olarak da kritiktir.',
                    'skills' => ['sie_du'],
                    'prereq' => ['self_introduction'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almancada \"sen\" için iki ayrı biçim vardır:\n\ndu → samimi: arkadaş, aile, çocuklar, yakın iş arkadaşları\nSie → resmi: tanımadığın yetişkinler, müşteriler, amirler, memurlar, doktorlar\n\nSie her zaman BÜYÜK harfle yazılır ve çoğul fiil alır."],
                        ['t'=>'rule','h'=>'Kural','b'=>"Fiil çekimi değişir:\n\nWie heißt du? → Adın ne? (samimi)\nWie heißen Sie? → Adınız ne? (resmi)\n\nWoher kommst du? / Woher kommen Sie?\nWo wohnst du? / Wo wohnen Sie?\n\nSie ile fiil her zaman mastar biçimindedir: kommen, wohnen, heißen."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"siz\" kullanımı esnektir; yaşça büyük birine \"sen\" demek bazen kabul edilir. Almanya'da ise kural nettir: TANIMADIĞIN HER YETİŞKİNE \"Sie\" denir. Karşı taraf \"Wir können uns duzen\" (birbirimize sen diyebiliriz) demeden \"du\"ya geçilmez."],
                        ['t'=>'usage','h'=>'Gerçek hayatta kullanım','b'=>"İş yerinde bazı Alman şirketleri herkesin \"du\" kullandığı bir kültür benimser. İlk gün amirin sana \"Ich bin Thomas, wir sagen hier alle du\" derse artık \"du\" kullanabilirsin. Emin değilsen \"Sie\" ile başla; bu hiçbir zaman kaba görünmez.",'c'=>1],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Sie kullanırken fiili tekil çekmek: \"Wie heißt Sie?\" yanlıştır. Doğrusu \"Wie heißen Sie?\"dir.",'c'=>1],
                    ],
                    'vocab' => ['Herr','Frau','Wie geht es Ihnen?','Wie geht\'s?','Woher kommen Sie?'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'sie_du','q'=>'İş görüşmesindesin. İK sorumlusuna nasıl hitap edersin?','a'=>'Sie','opts'=>['Sie','du','ihr','es'],'exp'=>'Tanımadığın yetişkinle ve resmi ortamda her zaman Sie kullanılır.','vg'=>'sieddu-choice'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'sie_du','q'=>'"Nerede oturuyorsunuz?" (resmi) nasıl denir?','a'=>'Wo wohnen Sie?','opts'=>['Wo wohnen Sie?','Wo wohnst Sie?','Wo wohnt Sie?','Wo wohnen du?'],'exp'=>'Sie ile fiil mastar biçimindedir: wohnen.','vg'=>'siedu-conjugate'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'sie_du','q'=>'Yakın arkadaşına "Nereden geliyorsun?" nasıl sorarsın?','a'=>'Woher kommst du?','opts'=>['Woher kommst du?','Woher kommen Sie?','Woher kommt du?','Woher kommen du?'],'exp'=>'du ile fiil -st eki alır: du kommst.','vg'=>'siedu-conjugate'],
                        ['type'=>'sentence_correction','mode'=>'production','skill'=>'sie_du','q'=>'Bu cümledeki hatayı düzelt: "Wie heißt Sie?"','a'=>'Wie heißen Sie?','exp'=>'Sie ile fiil çoğul/mastar biçimindedir: heißen.','vg'=>'siedu-correct'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'sie_du','q'=>'Almanya\'da bir kişiye "du" demeye ne zaman geçilir?','a'=>'Karşı taraf teklif ettiğinde','opts'=>['Karşı taraf teklif ettiğinde','İkinci görüşmede otomatik olarak','Yaş küçükse hemen','Aynı işte çalışıyorsanız hemen'],'exp'=>'Genellikle yaşça büyük veya kıdemli olan kişi "du"yu teklif eder. Sen kendiliğinden geçmezsin.','vg'=>'siedu-culture'],
                    ],
                ],
            ],
        ],

        /* ============================================================
         * MODUL 3 - Sayılar ve iletişim bilgileri
         * ============================================================ */
        [
            'slug' => 'a0-m3-sayilar',
            'level' => 'A0',
            'title' => 'Sayılar ve İletişim Bilgileri',
            'description' => 'Sayı söyleme, telefon numarası, adres ve posta kodu. Resmi kurumlarda ilk sorulacak şeyler.',
            'lessons' => [
                [
                    'slug' => 'a0-sayilar-0-20',
                    'title' => 'Sayılar 0-20',
                    'type' => 'vocabulary',
                    'minutes' => 10,
                    'objective' => '0-20 arası sayıları duyduğunda anlamak ve söyleyebilmek.',
                    'summary' => 'Fiyat, saat, peron, kapı numarası: günlük hayatın her yerinde sayı var.',
                    'skills' => ['numbers_0_20'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'table','h'=>'0-12','b'=>"0 null · 1 eins · 2 zwei · 3 drei · 4 vier · 5 fünf · 6 sechs · 7 sieben · 8 acht · 9 neun · 10 zehn · 11 elf · 12 zwölf"],
                        ['t'=>'rule','h'=>'13-19 kuralı','b'=>"13'ten 19'a kadar: birler basamağı + zehn\n\n13 dreizehn · 14 vierzehn · 15 fünfzehn · 16 sechzehn · 17 siebzehn · 18 achtzehn · 19 neunzehn\n\nİki istisna var:\n16 = sechzehn (sechszehn değil, s düşer)\n17 = siebzehn (siebenzehn değil, en düşer)"],
                        ['t'=>'explanation','h'=>'Telefonda "zwei" sorunu','b'=>"Telefonda \"zwei\" (2) ile \"drei\" (3) karışabildiği için Almanlar 2 yerine sık sık \"zwo\" der. Bir memur sana \"zwo\" derse bu 2 demektir."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"sechs\" kelimesini \"seks\" yerine \"zeks\" okumamak. Baştaki s ünlüden önce z okunur: ZEKS.",'c'=>1],
                    ],
                    'vocab' => ['null','eins','zwei','drei','vier','fünf','sechs','sieben','acht','neun','zehn','elf','zwölf','dreizehn'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'numbers_0_20','q'=>'"acht" hangi sayıdır?','a'=>'8','opts'=>['8','4','18','80'],'exp'=>'acht = 8. achtzehn = 18.','vg'=>'num-recognize'],
                        ['type'=>'text_input','mode'=>'recall','skill'=>'numbers_0_20','q'=>'12 sayısını Almanca yaz.','a'=>'zwölf','exp'=>'zwölf. Umlaut ö yazılmalı; "zwolf" yanlıştır.','vg'=>'num-write'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'numbers_0_20','q'=>'16 sayısı Almanca nasıl yazılır?','a'=>'sechzehn','opts'=>['sechzehn','sechszehn','sechsehn','sechzen'],'exp'=>'16\'da sechs\'in s harfi düşer: sechzehn.','vg'=>'num-irregular'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'numbers_0_20','q'=>'17 sayısı Almanca nasıl yazılır?','a'=>'siebzehn','opts'=>['siebzehn','siebenzehn','siebzen','siebenzen'],'exp'=>'17\'de sieben\'in -en kısmı düşer: siebzehn.','vg'=>'num-irregular'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'numbers_0_20','q'=>'5 sayısını Almanca yaz.','a'=>'fünf','alt'=>['fuenf'],'exp'=>'fünf. Umlaut ü zorunludur.','vg'=>'num-write'],
                    ],
                ],
                [
                    'slug' => 'a0-sayilar-21-100',
                    'title' => 'Sayılar 21-100 ve Ters Okuma',
                    'type' => 'grammar',
                    'minutes' => 12,
                    'objective' => 'İki basamaklı sayıları Almanca mantığıyla kurmak ve duyduğunda doğru anlamak.',
                    'summary' => 'Almanca sayı okuma Türkçenin tersidir. Bu ders anlaşılmadan fiyat ve telefon numarası anlaşılmaz.',
                    'skills' => ['numbers_21_100'],
                    'prereq' => ['numbers_0_20'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural: birler önce okunur','b'=>"Almancada iki basamaklı sayılarda ÖNCE BİRLER, sonra onlar okunur ve arada \"und\" olur.\n\n21 = ein-und-zwanzig (bir ve yirmi)\n34 = vier-und-dreißig (dört ve otuz)\n67 = sieben-und-sechzig\n\nÜçü de bitişik yazılır: einundzwanzig."],
                        ['t'=>'why','h'=>'Neden önemli?','b'=>"Bir kasiyer \"vierundzwanzig Euro\" dediğinde 24 euro demektir, 42 değil. Bu tersliği alışkanlık haline getirmezsen fiyatları ve telefon numaralarını sürekli yanlış anlarsın."],
                        ['t'=>'table','h'=>'Onluklar','b'=>"20 zwanzig · 30 dreißig · 40 vierzig · 50 fünfzig · 60 sechzig · 70 siebzig · 80 achtzig · 90 neunzig · 100 hundert\n\nDikkat: 30 = dreißig (ß ile, dreizig değil). 60 = sechzig, 70 = siebzig (kısalma var)."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"yirmi bir\" deriz: önce onlar, sonra birler. Almancada tam tersidir. Bu, Türkçe konuşanların Almancada en uzun süre hata yaptığı konulardan biridir. Duyduğun sayıyı beynin ters çevirmeye alışmalı."],
                        ['t'=>'memory_tip','h'=>'Kolay hatırlama','b'=>"Almanca sayıyı duyunca aklından SONA doğru dinle: \"...zwanzig\" duyduğun anda sayının 20'li olduğunu bil, sonra baştaki birler basamağını ekle. Bu bir kural değil, dinlemeyi kolaylaştıran bir yöntemdir.",'c'=>1],
                        ['t'=>'example','h'=>'Örnek','b'=>'Fiyat söyleme:','de'=>'Das kostet siebenundvierzig Euro fünfzig.','tr'=>'Bu 47 euro 50 sent. (yedi-ve-kırk)'],
                    ],
                    'vocab' => ['zwanzig','einundzwanzig','dreißig','vierzig','fünfzig','hundert','Euro','Preis'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'numbers_21_100','q'=>'"vierundzwanzig" hangi sayıdır?','a'=>'24','opts'=>['24','42','4','20'],'exp'=>'vier (4) + und + zwanzig (20) = 24. Birler önce okunur.','vg'=>'num2-recognize'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'numbers_21_100','q'=>'"zweiundsechzig" hangi sayıdır?','a'=>'62','opts'=>['62','26','12','72'],'exp'=>'zwei (2) + und + sechzig (60) = 62.','vg'=>'num2-recognize'],
                        ['type'=>'text_input','mode'=>'recall','skill'=>'numbers_21_100','q'=>'35 sayısını Almanca yaz (bitişik).','a'=>'fünfunddreißig','alt'=>['fuenfunddreissig','fünfunddreissig'],'exp'=>'fünf + und + dreißig, hepsi bitişik: fünfunddreißig.','vg'=>'num2-write'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'numbers_21_100','q'=>'30 sayısının doğru yazımı hangisidir?','a'=>'dreißig','opts'=>['dreißig','dreizig','dreissich','dreizehn'],'exp'=>'30 = dreißig, ß ile yazılır. dreizehn ise 13\'tür.','vg'=>'num2-spelling'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'numbers_21_100','q'=>'Kasiyer "achtundvierzig Euro" dedi. Ne kadar ödemelisin?','a'=>'48 euro','opts'=>['48 euro','84 euro','8 euro','40 euro'],'exp'=>'acht (8) + und + vierzig (40) = 48.','vg'=>'num2-apply'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'numbers_21_100','q'=>'"Bu 21 euro" cümlesini Almanca yaz.','a'=>'Das kostet einundzwanzig Euro.','alt'=>['Das sind einundzwanzig Euro.','Das kostet 21 Euro.'],'exp'=>'kosten fiili fiyat için kullanılır. 21 = einundzwanzig.','vg'=>'num2-produce'],
                    ],
                ],
                [
                    'slug' => 'a0-iletisim-bilgileri',
                    'title' => 'Telefon, Adres ve Posta Kodu',
                    'type' => 'daily_life',
                    'minutes' => 12,
                    'objective' => 'Telefon numaranı, adresini ve posta kodunu Almanca söyleyebilmek.',
                    'summary' => 'Bürgeramt, doktor, işveren: hepsi bu üç bilgiyi sorar. Doğru söylemek zorundasın.',
                    'skills' => ['phone_numbers','address_info'],
                    'prereq' => ['numbers_21_100'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural: telefon numarası tek tek okunur','b'=>"Almanca telefon numaraları genellikle RAKAM RAKAM okunur:\n\n0176 3345 812 → null-eins-sieben-sechs / drei-drei-vier-fünf / acht-eins-zwei\n\nBazen ikişerli gruplanır (dreiunddreißig = 33) ama emin değilsen tek tek söyle; herkes anlar."],
                        ['t'=>'explanation','h'=>'Adres sırası','b'=>"Alman adresinde sıralama Türkçenin tersidir: ÖNCE SOKAK, SONRA NUMARA.\n\nHauptstraße 12\n50667 Köln\n\nİlk satır: sokak adı + bina numarası\nİkinci satır: posta kodu (PLZ, 5 hane) + şehir"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede \"12 numaralı Hauptstraße\" gibi numarayı önce söyleyebiliriz; Almancada numara HER ZAMAN sokak adından sonra gelir. Ayrıca Alman posta kodu 5 hanedir ve şehirden ÖNCE yazılır."],
                        ['t'=>'example','h'=>'Örnek','b'=>'Bürgeramt\'ta tipik bir diyalog:','de'=>'— Wie ist Ihre Adresse?\n— Hauptstraße zwölf, fünfzig sechs sechs sieben Köln.\n— Und Ihre Telefonnummer?\n— null eins sieben sechs, drei drei vier fünf, acht eins zwei.','tr'=>'— Adresiniz nedir?\n— Hauptstraße 12, 50667 Köln.\n— Telefon numaranız?\n— 0176 3345 812.'],
                        ['t'=>'usage','h'=>'Gerçek hayatta kullanım','b'=>"Posta kodu 5 hanedir ve söylerken genellikle rakam rakam okunur. Adını yazdırırken \"Können Sie das buchstabieren?\" diye sorulursa alfabe dersindeki harf adlarını kullan.",'c'=>1],
                    ],
                    'vocab' => ['Telefonnummer','Handy','Adresse','Straße','Postleitzahl','E-Mail'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'address_info','q'=>'Alman adres yazımında doğru sıra hangisidir?','a'=>'Sokak adı, numara, posta kodu, şehir','opts'=>['Sokak adı, numara, posta kodu, şehir','Numara, sokak adı, şehir, posta kodu','Şehir, posta kodu, sokak adı, numara','Posta kodu, şehir, numara, sokak adı'],'exp'=>'Hauptstraße 12 / 50667 Köln biçimi standarttır.','vg'=>'address-order'],
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'address_info','q'=>'Alman posta kodu kaç hanedir?','a'=>'5','opts'=>['5','4','6','3'],'exp'=>'Alman Postleitzahl (PLZ) 5 hanedir: 50667.','vg'=>'address-plz'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'phone_numbers','q'=>'Telefonda "zwo" duydun. Bu hangi sayıdır?','a'=>'2','opts'=>['2','0','8','12'],'exp'=>'Telefonda zwei ile drei karışmasın diye 2 yerine "zwo" denir.','vg'=>'phone-zwo'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'address_info','q'=>'"Telefon numaranız nedir?" cümlesini Almanca yaz (resmi).','a'=>'Wie ist Ihre Telefonnummer?','alt'=>['Wie lautet Ihre Telefonnummer?'],'exp'=>'Resmi biçimde "Ihre" büyük harfle yazılır.','vg'=>'phone-ask'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'address_info','q'=>'Memur "Wie ist Ihre Postleitzahl?" diye sordu. Ne cevaplarsın?','a'=>'5 haneli posta kodunu söylerim','opts'=>['5 haneli posta kodunu söylerim','Telefon numaramı söylerim','Adımı harf harf söylerim','Doğum tarihimi söylerim'],'exp'=>'Postleitzahl = posta kodu.','vg'=>'address-apply'],
                    ],
                ],
            ],
        ],

        /* ============================================================
         * MODUL 4 - Meslek ve temel kalıplar
         * ============================================================ */
        [
            'slug' => 'a0-m4-meslek-kaliplar',
            'level' => 'A0',
            'title' => 'Meslek ve Hayatta Kalma Kalıpları',
            'description' => 'Mesleğini söylemek ve anlamadığında ne diyeceğini bilmek. Almanya\'nın ilk haftası için can simidi.',
            'lessons' => [
                [
                    'slug' => 'a0-meslekler',
                    'title' => 'Meslekler',
                    'type' => 'vocabulary',
                    'minutes' => 12,
                    'objective' => 'Mesleğini söylemek, karşındakinin mesleğini sormak ve anlamak.',
                    'summary' => 'Almanya\'da tanışmanın ikinci cümlesi neredeyse her zaman meslek üzerinedir.',
                    'skills' => ['professions'],
                    'prereq' => ['self_introduction'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural: kadın biçimi -in alır','b'=>"Çoğu meslekte kadın biçimi -in ekiyle yapılır:\n\nLehrer → Lehrerin\nArzt → Ärztin (umlaut da gelir)\nVerkäufer → Verkäuferin\nIngenieur → Ingenieurin\n\nÇoğulda -innen olur: die Lehrerinnen."],
                        ['t'=>'explanation','h'=>'Meslek sorma','b'=>"İki standart soru vardır:\n\nWas sind Sie von Beruf? — Mesleğiniz nedir?\nWas machen Sie beruflich? — Ne iş yapıyorsunuz?\n\nCevap artikelsiz verilir: Ich bin Ingenieur."],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede meslek isimlerinin cinsiyeti yoktur: \"öğretmen\" hem kadın hem erkek için kullanılır. Almancada iki ayrı kelime vardır ve yanlış kullanmak dikkat çeker."],
                        ['t'=>'example','h'=>'Örnek','b'=>'İş yerinde tanışma:','de'=>'— Was sind Sie von Beruf?\n— Ich bin Elektriker. Und Sie?\n— Ich bin Ingenieurin bei einer Firma in Köln.','tr'=>'— Mesleğiniz nedir?\n— Elektrikçiyim. Ya siz?\n— Köln\'de bir firmada mühendisim.'],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"\"Ich bin ein Lehrer\" demek. Meslek söylerken artikel KULLANILMAZ: Ich bin Lehrer.",'c'=>1],
                    ],
                    'vocab' => ['Beruf','Arbeit','Lehrer','Lehrerin','Arzt','Ärztin','Ingenieur','Verkäufer','Koch','Fahrer','Student','Krankenschwester','Arbeiter','Firma'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'recall','skill'=>'professions','q'=>'"Arzt" mesleğinin kadın biçimi hangisidir?','a'=>'Ärztin','opts'=>['Ärztin','Arztin','Arztfrau','Arzterin'],'exp'=>'Arzt → Ärztin: hem -in eki hem umlaut gelir.','vg'=>'prof-female'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'professions','q'=>'"Mesleğiniz nedir?" nasıl sorulur?','a'=>'Was sind Sie von Beruf?','opts'=>['Was sind Sie von Beruf?','Wie ist Ihr Beruf machen?','Wo arbeiten Beruf?','Wer sind Sie Beruf?'],'exp'=>'Standart kalıp: Was sind Sie von Beruf?','vg'=>'prof-ask'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'professions','q'=>'Kadınsın ve öğretmensin. Mesleğini bir cümleyle yaz.','a'=>'Ich bin Lehrerin.','exp'=>'Kadın biçimi Lehrerin; artikel kullanılmaz.','vg'=>'prof-produce'],
                        ['type'=>'article','mode'=>'recall','skill'=>'professions','q'=>'"Firma" kelimesinin artikeli nedir?','a'=>'die','opts'=>['die','der','das'],'exp'=>'die Firma – die Firmen.','vg'=>'prof-article'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'professions','q'=>'Hangi cümle doğrudur?','a'=>'Ich bin Krankenschwester.','opts'=>['Ich bin Krankenschwester.','Ich bin eine Krankenschwester.','Ich habe Krankenschwester.','Ich bin die Krankenschwester Beruf.'],'exp'=>'Meslek artikelsiz söylenir.','vg'=>'prof-noarticle'],
                    ],
                ],
                [
                    'slug' => 'a0-hayatta-kalma',
                    'title' => 'Anlamadığında Ne Diyeceksin?',
                    'type' => 'daily_life',
                    'minutes' => 12,
                    'objective' => 'Anlamadığını kibarca söylemek, tekrar veya yavaşlatma istemek.',
                    'summary' => 'Bu ders A0\'ın en pratik dersidir. Bu beş cümle Almanya\'daki ilk ayını kurtarır.',
                    'skills' => ['basic_phrases'],
                    'prereq' => ['greetings'=>85],
                    'sections' => [
                        ['t'=>'explanation','h'=>'Bu nedir?','b'=>"Almanya'da hiç kimse senden mükemmel Almanca beklemiyor. Beklenen şey, anlamadığını NET ve KİBAR biçimde söylemendir. Sessiz kalmak ya da anlamış gibi kafa sallamak en büyük hatadır; işte, doktorda ve resmi kurumlarda ciddi sorunlara yol açar."],
                        ['t'=>'rule','h'=>'Beş temel cümle','b'=>"1. Entschuldigung, ich verstehe nicht. — Affedersiniz, anlamıyorum.\n2. Können Sie das bitte wiederholen? — Bunu tekrar eder misiniz?\n3. Können Sie bitte langsamer sprechen? — Daha yavaş konuşabilir misiniz?\n4. Wie bitte? — Efendim?\n5. Ich spreche nur wenig Deutsch. — Sadece biraz Almanca konuşuyorum."],
                        ['t'=>'why','h'=>'Neden bu kadar önemli?','b'=>"Bir iş talimatını anlamadan \"ja\" demek, iş güvenliği açısından tehlikeli olabilir. Doktorda ilaç dozunu yanlış anlamak ciddi sonuç doğurur. \"Anlamadım\" demek zayıflık değil, profesyonellik göstergesidir."],
                        ['t'=>'usage','h'=>'Gerçek hayatta kullanım','b'=>"Bir şeyi yazılı istemek de çok işe yarar:\nKönnen Sie das bitte aufschreiben? — Bunu yazabilir misiniz?\nBu cümle özellikle adres, tarih ve rakam alırken hayat kurtarır.",'c'=>1],
                        ['t'=>'example','h'=>'Örnek','b'=>'İş yerinde:','de'=>'— Sie müssen das Formular bis Freitag einreichen.\n— Entschuldigung, ich verstehe nicht. Können Sie bitte langsamer sprechen?\n— Natürlich. Das For-mu-lar. Bis Frei-tag.','tr'=>'— Bu formu cumaya kadar teslim etmelisiniz.\n— Affedersiniz, anlamıyorum. Daha yavaş konuşabilir misiniz?\n— Tabii ki. For-mu-lar. Cu-ma-ya kadar.'],
                    ],
                    'vocab' => ['Ich verstehe nicht.','Können Sie bitte langsamer sprechen?','Wie bitte?','Ich spreche nur wenig Deutsch.','Entschuldigung','wiederholen','verstehen'],
                    'exercises' => [
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'basic_phrases','q'=>'Amirin çok hızlı konuşuyor ve anlamıyorsun. En doğru tepki hangisi?','a'=>'Können Sie bitte langsamer sprechen?','opts'=>['Können Sie bitte langsamer sprechen?','Ja, ja, alles klar.','Auf Wiedersehen.','Ich bin müde.'],'exp'=>'Anlamadan onaylamak yerine yavaşlatmasını istemek doğru davranıştır.','vg'=>'survival-apply'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'basic_phrases','q'=>'"Wie bitte?" ne anlama gelir?','a'=>'Efendim? / Pardon?','opts'=>['Efendim? / Pardon?','Lütfen buyurun.','Ne kadar?','Rica ederim.'],'exp'=>'Duyamadığında veya anlamadığında kullanılan kısa kalıptır.','vg'=>'survival-meaning'],
                        ['type'=>'translation_tr_de','mode'=>'production','skill'=>'basic_phrases','q'=>'"Anlamıyorum" cümlesini Almanca yaz.','a'=>'Ich verstehe nicht.','exp'=>'verstehen fiili + nicht. Fiil ikinci sırada, nicht sonda.','vg'=>'survival-produce'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'basic_phrases','q'=>'Doktor sana ilaç dozunu söyledi ama emin değilsin. En güvenli davranış hangisi?','a'=>'Können Sie das bitte aufschreiben?','opts'=>['Können Sie das bitte aufschreiben?','Ja, danke.','Auf Wiedersehen.','Ich bin gesund.'],'exp'=>'Kritik bilgiyi yazılı istemek en güvenli yoldur.','vg'=>'survival-safety'],
                        ['type'=>'text_input','mode'=>'production','skill'=>'basic_phrases','q'=>'"Sadece biraz Almanca konuşuyorum" cümlesini yaz.','a'=>'Ich spreche nur wenig Deutsch.','alt'=>['Ich spreche nur ein bisschen Deutsch.'],'exp'=>'Bu cümle karşındakini otomatik olarak yavaşlatır.','vg'=>'survival-produce'],
                    ],
                ],
                [
                    'slug' => 'a0-isim-buyuk-harf',
                    'title' => 'Almancada İsimler Büyük Harfle Yazılır',
                    'type' => 'grammar',
                    'minutes' => 10,
                    'objective' => 'İsimleri tanımak ve her zaman büyük harfle yazmak.',
                    'summary' => 'Bu kural Almancaya özgüdür ve yazım hatalarının en büyük kaynağıdır.',
                    'skills' => ['noun_capitalization'],
                    'prereq' => ['alphabet'=>85],
                    'sections' => [
                        ['t'=>'rule','h'=>'Kural','b'=>"Almancada BÜTÜN isimler, cümlenin neresinde olursa olsun, büyük harfle yazılır.\n\nIch trinke Kaffee. (Kaffee = isim)\nDer Tisch ist neu. (Tisch = isim)\nIch arbeite in Deutschland. (Deutschland = isim)\n\nFiiller, sıfatlar ve edatlar küçük harfle yazılır: trinken, neu, in."],
                        ['t'=>'why','h'=>'Neden böyle?','b'=>"Büyük harf, okuyucunun cümledeki ismi anında görmesini sağlar. Almanca cümleler uzun olabildiği için bu görsel işaret okumayı kolaylaştırır. Ayrıca aynı yazılan iki kelimeyi ayırır:\n\ndas Essen (yemek) — essen (yemek yemek)\nder Morgen (sabah) — morgen (yarın)"],
                        ['t'=>'tr_contrast','h'=>'Türkçeden farkı','b'=>"Türkçede yalnızca ÖZEL isimler büyük harfle başlar (Ankara, Ayşe). Almancada ise HER isim büyük harfle başlar: masa, su, iş, sabah — hepsi Tisch, Wasser, Arbeit, Morgen olur."],
                        ['t'=>'how_recognize','h'=>'Nasıl anlarsın?','b'=>"Bir kelimenin önüne der / die / das koyabiliyorsan o kelime isimdir ve büyük harfle yazılır.\n\nder Tisch ✓ isim\ndie Arbeit ✓ isim\n\"der arbeiten\" ✗ olmaz → arbeiten fiildir, küçük harf."],
                        ['t'=>'common_mistake','h'=>'En sık yapılan hata','b'=>"Cümle ortasındaki ismi küçük yazmak: \"Ich arbeite in deutschland.\" Doğrusu \"Ich arbeite in Deutschland.\"dır. Bu hata Almanya'da yazılan bir e-postada hemen fark edilir.",'c'=>1],
                    ],
                    'vocab' => ['Wort','Frage','Antwort','Arbeit','Tag'],
                    'exercises' => [
                        ['type'=>'sentence_correction','mode'=>'spelling','skill'=>'noun_capitalization','q'=>'Bu cümledeki hatayı düzelt: "Ich arbeite in deutschland."','a'=>'Ich arbeite in Deutschland.','exp'=>'Deutschland bir isimdir (üstelik özel isim) ve büyük harfle yazılır.','vg'=>'cap-correct'],
                        ['type'=>'sentence_correction','mode'=>'spelling','skill'=>'noun_capitalization','q'=>'Bu cümledeki hatayı düzelt: "Der tisch ist neu."','a'=>'Der Tisch ist neu.','exp'=>'Tisch bir isimdir, büyük harfle yazılır. neu bir sıfattır, küçük kalır.','vg'=>'cap-correct'],
                        ['type'=>'multiple_choice','mode'=>'recognition','skill'=>'noun_capitalization','q'=>'Hangi cümle doğru yazılmıştır?','a'=>'Ich trinke Kaffee und Wasser.','opts'=>['Ich trinke Kaffee und Wasser.','Ich Trinke kaffee und wasser.','ich trinke Kaffee und Wasser.','Ich trinke kaffee und Wasser.'],'exp'=>'Kaffee ve Wasser isimdir (büyük), trinke fiildir (küçük), cümle başı büyük.','vg'=>'cap-choose'],
                        ['type'=>'multiple_choice','mode'=>'application','skill'=>'noun_capitalization','q'=>'"morgen" ile "Morgen" arasındaki fark nedir?','a'=>'morgen = yarın, Morgen = sabah','opts'=>['morgen = yarın, Morgen = sabah','İkisi de aynıdır','morgen = sabah, Morgen = yarın','Morgen sadece cümle başında kullanılır'],'exp'=>'Büyük harf burada anlamı belirler: der Morgen (sabah), morgen (yarın).','vg'=>'cap-meaning'],
                        ['type'=>'text_input','mode'=>'spelling','skill'=>'noun_capitalization','q'=>'"Bir sorum var" cümlesini doğru büyük harflerle yaz.','a'=>'Ich habe eine Frage.','exp'=>'Frage bir isimdir, büyük harfle yazılır.','vg'=>'cap-produce'],
                    ],
                ],
            ],
        ],
    ];
}
