<?php
/**
 * AlmancaPro - A1 kelime hazinesi.
 */
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME'])
    && basename((string)$_SERVER['SCRIPT_FILENAME']) === basename(__FILE__)
    && PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

function almancapro_vocab_a1(): array
{
    return [
        /* --- Zamirler ve soru kelimeleri --- */
        ['g'=>'ich','tr'=>'ben','pos'=>'pronoun','top'=>'pronomen','ex'=>'Ich bin müde.','ext'=>'Yorgunum.'],
        ['g'=>'du','tr'=>'sen','pos'=>'pronoun','top'=>'pronomen','ex'=>'Du bist mein Freund.','ext'=>'Sen benim arkadaşımsın.','note'=>'Samimi hitap. Tanımadığın yetişkine "Sie" denir.'],
        ['g'=>'er','tr'=>'o (erkek)','pos'=>'pronoun','top'=>'pronomen','ex'=>'Er arbeitet in Berlin.','ext'=>'O Berlin\'de çalışıyor.'],
        ['g'=>'sie','tr'=>'o (kadın); onlar','pos'=>'pronoun','top'=>'pronomen','ex'=>'Sie kommt aus Ankara.','ext'=>'O Ankara\'dan geliyor.','sim'=>'sie (o kadın) tekil fiil, sie (onlar) çoğul fiil alır; Sie (siz) büyük harfle yazılır.'],
        ['g'=>'es','tr'=>'o (nötr)','pos'=>'pronoun','top'=>'pronomen','ex'=>'Es ist kalt.','ext'=>'Hava soğuk.','note'=>'Hava ve saat cümlelerinde özne olarak kullanılır.'],
        ['g'=>'wir','tr'=>'biz','pos'=>'pronoun','top'=>'pronomen','ex'=>'Wir lernen Deutsch.','ext'=>'Biz Almanca öğreniyoruz.'],
        ['g'=>'ihr','tr'=>'siz (samimi çoğul)','pos'=>'pronoun','top'=>'pronomen','ex'=>'Ihr seid pünktlich.','ext'=>'Siz dakiksiniz.'],
        ['g'=>'wer','tr'=>'kim','pos'=>'pronoun','top'=>'w_fragen','ex'=>'Wer ist das?','ext'=>'Bu kim?'],
        ['g'=>'was','tr'=>'ne','pos'=>'pronoun','top'=>'w_fragen','ex'=>'Was machst du?','ext'=>'Ne yapıyorsun?'],
        ['g'=>'wo','tr'=>'nerede','pos'=>'adverb','top'=>'w_fragen','ex'=>'Wo ist die Toilette?','ext'=>'Tuvalet nerede?','sim'=>'wo = nerede (durum), wohin = nereye (hareket).'],
        ['g'=>'wohin','tr'=>'nereye','pos'=>'adverb','top'=>'w_fragen','ex'=>'Wohin gehst du?','ext'=>'Nereye gidiyorsun?'],
        ['g'=>'woher','tr'=>'nereden','pos'=>'adverb','top'=>'w_fragen','ex'=>'Woher kommst du?','ext'=>'Nereden geliyorsun?'],
        ['g'=>'wann','tr'=>'ne zaman','pos'=>'adverb','top'=>'w_fragen','ex'=>'Wann beginnt die Arbeit?','ext'=>'İş ne zaman başlıyor?'],
        ['g'=>'wie','tr'=>'nasıl','pos'=>'adverb','top'=>'w_fragen','ex'=>'Wie heißt du?','ext'=>'Adın ne?'],
        ['g'=>'warum','tr'=>'neden','pos'=>'adverb','top'=>'w_fragen','ex'=>'Warum bist du müde?','ext'=>'Neden yorgunsun?'],
        ['g'=>'wie viel','tr'=>'ne kadar','pos'=>'phrase','top'=>'w_fragen','ex'=>'Wie viel kostet das?','ext'=>'Bu ne kadar?'],
        ['g'=>'wie viele','tr'=>'kaç tane','pos'=>'phrase','top'=>'w_fragen','ex'=>'Wie viele Kinder haben Sie?','ext'=>'Kaç çocuğunuz var?'],
        ['g'=>'welcher','tr'=>'hangi','pos'=>'pronoun','top'=>'w_fragen','ex'=>'Welcher Bus fährt zum Bahnhof?','ext'=>'Hangi otobüs gara gidiyor?','note'=>'Cinsiyete göre değişir: welcher / welche / welches.'],

        /* --- İyelik --- */
        ['g'=>'mein','tr'=>'benim','pos'=>'article','top'=>'possessiv','ex'=>'Mein Bruder wohnt in Hamburg.','ext'=>'Kardeşim Hamburg\'da oturuyor.','note'=>'Kadın ve çoğul isimlerde "meine" olur.'],
        ['g'=>'dein','tr'=>'senin','pos'=>'article','top'=>'possessiv','ex'=>'Ist das dein Auto?','ext'=>'Bu senin araban mı?'],
        ['g'=>'sein','tr'=>'onun (erkek)','pos'=>'article','top'=>'possessiv','ex'=>'Sein Chef ist streng.','ext'=>'Onun patronu katı.','sim'=>'sein hem "olmak" fiili hem "onun" iyeliğidir; cümledeki yerine bak.'],
        ['g'=>'ihr','tr'=>'onun (kadın); onların','pos'=>'article','top'=>'possessiv','ex'=>'Ihre Mutter kommt morgen.','ext'=>'Onun annesi yarın geliyor.'],
        ['g'=>'unser','tr'=>'bizim','pos'=>'article','top'=>'possessiv','ex'=>'Unser Team ist klein.','ext'=>'Ekibimiz küçük.'],

        /* --- Zaman --- */
        ['g'=>'Montag','a'=>'der','pl'=>'die Montage','tr'=>'pazartesi','pos'=>'noun','top'=>'wochentage','ex'=>'Am Montag arbeite ich.','ext'=>'Pazartesi çalışıyorum.','note'=>'Günlerle "am" kullanılır: am Montag.'],
        ['g'=>'Dienstag','a'=>'der','pl'=>'die Dienstage','tr'=>'salı','pos'=>'noun','top'=>'wochentage','ex'=>'Der Termin ist am Dienstag.','ext'=>'Randevu salı günü.'],
        ['g'=>'Mittwoch','a'=>'der','pl'=>'die Mittwoche','tr'=>'çarşamba','pos'=>'noun','top'=>'wochentage','ex'=>'Am Mittwoch habe ich frei.','ext'=>'Çarşamba iznim var.','tip'=>'Mitte (orta) + Woche (hafta) = haftanın ortası.'],
        ['g'=>'Donnerstag','a'=>'der','pl'=>'die Donnerstage','tr'=>'perşembe','pos'=>'noun','top'=>'wochentage','ex'=>'Donnerstag ist Besprechung.','ext'=>'Perşembe toplantı var.'],
        ['g'=>'Freitag','a'=>'der','pl'=>'die Freitage','tr'=>'cuma','pos'=>'noun','top'=>'wochentage','ex'=>'Am Freitag ist Feierabend um 15 Uhr.','ext'=>'Cuma mesai 15\'te bitiyor.'],
        ['g'=>'Samstag','a'=>'der','pl'=>'die Samstage','tr'=>'cumartesi','pos'=>'noun','top'=>'wochentage','ex'=>'Am Samstag kaufe ich ein.','ext'=>'Cumartesi alışveriş yapıyorum.','sim'=>'Kuzey Almanya\'da "Sonnabend" de kullanılır.'],
        ['g'=>'Sonntag','a'=>'der','pl'=>'die Sonntage','tr'=>'pazar','pos'=>'noun','top'=>'wochentage','ex'=>'Am Sonntag sind die Geschäfte geschlossen.','ext'=>'Pazar günü mağazalar kapalı.'],
        ['g'=>'Januar','a'=>'der','tr'=>'ocak','pos'=>'noun','top'=>'monate','ex'=>'Im Januar ist es kalt.','ext'=>'Ocakta hava soğuk.','note'=>'Aylarla "im" kullanılır: im Januar.'],
        ['g'=>'Februar','a'=>'der','tr'=>'şubat','pos'=>'noun','top'=>'monate','ex'=>'Mein Vertrag beginnt im Februar.','ext'=>'Sözleşmem şubatta başlıyor.'],
        ['g'=>'März','a'=>'der','tr'=>'mart','pos'=>'noun','top'=>'monate','ex'=>'Im März fange ich an.','ext'=>'Martta başlıyorum.'],
        ['g'=>'April','a'=>'der','tr'=>'nisan','pos'=>'noun','top'=>'monate','ex'=>'Der Urlaub ist im April.','ext'=>'İzin nisanda.'],
        ['g'=>'Mai','a'=>'der','tr'=>'mayıs','pos'=>'noun','top'=>'monate','ex'=>'Der 1. Mai ist ein Feiertag.','ext'=>'1 Mayıs resmi tatil.'],
        ['g'=>'Juni','a'=>'der','tr'=>'haziran','pos'=>'noun','top'=>'monate','ex'=>'Im Juni wird es warm.','ext'=>'Haziranda hava ısınır.'],
        ['g'=>'Juli','a'=>'der','tr'=>'temmuz','pos'=>'noun','top'=>'monate','ex'=>'Im Juli habe ich Urlaub.','ext'=>'Temmuzda iznim var.'],
        ['g'=>'August','a'=>'der','tr'=>'ağustos','pos'=>'noun','top'=>'monate','ex'=>'Im August ist Ferienzeit.','ext'=>'Ağustos tatil dönemi.'],
        ['g'=>'September','a'=>'der','tr'=>'eylül','pos'=>'noun','top'=>'monate','ex'=>'Die Schule beginnt im September.','ext'=>'Okul eylülde başlıyor.'],
        ['g'=>'Oktober','a'=>'der','tr'=>'ekim','pos'=>'noun','top'=>'monate','ex'=>'Im Oktober wird es kühl.','ext'=>'Ekimde hava serinler.'],
        ['g'=>'November','a'=>'der','tr'=>'kasım','pos'=>'noun','top'=>'monate','ex'=>'Der November ist grau.','ext'=>'Kasım gri geçer.'],
        ['g'=>'Dezember','a'=>'der','tr'=>'aralık','pos'=>'noun','top'=>'monate','ex'=>'Im Dezember ist Weihnachten.','ext'=>'Aralıkta Noel var.'],
        ['g'=>'heute','tr'=>'bugün','pos'=>'adverb','top'=>'zeit','ex'=>'Heute arbeite ich nicht.','ext'=>'Bugün çalışmıyorum.'],
        ['g'=>'morgen','tr'=>'yarın','pos'=>'adverb','top'=>'zeit','ex'=>'Morgen habe ich einen Termin.','ext'=>'Yarın bir randevum var.','sim'=>'morgen = yarın (küçük harf), der Morgen = sabah (büyük harf).'],
        ['g'=>'gestern','tr'=>'dün','pos'=>'adverb','top'=>'zeit','ex'=>'Gestern war ich krank.','ext'=>'Dün hastaydım.'],
        ['g'=>'jetzt','tr'=>'şimdi','pos'=>'adverb','top'=>'zeit','ex'=>'Ich muss jetzt gehen.','ext'=>'Şimdi gitmem gerek.'],
        ['g'=>'früh','tr'=>'erken','pos'=>'adjective','top'=>'zeit','ex'=>'Ich stehe früh auf.','ext'=>'Erken kalkıyorum.'],
        ['g'=>'spät','tr'=>'geç','pos'=>'adjective','top'=>'zeit','ex'=>'Es ist schon spät.','ext'=>'Saat çoktan geç oldu.'],
        ['g'=>'Minute','a'=>'die','pl'=>'die Minuten','tr'=>'dakika','pos'=>'noun','top'=>'zeit','ex'=>'Warten Sie bitte fünf Minuten.','ext'=>'Lütfen beş dakika bekleyin.'],
        ['g'=>'Stunde','a'=>'die','pl'=>'die Stunden','tr'=>'saat (süre)','pos'=>'noun','top'=>'zeit','ex'=>'Ich arbeite acht Stunden.','ext'=>'Sekiz saat çalışıyorum.','sim'=>'die Stunde = süre; die Uhr = saat aleti ve saat kaç.'],
        ['g'=>'Vormittag','a'=>'der','pl'=>'die Vormittage','tr'=>'öğleden önce','pos'=>'noun','top'=>'zeit','ex'=>'Am Vormittag habe ich Zeit.','ext'=>'Öğleden önce vaktim var.'],
        ['g'=>'Mittag','a'=>'der','pl'=>'die Mittage','tr'=>'öğle','pos'=>'noun','top'=>'zeit','ex'=>'Zu Mittag esse ich in der Kantine.','ext'=>'Öğlen kantinde yemek yiyorum.'],
        ['g'=>'Nachmittag','a'=>'der','pl'=>'die Nachmittage','tr'=>'öğleden sonra','pos'=>'noun','top'=>'zeit','ex'=>'Am Nachmittag habe ich frei.','ext'=>'Öğleden sonra boşum.'],

        /* --- Aile --- */
        ['g'=>'Familie','a'=>'die','pl'=>'die Familien','tr'=>'aile','pos'=>'noun','top'=>'familie','ex'=>'Meine Familie lebt in der Türkei.','ext'=>'Ailem Türkiye\'de yaşıyor.'],
        ['g'=>'Mutter','a'=>'die','pl'=>'die Mütter','tr'=>'anne','pos'=>'noun','top'=>'familie','ex'=>'Meine Mutter kocht gut.','ext'=>'Annem güzel yemek yapar.','tip'=>'Çoğulda umlaut gelir: Mutter → Mütter.'],
        ['g'=>'Vater','a'=>'der','pl'=>'die Väter','tr'=>'baba','pos'=>'noun','top'=>'familie','ex'=>'Mein Vater ist Rentner.','ext'=>'Babam emekli.'],
        ['g'=>'Eltern','a'=>'die','pl'=>'die Eltern','tr'=>'ebeveynler','pos'=>'noun','top'=>'familie','ex'=>'Meine Eltern wohnen in Izmir.','ext'=>'Ailem İzmir\'de oturuyor.','note'=>'Sadece çoğul kullanılır.'],
        ['g'=>'Kind','a'=>'das','pl'=>'die Kinder','tr'=>'çocuk','pos'=>'noun','top'=>'familie','ex'=>'Wir haben zwei Kinder.','ext'=>'İki çocuğumuz var.'],
        ['g'=>'Sohn','a'=>'der','pl'=>'die Söhne','tr'=>'oğul','pos'=>'noun','top'=>'familie','ex'=>'Mein Sohn geht zur Schule.','ext'=>'Oğlum okula gidiyor.'],
        ['g'=>'Tochter','a'=>'die','pl'=>'die Töchter','tr'=>'kız evlat','pos'=>'noun','top'=>'familie','ex'=>'Meine Tochter ist fünf Jahre alt.','ext'=>'Kızım beş yaşında.'],
        ['g'=>'Bruder','a'=>'der','pl'=>'die Brüder','tr'=>'erkek kardeş','pos'=>'noun','top'=>'familie','ex'=>'Mein Bruder arbeitet in München.','ext'=>'Kardeşim Münih\'te çalışıyor.'],
        ['g'=>'Schwester','a'=>'die','pl'=>'die Schwestern','tr'=>'kız kardeş','pos'=>'noun','top'=>'familie','ex'=>'Meine Schwester studiert.','ext'=>'Kız kardeşim üniversitede okuyor.'],
        ['g'=>'Ehefrau','a'=>'die','pl'=>'die Ehefrauen','tr'=>'eş (kadın)','pos'=>'noun','top'=>'familie','ex'=>'Meine Ehefrau heißt Zeynep.','ext'=>'Eşimin adı Zeynep.'],
        ['g'=>'Ehemann','a'=>'der','pl'=>'die Ehemänner','tr'=>'eş (erkek)','pos'=>'noun','top'=>'familie','ex'=>'Ihr Ehemann arbeitet bei BMW.','ext'=>'Eşi BMW\'de çalışıyor.'],
        ['g'=>'Freund','a'=>'der','pl'=>'die Freunde','tr'=>'arkadaş (erkek)','pos'=>'noun','top'=>'familie','ex'=>'Ein Freund hilft mir.','ext'=>'Bir arkadaşım bana yardım ediyor.'],

        /* --- Ev --- */
        ['g'=>'Wohnung','a'=>'die','pl'=>'die Wohnungen','tr'=>'daire, ev','pos'=>'noun','top'=>'wohnen','ex'=>'Ich suche eine Wohnung.','ext'=>'Bir daire arıyorum.','tip'=>'-ung ile biten isimler her zaman "die" alır.'],
        ['g'=>'Haus','a'=>'das','pl'=>'die Häuser','tr'=>'ev, bina','pos'=>'noun','top'=>'wohnen','ex'=>'Das Haus ist alt.','ext'=>'Ev eski.'],
        ['g'=>'Zimmer','a'=>'das','pl'=>'die Zimmer','tr'=>'oda','pos'=>'noun','top'=>'wohnen','ex'=>'Die Wohnung hat drei Zimmer.','ext'=>'Dairenin üç odası var.','tip'=>'-er ile biten nötr isimler çoğulda değişmez.'],
        ['g'=>'Küche','a'=>'die','pl'=>'die Küchen','tr'=>'mutfak','pos'=>'noun','top'=>'wohnen','ex'=>'Die Küche ist klein.','ext'=>'Mutfak küçük.'],
        ['g'=>'Bad','a'=>'das','pl'=>'die Bäder','tr'=>'banyo','pos'=>'noun','top'=>'wohnen','ex'=>'Das Bad hat kein Fenster.','ext'=>'Banyonun penceresi yok.'],
        ['g'=>'Schlafzimmer','a'=>'das','pl'=>'die Schlafzimmer','tr'=>'yatak odası','pos'=>'noun','top'=>'wohnen','ex'=>'Das Schlafzimmer ist ruhig.','ext'=>'Yatak odası sessiz.'],
        ['g'=>'Tisch','a'=>'der','pl'=>'die Tische','tr'=>'masa','pos'=>'noun','top'=>'wohnen','pr'=>'TİŞ','ex'=>'Der Tisch steht in der Küche.','ext'=>'Masa mutfakta duruyor.','tip'=>'İsimleri her zaman artikeli ve çoğuluyla öğren: der Tisch – die Tische.'],
        ['g'=>'Stuhl','a'=>'der','pl'=>'die Stühle','tr'=>'sandalye','pos'=>'noun','top'=>'wohnen','ex'=>'Nehmen Sie bitte einen Stuhl.','ext'=>'Lütfen bir sandalye alın.'],
        ['g'=>'Bett','a'=>'das','pl'=>'die Betten','tr'=>'yatak','pos'=>'noun','top'=>'wohnen','ex'=>'Das Bett ist bequem.','ext'=>'Yatak rahat.'],
        ['g'=>'Lampe','a'=>'die','pl'=>'die Lampen','tr'=>'lamba','pos'=>'noun','top'=>'wohnen','ex'=>'Die Lampe ist kaputt.','ext'=>'Lamba bozuk.','tip'=>'-e ile biten isimlerin çoğu "die" alır.'],
        ['g'=>'Fenster','a'=>'das','pl'=>'die Fenster','tr'=>'pencere','pos'=>'noun','top'=>'wohnen','ex'=>'Bitte machen Sie das Fenster zu.','ext'=>'Lütfen pencereyi kapatın.'],
        ['g'=>'Tür','a'=>'die','pl'=>'die Türen','tr'=>'kapı','pos'=>'noun','top'=>'wohnen','ex'=>'Die Tür ist offen.','ext'=>'Kapı açık.'],
        ['g'=>'Schlüssel','a'=>'der','pl'=>'die Schlüssel','tr'=>'anahtar','pos'=>'noun','top'=>'wohnen','ex'=>'Ich habe meinen Schlüssel vergessen.','ext'=>'Anahtarımı unuttum.'],
        ['g'=>'Miete','a'=>'die','pl'=>'die Mieten','tr'=>'kira','pos'=>'noun','top'=>'wohnen','ex'=>'Die Miete ist 700 Euro.','ext'=>'Kira 700 euro.'],

        /* --- Yiyecek içecek --- */
        ['g'=>'Wasser','a'=>'das','pl'=>'die Wässer','tr'=>'su','pos'=>'noun','top'=>'essen','ex'=>'Ein Glas Wasser, bitte.','ext'=>'Bir bardak su, lütfen.','note'=>'Günlük dilde çoğulu neredeyse hiç kullanılmaz.'],
        ['g'=>'Kaffee','a'=>'der','pl'=>'die Kaffees','tr'=>'kahve','pos'=>'noun','top'=>'essen','ex'=>'Ich trinke einen Kaffee.','ext'=>'Bir kahve içiyorum.'],
        ['g'=>'Tee','a'=>'der','pl'=>'die Tees','tr'=>'çay','pos'=>'noun','top'=>'essen','ex'=>'Möchten Sie Tee oder Kaffee?','ext'=>'Çay mı kahve mi istersiniz?'],
        ['g'=>'Brot','a'=>'das','pl'=>'die Brote','tr'=>'ekmek','pos'=>'noun','top'=>'essen','ex'=>'Ich kaufe Brot beim Bäcker.','ext'=>'Fırıncıdan ekmek alıyorum.'],
        ['g'=>'Brötchen','a'=>'das','pl'=>'die Brötchen','tr'=>'küçük ekmek, sandviç ekmeği','pos'=>'noun','top'=>'essen','ex'=>'Zwei Brötchen, bitte.','ext'=>'İki ekmek, lütfen.','tip'=>'-chen küçültme ekidir ve daima "das" alır.'],
        ['g'=>'Milch','a'=>'die','tr'=>'süt','pos'=>'noun','top'=>'essen','ex'=>'Mit Milch, bitte.','ext'=>'Sütlü, lütfen.'],
        ['g'=>'Ei','a'=>'das','pl'=>'die Eier','tr'=>'yumurta','pos'=>'noun','top'=>'essen','ex'=>'Ich esse ein Ei zum Frühstück.','ext'=>'Kahvaltıda bir yumurta yiyorum.'],
        ['g'=>'Fleisch','a'=>'das','tr'=>'et','pos'=>'noun','top'=>'essen','ex'=>'Ich esse kein Schweinefleisch.','ext'=>'Domuz eti yemiyorum.'],
        ['g'=>'Obst','a'=>'das','tr'=>'meyve','pos'=>'noun','top'=>'essen','ex'=>'Obst ist gesund.','ext'=>'Meyve sağlıklıdır.'],
        ['g'=>'Gemüse','a'=>'das','tr'=>'sebze','pos'=>'noun','top'=>'essen','ex'=>'Ich kaufe Gemüse auf dem Markt.','ext'=>'Pazardan sebze alıyorum.'],
        ['g'=>'Frühstück','a'=>'das','pl'=>'die Frühstücke','tr'=>'kahvaltı','pos'=>'noun','top'=>'essen','ex'=>'Das Frühstück ist um sieben.','ext'=>'Kahvaltı yedide.'],
        ['g'=>'Mittagessen','a'=>'das','pl'=>'die Mittagessen','tr'=>'öğle yemeği','pos'=>'noun','top'=>'essen','ex'=>'Das Mittagessen dauert 30 Minuten.','ext'=>'Öğle yemeği 30 dakika sürüyor.'],
        ['g'=>'Abendessen','a'=>'das','pl'=>'die Abendessen','tr'=>'akşam yemeği','pos'=>'noun','top'=>'essen','ex'=>'Zum Abendessen gibt es Suppe.','ext'=>'Akşam yemeğinde çorba var.'],
        ['g'=>'Rechnung','a'=>'die','pl'=>'die Rechnungen','tr'=>'hesap, fatura','pos'=>'noun','top'=>'restaurant','ex'=>'Die Rechnung, bitte!','ext'=>'Hesap, lütfen!'],
        ['g'=>'Speisekarte','a'=>'die','pl'=>'die Speisekarten','tr'=>'menü','pos'=>'noun','top'=>'restaurant','ex'=>'Die Speisekarte, bitte.','ext'=>'Menü, lütfen.'],
        ['g'=>'Kellner','a'=>'der','pl'=>'die Kellner','tr'=>'garson','pos'=>'noun','top'=>'restaurant','ex'=>'Der Kellner bringt das Essen.','ext'=>'Garson yemeği getiriyor.'],
        ['g'=>'bestellen','tr'=>'sipariş vermek','pos'=>'verb','top'=>'restaurant','p3'=>'bestellt','pret'=>'bestellte','p2'=>'bestellt','aux'=>'haben','case'=>'akkusativ','ex'=>'Ich bestelle eine Suppe.','ext'=>'Bir çorba sipariş ediyorum.','note'=>'be- ön eki ayrılmaz, Partizip II ge- almaz.'],
        ['g'=>'bezahlen','tr'=>'ödemek','pos'=>'verb','top'=>'restaurant','p3'=>'bezahlt','pret'=>'bezahlte','p2'=>'bezahlt','aux'=>'haben','ex'=>'Ich möchte bezahlen.','ext'=>'Ödemek istiyorum.'],

        /* --- Alışveriş ve para --- */
        ['g'=>'Geld','a'=>'das','tr'=>'para','pos'=>'noun','top'=>'einkaufen','ex'=>'Ich habe kein Geld dabei.','ext'=>'Yanımda param yok.'],
        ['g'=>'Euro','a'=>'der','pl'=>'die Euro','tr'=>'euro','pos'=>'noun','top'=>'einkaufen','ex'=>'Das kostet zehn Euro.','ext'=>'Bu on euro.','note'=>'Fiyat söylerken çoğulda da "Euro" kalır.'],
        ['g'=>'Preis','a'=>'der','pl'=>'die Preise','tr'=>'fiyat','pos'=>'noun','top'=>'einkaufen','ex'=>'Der Preis ist zu hoch.','ext'=>'Fiyat çok yüksek.'],
        ['g'=>'Supermarkt','a'=>'der','pl'=>'die Supermärkte','tr'=>'süpermarket','pos'=>'noun','top'=>'einkaufen','ex'=>'Der Supermarkt schließt um 20 Uhr.','ext'=>'Süpermarket 20\'de kapanıyor.'],
        ['g'=>'Geschäft','a'=>'das','pl'=>'die Geschäfte','tr'=>'dükkan, mağaza','pos'=>'noun','top'=>'einkaufen','ex'=>'Das Geschäft ist geschlossen.','ext'=>'Dükkan kapalı.'],
        ['g'=>'kaufen','tr'=>'satın almak','pos'=>'verb','top'=>'einkaufen','p3'=>'kauft','pret'=>'kaufte','p2'=>'gekauft','aux'=>'haben','case'=>'akkusativ','ex'=>'Ich kaufe den Kaffee.','ext'=>'Kahveyi satın alıyorum.'],
        ['g'=>'kosten','tr'=>'... etmek (fiyat)','pos'=>'verb','top'=>'einkaufen','p3'=>'kostet','pret'=>'kostete','p2'=>'gekostet','aux'=>'haben','ex'=>'Wie viel kostet das?','ext'=>'Bu ne kadar?'],
        ['g'=>'teuer','tr'=>'pahalı','pos'=>'adjective','top'=>'einkaufen','ex'=>'Die Wohnung ist teuer.','ext'=>'Daire pahalı.'],
        ['g'=>'billig','tr'=>'ucuz','pos'=>'adjective','top'=>'einkaufen','ex'=>'Das Brot ist billig.','ext'=>'Ekmek ucuz.','sim'=>'günstig daha nazik bir "uygun fiyatlı" ifadesidir.'],

        /* --- Şehir ve ulaşım --- */
        ['g'=>'Bahnhof','a'=>'der','pl'=>'die Bahnhöfe','tr'=>'tren garı','pos'=>'noun','top'=>'stadt','ex'=>'Wo ist der Bahnhof?','ext'=>'Tren garı nerede?'],
        ['g'=>'Zug','a'=>'der','pl'=>'die Züge','tr'=>'tren','pos'=>'noun','top'=>'stadt','ex'=>'Der Zug hat Verspätung.','ext'=>'Tren gecikmeli.'],
        ['g'=>'Bus','a'=>'der','pl'=>'die Busse','tr'=>'otobüs','pos'=>'noun','top'=>'stadt','ex'=>'Der Bus fährt um acht.','ext'=>'Otobüs sekizde kalkıyor.'],
        ['g'=>'Straßenbahn','a'=>'die','pl'=>'die Straßenbahnen','tr'=>'tramvay','pos'=>'noun','top'=>'stadt','ex'=>'Die Straßenbahn Nummer 5 fährt zum Zentrum.','ext'=>'5 numaralı tramvay merkeze gidiyor.'],
        ['g'=>'Fahrkarte','a'=>'die','pl'=>'die Fahrkarten','tr'=>'bilet','pos'=>'noun','top'=>'stadt','ex'=>'Eine Fahrkarte nach Köln, bitte.','ext'=>'Köln\'e bir bilet, lütfen.'],
        ['g'=>'Auto','a'=>'das','pl'=>'die Autos','tr'=>'araba','pos'=>'noun','top'=>'stadt','ex'=>'Das Auto ist neu.','ext'=>'Araba yeni.'],
        ['g'=>'Apotheke','a'=>'die','pl'=>'die Apotheken','tr'=>'eczane','pos'=>'noun','top'=>'stadt','ex'=>'Die Apotheke ist gegenüber.','ext'=>'Eczane karşıda.'],
        ['g'=>'Krankenhaus','a'=>'das','pl'=>'die Krankenhäuser','tr'=>'hastane','pos'=>'noun','top'=>'gesundheit','ex'=>'Das Krankenhaus ist in der Nähe.','ext'=>'Hastane yakınlarda.'],
        ['g'=>'Bank','a'=>'die','pl'=>'die Banken','tr'=>'banka','pos'=>'noun','top'=>'stadt','ex'=>'Ich gehe zur Bank.','ext'=>'Bankaya gidiyorum.','sim'=>'die Bank – die Bänke = oturma bankı; die Bank – die Banken = para bankası.'],
        ['g'=>'links','tr'=>'sol, solda','pos'=>'adverb','top'=>'weg','ex'=>'Gehen Sie links.','ext'=>'Sola gidin.'],
        ['g'=>'rechts','tr'=>'sağ, sağda','pos'=>'adverb','top'=>'weg','ex'=>'Die Apotheke ist rechts.','ext'=>'Eczane sağda.'],
        ['g'=>'geradeaus','tr'=>'dosdoğru','pos'=>'adverb','top'=>'weg','ex'=>'Gehen Sie geradeaus.','ext'=>'Dosdoğru gidin.'],

        /* --- Sağlık --- */
        ['g'=>'Termin','a'=>'der','pl'=>'die Termine','tr'=>'randevu','pos'=>'noun','top'=>'gesundheit','ex'=>'Ich möchte einen Termin machen.','ext'=>'Randevu almak istiyorum.'],
        ['g'=>'Schmerzen','a'=>'die','pl'=>'die Schmerzen','tr'=>'ağrılar','pos'=>'noun','top'=>'gesundheit','ex'=>'Ich habe Schmerzen im Rücken.','ext'=>'Sırtımda ağrı var.','note'=>'Genelde çoğul kullanılır: Ich habe Schmerzen.'],
        ['g'=>'krank','tr'=>'hasta','pos'=>'adjective','top'=>'gesundheit','ex'=>'Ich bin krank.','ext'=>'Hastayım.'],
        ['g'=>'gesund','tr'=>'sağlıklı','pos'=>'adjective','top'=>'gesundheit','ex'=>'Er ist wieder gesund.','ext'=>'O yine sağlıklı.'],
        ['g'=>'Medikament','a'=>'das','pl'=>'die Medikamente','tr'=>'ilaç','pos'=>'noun','top'=>'gesundheit','ex'=>'Nehmen Sie dieses Medikament dreimal am Tag.','ext'=>'Bu ilacı günde üç kez alın.'],

        /* --- İş temelleri --- */
        ['g'=>'Chef','a'=>'der','pl'=>'die Chefs','tr'=>'patron, amir','pos'=>'noun','top'=>'arbeit','pr'=>'ŞEF','ex'=>'Mein Chef ist heute nicht da.','ext'=>'Amirim bugün yok.'],
        ['g'=>'Kollege','a'=>'der','pl'=>'die Kollegen','tr'=>'iş arkadaşı (erkek)','pos'=>'noun','top'=>'arbeit','ex'=>'Mein Kollege hilft mir.','ext'=>'İş arkadaşım bana yardım ediyor.','note'=>'n-Deklination: den Kollegen.'],
        ['g'=>'Kollegin','a'=>'die','pl'=>'die Kolleginnen','tr'=>'iş arkadaşı (kadın)','pos'=>'noun','top'=>'arbeit','ex'=>'Meine Kollegin ist neu.','ext'=>'Kadın iş arkadaşım yeni.'],
        ['g'=>'Pause','a'=>'die','pl'=>'die Pausen','tr'=>'mola','pos'=>'noun','top'=>'arbeit','ex'=>'Wann ist die Pause?','ext'=>'Mola ne zaman?'],
        ['g'=>'Schicht','a'=>'die','pl'=>'die Schichten','tr'=>'vardiya','pos'=>'noun','top'=>'arbeit','ex'=>'Ich habe Frühschicht.','ext'=>'Sabah vardiyasındayım.'],
        ['g'=>'Feierabend','a'=>'der','pl'=>'die Feierabende','tr'=>'mesai bitişi','pos'=>'noun','top'=>'arbeit','ex'=>'Um 16 Uhr ist Feierabend.','ext'=>'Mesai 16\'da bitiyor.','note'=>'Almanya iş kültüründe çok kullanılan bir kelimedir.'],
        ['g'=>'Urlaub','a'=>'der','pl'=>'die Urlaube','tr'=>'izin, tatil','pos'=>'noun','top'=>'arbeit','ex'=>'Ich möchte Urlaub nehmen.','ext'=>'İzin almak istiyorum.'],
        ['g'=>'Arbeitszeit','a'=>'die','pl'=>'die Arbeitszeiten','tr'=>'çalışma saati','pos'=>'noun','top'=>'arbeit','ex'=>'Meine Arbeitszeit ist von 8 bis 16 Uhr.','ext'=>'Çalışma saatim 8\'den 16\'ya kadar.'],
        ['g'=>'Werkzeug','a'=>'das','pl'=>'die Werkzeuge','tr'=>'alet, takım','pos'=>'noun','top'=>'arbeit','ex'=>'Wo ist das Werkzeug?','ext'=>'Alet nerede?'],

        /* --- Sık kullanılan fiiller --- */
        ['g'=>'machen','tr'=>'yapmak','pos'=>'verb','top'=>'basis','p3'=>'macht','pret'=>'machte','p2'=>'gemacht','aux'=>'haben','case'=>'akkusativ','ex'=>'Was machst du?','ext'=>'Ne yapıyorsun?'],
        ['g'=>'gehen','tr'=>'gitmek (yürüyerek)','pos'=>'verb','top'=>'basis','p3'=>'geht','pret'=>'ging','p2'=>'gegangen','aux'=>'sein','irr'=>1,'ex'=>'Ich gehe zur Arbeit.','ext'=>'İşe gidiyorum.','sim'=>'gehen = yürüyerek; fahren = araçla.'],
        ['g'=>'fahren','tr'=>'gitmek (araçla), sürmek','pos'=>'verb','top'=>'basis','p3'=>'fährt','pret'=>'fuhr','p2'=>'gefahren','aux'=>'sein','irr'=>1,'ex'=>'Ich fahre mit dem Bus.','ext'=>'Otobüsle gidiyorum.','tip'=>'fahren – fährt – fuhr – ist gefahren: dördünü birlikte öğren.'],
        ['g'=>'essen','tr'=>'yemek','pos'=>'verb','top'=>'essen','p3'=>'isst','pret'=>'aß','p2'=>'gegessen','aux'=>'haben','irr'=>1,'case'=>'akkusativ','ex'=>'Ich esse einen Apfel.','ext'=>'Bir elma yiyorum.'],
        ['g'=>'trinken','tr'=>'içmek','pos'=>'verb','top'=>'essen','p3'=>'trinkt','pret'=>'trank','p2'=>'getrunken','aux'=>'haben','irr'=>1,'case'=>'akkusativ','ex'=>'Ich trinke Wasser.','ext'=>'Su içiyorum.'],
        ['g'=>'nehmen','tr'=>'almak','pos'=>'verb','top'=>'basis','p3'=>'nimmt','pret'=>'nahm','p2'=>'genommen','aux'=>'haben','irr'=>1,'case'=>'akkusativ','ex'=>'Ich nehme den Bus.','ext'=>'Otobüse biniyorum.'],
        ['g'=>'sehen','tr'=>'görmek','pos'=>'verb','top'=>'basis','p3'=>'sieht','pret'=>'sah','p2'=>'gesehen','aux'=>'haben','irr'=>1,'case'=>'akkusativ','ex'=>'Ich sehe den Bahnhof.','ext'=>'Garı görüyorum.'],
        ['g'=>'geben','tr'=>'vermek','pos'=>'verb','top'=>'basis','p3'=>'gibt','pret'=>'gab','p2'=>'gegeben','aux'=>'haben','irr'=>1,'ex'=>'Geben Sie mir bitte das Formular.','ext'=>'Lütfen bana formu verin.','note'=>'es gibt = "var" demektir ve Akkusativ ister.'],
        ['g'=>'finden','tr'=>'bulmak; ... bulmak (görüş)','pos'=>'verb','top'=>'basis','p3'=>'findet','pret'=>'fand','p2'=>'gefunden','aux'=>'haben','irr'=>1,'case'=>'akkusativ','ex'=>'Ich finde die Arbeit interessant.','ext'=>'İşi ilginç buluyorum.'],
        ['g'=>'brauchen','tr'=>'ihtiyaç duymak','pos'=>'verb','top'=>'basis','p3'=>'braucht','pret'=>'brauchte','p2'=>'gebraucht','aux'=>'haben','case'=>'akkusativ','ex'=>'Ich brauche einen Termin.','ext'=>'Bir randevuya ihtiyacım var.'],
        ['g'=>'aufstehen','tr'=>'kalkmak','pos'=>'verb','top'=>'alltag','p3'=>'steht auf','pret'=>'stand auf','p2'=>'aufgestanden','aux'=>'sein','irr'=>1,'sep'=>'auf','ex'=>'Ich stehe um sechs Uhr auf.','ext'=>'Saat altıda kalkıyorum.','tip'=>'Ayrılabilir fiilde ön ek cümlenin sonuna gider.'],
        ['g'=>'einkaufen','tr'=>'alışveriş yapmak','pos'=>'verb','top'=>'einkaufen','p3'=>'kauft ein','pret'=>'kaufte ein','p2'=>'eingekauft','aux'=>'haben','sep'=>'ein','ex'=>'Ich kaufe am Samstag ein.','ext'=>'Cumartesi alışveriş yapıyorum.'],
        ['g'=>'anfangen','tr'=>'başlamak','pos'=>'verb','top'=>'arbeit','p3'=>'fängt an','pret'=>'fing an','p2'=>'angefangen','aux'=>'haben','irr'=>1,'sep'=>'an','ex'=>'Die Arbeit fängt um sieben an.','ext'=>'İş yedide başlıyor.'],
        ['g'=>'ankommen','tr'=>'varmak','pos'=>'verb','top'=>'stadt','p3'=>'kommt an','pret'=>'kam an','p2'=>'angekommen','aux'=>'sein','irr'=>1,'sep'=>'an','ex'=>'Der Zug kommt um 9 Uhr an.','ext'=>'Tren 9\'da varıyor.'],
        ['g'=>'können','tr'=>'-ebilmek','pos'=>'verb','top'=>'modalverben','p3'=>'kann','pret'=>'konnte','p2'=>'gekonnt','aux'=>'haben','irr'=>1,'ex'=>'Ich kann Deutsch sprechen.','ext'=>'Almanca konuşabiliyorum.','note'=>'Modal fiilde ikinci fiil mastar olarak cümle sonuna gider.'],
        ['g'=>'müssen','tr'=>'zorunda olmak','pos'=>'verb','top'=>'modalverben','p3'=>'muss','pret'=>'musste','p2'=>'gemusst','aux'=>'haben','irr'=>1,'ex'=>'Ich muss früh aufstehen.','ext'=>'Erken kalkmam gerekiyor.'],
        ['g'=>'wollen','tr'=>'istemek','pos'=>'verb','top'=>'modalverben','p3'=>'will','pret'=>'wollte','p2'=>'gewollt','aux'=>'haben','irr'=>1,'ex'=>'Ich will in Deutschland arbeiten.','ext'=>'Almanya\'da çalışmak istiyorum.','sim'=>'möchten daha kibardır; wollen daha kararlı ve doğrudandır.'],
        ['g'=>'dürfen','tr'=>'izinli olmak','pos'=>'verb','top'=>'modalverben','p3'=>'darf','pret'=>'durfte','p2'=>'gedurft','aux'=>'haben','irr'=>1,'ex'=>'Darf ich hier rauchen?','ext'=>'Burada sigara içebilir miyim?'],
        ['g'=>'sollen','tr'=>'-meli, birinin isteği','pos'=>'verb','top'=>'modalverben','p3'=>'soll','pret'=>'sollte','p2'=>'gesollt','aux'=>'haben','irr'=>1,'ex'=>'Ich soll um acht da sein.','ext'=>'Sekizde orada olmam söylendi.'],
        ['g'=>'mögen','tr'=>'sevmek, hoşlanmak','pos'=>'verb','top'=>'modalverben','p3'=>'mag','pret'=>'mochte','p2'=>'gemocht','aux'=>'haben','irr'=>1,'ex'=>'Ich mag Kaffee.','ext'=>'Kahveyi severim.'],
        ['g'=>'möchten','tr'=>'istemek (kibar)','pos'=>'verb','top'=>'modalverben','p3'=>'möchte','ex'=>'Ich möchte einen Kaffee.','ext'=>'Bir kahve istiyorum.','note'=>'mögen fiilinin Konjunktiv II biçimidir; kibar istek için kullanılır.'],
        ['g'=>'schreiben','tr'=>'yazmak','pos'=>'verb','top'=>'basis','p3'=>'schreibt','pret'=>'schrieb','p2'=>'geschrieben','aux'=>'haben','irr'=>1,'ex'=>'Ich schreibe eine E-Mail.','ext'=>'Bir e-posta yazıyorum.'],
        ['g'=>'lesen','tr'=>'okumak','pos'=>'verb','top'=>'basis','p3'=>'liest','pret'=>'las','p2'=>'gelesen','aux'=>'haben','irr'=>1,'ex'=>'Ich lese den Vertrag.','ext'=>'Sözleşmeyi okuyorum.'],
        ['g'=>'helfen','tr'=>'yardım etmek','pos'=>'verb','top'=>'basis','p3'=>'hilft','pret'=>'half','p2'=>'geholfen','aux'=>'haben','irr'=>1,'case'=>'dativ','ex'=>'Kannst du mir helfen?','ext'=>'Bana yardım edebilir misin?','note'=>'helfen Dativ ister: jemandem helfen.'],
        ['g'=>'warten','tr'=>'beklemek','pos'=>'verb','top'=>'basis','p3'=>'wartet','pret'=>'wartete','p2'=>'gewartet','aux'=>'haben','prep'=>'auf + Akkusativ','ex'=>'Ich warte auf den Bus.','ext'=>'Otobüsü bekliyorum.'],

        /* --- Sıfatlar --- */
        ['g'=>'gut','tr'=>'iyi','pos'=>'adjective','top'=>'adjektive','ex'=>'Das Essen ist gut.','ext'=>'Yemek iyi.'],
        ['g'=>'schlecht','tr'=>'kötü','pos'=>'adjective','top'=>'adjektive','ex'=>'Das Wetter ist schlecht.','ext'=>'Hava kötü.'],
        ['g'=>'groß','tr'=>'büyük','pos'=>'adjective','top'=>'adjektive','ex'=>'Die Wohnung ist groß.','ext'=>'Daire büyük.'],
        ['g'=>'klein','tr'=>'küçük','pos'=>'adjective','top'=>'adjektive','ex'=>'Das Zimmer ist klein.','ext'=>'Oda küçük.'],
        ['g'=>'neu','tr'=>'yeni','pos'=>'adjective','top'=>'adjektive','ex'=>'Ich bin neu hier.','ext'=>'Burada yeniyim.'],
        ['g'=>'alt','tr'=>'eski; yaşlı','pos'=>'adjective','top'=>'adjektive','ex'=>'Das Haus ist alt.','ext'=>'Ev eski.'],
        ['g'=>'schön','tr'=>'güzel','pos'=>'adjective','top'=>'adjektive','ex'=>'Das ist eine schöne Stadt.','ext'=>'Bu güzel bir şehir.'],
        ['g'=>'schwer','tr'=>'zor; ağır','pos'=>'adjective','top'=>'adjektive','ex'=>'Deutsch ist nicht schwer.','ext'=>'Almanca zor değil.'],
        ['g'=>'einfach','tr'=>'kolay, basit','pos'=>'adjective','top'=>'adjektive','ex'=>'Das ist einfach.','ext'=>'Bu kolay.'],
        ['g'=>'wichtig','tr'=>'önemli','pos'=>'adjective','top'=>'adjektive','ex'=>'Pünktlichkeit ist wichtig.','ext'=>'Dakiklik önemlidir.'],
        ['g'=>'pünktlich','tr'=>'dakik','pos'=>'adjective','top'=>'arbeit','ex'=>'Bitte seien Sie pünktlich.','ext'=>'Lütfen dakik olun.','note'=>'Alman iş kültüründe çok önemli bir kavramdır.'],
        ['g'=>'müde','tr'=>'yorgun','pos'=>'adjective','top'=>'adjektive','ex'=>'Ich bin sehr müde.','ext'=>'Çok yorgunum.'],
        ['g'=>'kalt','tr'=>'soğuk','pos'=>'adjective','top'=>'adjektive','ex'=>'Heute ist es kalt.','ext'=>'Bugün hava soğuk.'],
        ['g'=>'warm','tr'=>'sıcak, ılık','pos'=>'adjective','top'=>'adjektive','ex'=>'Das Zimmer ist warm.','ext'=>'Oda sıcak.'],

        /* --- Yön ve bağlaçlar --- */
        ['g'=>'und','tr'=>'ve','pos'=>'conjunction','top'=>'konnektoren','ex'=>'Ich arbeite und lerne.','ext'=>'Çalışıyorum ve öğreniyorum.'],
        ['g'=>'aber','tr'=>'ama','pos'=>'conjunction','top'=>'konnektoren','ex'=>'Es ist schwer, aber interessant.','ext'=>'Zor ama ilginç.'],
        ['g'=>'oder','tr'=>'veya','pos'=>'conjunction','top'=>'konnektoren','ex'=>'Tee oder Kaffee?','ext'=>'Çay mı kahve mi?'],
        ['g'=>'auch','tr'=>'de, da','pos'=>'adverb','top'=>'konnektoren','ex'=>'Ich komme auch.','ext'=>'Ben de geliyorum.'],
        ['g'=>'sehr','tr'=>'çok','pos'=>'adverb','top'=>'konnektoren','ex'=>'Das ist sehr gut.','ext'=>'Bu çok iyi.'],
        ['g'=>'nicht','tr'=>'değil, -me','pos'=>'particle','top'=>'negation','ex'=>'Ich arbeite heute nicht.','ext'=>'Bugün çalışmıyorum.','note'=>'Fiili, sıfatı veya belirli bir ismi olumsuzlar.'],
        ['g'=>'kein','tr'=>'hiç, yok','pos'=>'article','top'=>'negation','ex'=>'Ich habe keine Zeit.','ext'=>'Vaktim yok.','note'=>'Artikelsiz veya "ein"li isimleri olumsuzlar.'],
        ['g'=>'immer','tr'=>'her zaman','pos'=>'adverb','top'=>'haeufigkeit','ex'=>'Ich bin immer pünktlich.','ext'=>'Her zaman dakiğimdir.'],
        ['g'=>'manchmal','tr'=>'bazen','pos'=>'adverb','top'=>'haeufigkeit','ex'=>'Manchmal arbeite ich samstags.','ext'=>'Bazen cumartesi çalışıyorum.'],
        ['g'=>'nie','tr'=>'asla','pos'=>'adverb','top'=>'haeufigkeit','ex'=>'Ich komme nie zu spät.','ext'=>'Asla geç kalmam.'],
        ['g'=>'oft','tr'=>'sık sık','pos'=>'adverb','top'=>'haeufigkeit','ex'=>'Ich fahre oft mit dem Zug.','ext'=>'Sık sık trenle gidiyorum.'],
    ];
}
